// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const changeDeviceState = `-- name: ChangeDeviceState :one
UPDATE devices
SET state = $1, version = version + 1, updated_at = $2
WHERE organization_id = $3
  AND id = $4
  AND version = $5
RETURNING id, organization_id, venue_id, name, platform, app_version,
          state, last_seen_at, version, created_at, updated_at
`

type ChangeDeviceStateParams struct {
	State           string    `json:"state"`
	UpdatedAt       time.Time `json:"updated_at"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int64     `json:"expected_version"`
}

type ChangeDeviceStateRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	VenueID        uuid.UUID          `json:"venue_id"`
	Name           string             `json:"name"`
	Platform       string             `json:"platform"`
	AppVersion     string             `json:"app_version"`
	State          string             `json:"state"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) ChangeDeviceState(ctx context.Context, arg ChangeDeviceStateParams) (ChangeDeviceStateRow, error) {
	row := q.db.QueryRow(ctx, changeDeviceState,
		arg.State,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i ChangeDeviceStateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.State,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, organization_id, venue_id, name, platform, app_version,
       state, last_seen_at, version, created_at, updated_at
FROM devices
WHERE organization_id = $1
  AND id = $2
`

type GetDeviceParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetDeviceRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	VenueID        uuid.UUID          `json:"venue_id"`
	Name           string             `json:"name"`
	Platform       string             `json:"platform"`
	AppVersion     string             `json:"app_version"`
	State          string             `json:"state"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (GetDeviceRow, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.OrganizationID, arg.ID)
	var i GetDeviceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.State,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceAssignmentForUpdate = `-- name: GetDeviceAssignmentForUpdate :one
SELECT id, organization_id, device_id, session_id, gate_id, capability,
       state, valid_from, valid_until, version, created_at, updated_at
FROM device_assignments
WHERE organization_id = $1
  AND device_id = $2
  AND id = $3
FOR UPDATE
`

type GetDeviceAssignmentForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	DeviceID       uuid.UUID `json:"device_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetDeviceAssignmentForUpdate(ctx context.Context, arg GetDeviceAssignmentForUpdateParams) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, getDeviceAssignmentForUpdate, arg.OrganizationID, arg.DeviceID, arg.ID)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.SessionID,
		&i.GateID,
		&i.Capability,
		&i.State,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceForUpdate = `-- name: GetDeviceForUpdate :one
SELECT id, organization_id, venue_id, name, platform, app_version,
       state, last_seen_at, version, created_at, updated_at
FROM devices
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type GetDeviceForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetDeviceForUpdateRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	VenueID        uuid.UUID          `json:"venue_id"`
	Name           string             `json:"name"`
	Platform       string             `json:"platform"`
	AppVersion     string             `json:"app_version"`
	State          string             `json:"state"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) GetDeviceForUpdate(ctx context.Context, arg GetDeviceForUpdateParams) (GetDeviceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getDeviceForUpdate, arg.OrganizationID, arg.ID)
	var i GetDeviceForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.State,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (
    id, organization_id, venue_id, name, platform, app_version,
    credential_hash, state, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11
)
RETURNING id, organization_id, venue_id, name, platform, app_version,
          state, last_seen_at, version, created_at, updated_at
`

type InsertDeviceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	VenueID        uuid.UUID `json:"venue_id"`
	Name           string    `json:"name"`
	Platform       string    `json:"platform"`
	AppVersion     string    `json:"app_version"`
	CredentialHash []byte    `json:"credential_hash"`
	State          string    `json:"state"`
	Version        int64     `json:"version"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type InsertDeviceRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	VenueID        uuid.UUID          `json:"venue_id"`
	Name           string             `json:"name"`
	Platform       string             `json:"platform"`
	AppVersion     string             `json:"app_version"`
	State          string             `json:"state"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (InsertDeviceRow, error) {
	row := q.db.QueryRow(ctx, insertDevice,
		arg.ID,
		arg.OrganizationID,
		arg.VenueID,
		arg.Name,
		arg.Platform,
		arg.AppVersion,
		arg.CredentialHash,
		arg.State,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsertDeviceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.State,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeviceAssignment = `-- name: InsertDeviceAssignment :one
INSERT INTO device_assignments (
    id, organization_id, device_id, session_id, gate_id, capability,
    state, valid_from, valid_until, version, created_at, updated_at
) VALUES (
    $1, $2, $3,
    NULLIF($4, '00000000-0000-0000-0000-000000000000')::uuid,
    NULLIF($5, '00000000-0000-0000-0000-000000000000')::uuid,
    $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, organization_id, device_id, session_id, gate_id, capability,
          state, valid_from, valid_until, version, created_at, updated_at
`

type InsertDeviceAssignmentParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	DeviceID       uuid.UUID          `json:"device_id"`
	SessionID      interface{}        `json:"session_id"`
	GateID         interface{}        `json:"gate_id"`
	Capability     string             `json:"capability"`
	State          string             `json:"state"`
	ValidFrom      time.Time          `json:"valid_from"`
	ValidUntil     pgtype.Timestamptz `json:"valid_until"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) InsertDeviceAssignment(ctx context.Context, arg InsertDeviceAssignmentParams) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, insertDeviceAssignment,
		arg.ID,
		arg.OrganizationID,
		arg.DeviceID,
		arg.SessionID,
		arg.GateID,
		arg.Capability,
		arg.State,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.SessionID,
		&i.GateID,
		&i.Capability,
		&i.State,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceAssignments = `-- name: ListDeviceAssignments :many
SELECT id, organization_id, device_id, session_id, gate_id, capability,
       state, valid_from, valid_until, version, created_at, updated_at
FROM device_assignments
WHERE organization_id = $1
  AND device_id = $2
  AND (
      $3::timestamptz IS NULL
      OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListDeviceAssignmentsParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	DeviceID       uuid.UUID          `json:"device_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	LimitCount     int32              `json:"limit_count"`
}

func (q *Queries) ListDeviceAssignments(ctx context.Context, arg ListDeviceAssignmentsParams) ([]DeviceAssignment, error) {
	rows, err := q.db.Query(ctx, listDeviceAssignments,
		arg.OrganizationID,
		arg.DeviceID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceAssignment{}
	for rows.Next() {
		var i DeviceAssignment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeviceID,
			&i.SessionID,
			&i.GateID,
			&i.Capability,
			&i.State,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, organization_id, venue_id, name, platform, app_version,
       state, last_seen_at, version, created_at, updated_at
FROM devices
WHERE organization_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListDevicesParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	LimitCount     int32              `json:"limit_count"`
}

type ListDevicesRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	VenueID        uuid.UUID          `json:"venue_id"`
	Name           string             `json:"name"`
	Platform       string             `json:"platform"`
	AppVersion     string             `json:"app_version"`
	State          string             `json:"state"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.OrganizationID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesRow{}
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VenueID,
			&i.Name,
			&i.Platform,
			&i.AppVersion,
			&i.State,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeviceForAssignment = `-- name: LockDeviceForAssignment :one
SELECT id, state
FROM devices
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockDeviceForAssignmentParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	DeviceID       uuid.UUID `json:"device_id"`
}

type LockDeviceForAssignmentRow struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) LockDeviceForAssignment(ctx context.Context, arg LockDeviceForAssignmentParams) (LockDeviceForAssignmentRow, error) {
	row := q.db.QueryRow(ctx, lockDeviceForAssignment, arg.OrganizationID, arg.DeviceID)
	var i LockDeviceForAssignmentRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const lockVenueForDevice = `-- name: LockVenueForDevice :one
SELECT id, status
FROM venues
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockVenueForDeviceParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	VenueID        uuid.UUID `json:"venue_id"`
}

type LockVenueForDeviceRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) LockVenueForDevice(ctx context.Context, arg LockVenueForDeviceParams) (LockVenueForDeviceRow, error) {
	row := q.db.QueryRow(ctx, lockVenueForDevice, arg.OrganizationID, arg.VenueID)
	var i LockVenueForDeviceRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const lookupDeviceByCredentialHash = `-- name: LookupDeviceByCredentialHash :one
SELECT id, organization_id, venue_id, name, platform, app_version,
       state, last_seen_at, version, created_at, updated_at
FROM devices
WHERE credential_hash = $1
`

type LookupDeviceByCredentialHashRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	VenueID        uuid.UUID          `json:"venue_id"`
	Name           string             `json:"name"`
	Platform       string             `json:"platform"`
	AppVersion     string             `json:"app_version"`
	State          string             `json:"state"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) LookupDeviceByCredentialHash(ctx context.Context, credentialHash []byte) (LookupDeviceByCredentialHashRow, error) {
	row := q.db.QueryRow(ctx, lookupDeviceByCredentialHash, credentialHash)
	var i LookupDeviceByCredentialHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.Name,
		&i.Platform,
		&i.AppVersion,
		&i.State,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeDeviceAssignment = `-- name: RevokeDeviceAssignment :one
UPDATE device_assignments
SET state = 'revoked', version = version + 1, updated_at = $1
WHERE organization_id = $2
  AND device_id = $3
  AND id = $4
  AND version = $5
  AND state = 'active'
RETURNING id, organization_id, device_id, session_id, gate_id, capability,
          state, valid_from, valid_until, version, created_at, updated_at
`

type RevokeDeviceAssignmentParams struct {
	UpdatedAt       time.Time `json:"updated_at"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	DeviceID        uuid.UUID `json:"device_id"`
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) RevokeDeviceAssignment(ctx context.Context, arg RevokeDeviceAssignmentParams) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, revokeDeviceAssignment,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.DeviceID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DeviceID,
		&i.SessionID,
		&i.GateID,
		&i.Capability,
		&i.State,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
