// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ChangeDeviceState(ctx context.Context, arg ChangeDeviceStateParams) (ChangeDeviceStateRow, error)
	GetDevice(ctx context.Context, arg GetDeviceParams) (GetDeviceRow, error)
	GetDeviceAssignmentForUpdate(ctx context.Context, arg GetDeviceAssignmentForUpdateParams) (DeviceAssignment, error)
	GetDeviceForUpdate(ctx context.Context, arg GetDeviceForUpdateParams) (GetDeviceForUpdateRow, error)
	InsertDevice(ctx context.Context, arg InsertDeviceParams) (InsertDeviceRow, error)
	InsertDeviceAssignment(ctx context.Context, arg InsertDeviceAssignmentParams) (DeviceAssignment, error)
	ListDeviceAssignments(ctx context.Context, arg ListDeviceAssignmentsParams) ([]DeviceAssignment, error)
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error)
	LockDeviceForAssignment(ctx context.Context, arg LockDeviceForAssignmentParams) (LockDeviceForAssignmentRow, error)
	LockVenueForDevice(ctx context.Context, arg LockVenueForDeviceParams) (LockVenueForDeviceRow, error)
	LookupDeviceByCredentialHash(ctx context.Context, credentialHash []byte) (LookupDeviceByCredentialHashRow, error)
	RevokeDeviceAssignment(ctx context.Context, arg RevokeDeviceAssignmentParams) (DeviceAssignment, error)
}

var _ Querier = (*Queries)(nil)
