// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ArchiveVenue(ctx context.Context, arg ArchiveVenueParams) (Venue, error)
	CloneSeatMapVersion(ctx context.Context, arg CloneSeatMapVersionParams) (SeatMapVersion, error)
	GetGAPoolSpace(ctx context.Context, arg GetGAPoolSpaceParams) (GetGAPoolSpaceRow, error)
	GetGAPoolTemplate(ctx context.Context, arg GetGAPoolTemplateParams) (GaPoolTemplate, error)
	GetGate(ctx context.Context, arg GetGateParams) (Gate, error)
	GetSeatMapVersion(ctx context.Context, arg GetSeatMapVersionParams) (SeatMapVersion, error)
	GetSeatMapVersionForUpdate(ctx context.Context, arg GetSeatMapVersionForUpdateParams) (SeatMapVersion, error)
	GetSpace(ctx context.Context, arg GetSpaceParams) (Space, error)
	GetVenue(ctx context.Context, arg GetVenueParams) (Venue, error)
	GetVenueForUpdate(ctx context.Context, arg GetVenueForUpdateParams) (Venue, error)
	InsertGAPoolTemplate(ctx context.Context, arg InsertGAPoolTemplateParams) (GaPoolTemplate, error)
	InsertGate(ctx context.Context, arg InsertGateParams) (Gate, error)
	InsertSeatMapVersion(ctx context.Context, arg InsertSeatMapVersionParams) (SeatMapVersion, error)
	InsertSpace(ctx context.Context, arg InsertSpaceParams) (Space, error)
	InsertVenue(ctx context.Context, arg InsertVenueParams) (Venue, error)
	ListGAPoolTemplates(ctx context.Context, arg ListGAPoolTemplatesParams) ([]GaPoolTemplate, error)
	ListGAPoolTemplatesAfter(ctx context.Context, arg ListGAPoolTemplatesAfterParams) ([]GaPoolTemplate, error)
	ListGates(ctx context.Context, arg ListGatesParams) ([]Gate, error)
	ListGatesAfter(ctx context.Context, arg ListGatesAfterParams) ([]Gate, error)
	ListSeatMapVersions(ctx context.Context, arg ListSeatMapVersionsParams) ([]SeatMapVersion, error)
	ListSeatMapVersionsAfter(ctx context.Context, arg ListSeatMapVersionsAfterParams) ([]SeatMapVersion, error)
	ListSpaces(ctx context.Context, arg ListSpacesParams) ([]Space, error)
	ListSpacesAfter(ctx context.Context, arg ListSpacesAfterParams) ([]Space, error)
	ListVenues(ctx context.Context, arg ListVenuesParams) ([]Venue, error)
	ListVenuesAfter(ctx context.Context, arg ListVenuesAfterParams) ([]Venue, error)
	LockSpace(ctx context.Context, arg LockSpaceParams) (LockSpaceRow, error)
	LockVenue(ctx context.Context, arg LockVenueParams) (LockVenueRow, error)
	NextSeatMapRevision(ctx context.Context, arg NextSeatMapRevisionParams) (int32, error)
	PublishSeatMapVersion(ctx context.Context, arg PublishSeatMapVersionParams) (SeatMapVersion, error)
	RestoreVenue(ctx context.Context, arg RestoreVenueParams) (Venue, error)
	RetirePublishedSeatMaps(ctx context.Context, arg RetirePublishedSeatMapsParams) error
	UpdateSeatMapDraft(ctx context.Context, arg UpdateSeatMapDraftParams) (SeatMapVersion, error)
	UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error)
}

var _ Querier = (*Queries)(nil)
