// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venue.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveVenue = `-- name: ArchiveVenue :one
UPDATE venues
SET status = 'archived', version = version + 1, updated_at = $4
WHERE organization_id = $1 AND id = $2 AND status <> 'archived' AND version = $3
RETURNING id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at
`

type ArchiveVenueParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	Version        int64     `json:"version"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ArchiveVenue(ctx context.Context, arg ArchiveVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, archiveVenue,
		arg.OrganizationID,
		arg.ID,
		arg.Version,
		arg.UpdatedAt,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.Timezone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cloneSeatMapVersion = `-- name: CloneSeatMapVersion :one
INSERT INTO seat_map_versions (id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, created_at, updated_at)
SELECT $1, source.organization_id, source.space_id, $4, 'draft', 0, source.checksum, source.content, source.seat_count, source.sellable_count, 1, $5, $5
FROM seat_map_versions AS source
WHERE source.organization_id = $2 AND source.space_id = $3 AND source.id = $6 AND source.status IN ('published', 'retired')
RETURNING id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, published_at, created_at, updated_at
`

type CloneSeatMapVersionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
	ID_2           uuid.UUID `json:"id_2"`
}

func (q *Queries) CloneSeatMapVersion(ctx context.Context, arg CloneSeatMapVersionParams) (SeatMapVersion, error) {
	row := q.db.QueryRow(ctx, cloneSeatMapVersion,
		arg.ID,
		arg.OrganizationID,
		arg.SpaceID,
		arg.Name,
		arg.CreatedAt,
		arg.ID_2,
	)
	var i SeatMapVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Status,
		&i.Revision,
		&i.Checksum,
		&i.Content,
		&i.SeatCount,
		&i.SellableCount,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGAPoolSpace = `-- name: GetGAPoolSpace :one
SELECT id, inventory_mode
FROM spaces
WHERE organization_id = $1 AND id = $2
`

type GetGAPoolSpaceParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetGAPoolSpaceRow struct {
	ID            uuid.UUID `json:"id"`
	InventoryMode string    `json:"inventory_mode"`
}

func (q *Queries) GetGAPoolSpace(ctx context.Context, arg GetGAPoolSpaceParams) (GetGAPoolSpaceRow, error) {
	row := q.db.QueryRow(ctx, getGAPoolSpace, arg.OrganizationID, arg.ID)
	var i GetGAPoolSpaceRow
	err := row.Scan(&i.ID, &i.InventoryMode)
	return i, err
}

const getGAPoolTemplate = `-- name: GetGAPoolTemplate :one
SELECT id, organization_id, space_id, slug, display_name, status, physical_capacity, sellable_capacity, version, created_at, updated_at
FROM ga_pool_templates
WHERE organization_id = $1 AND space_id = $2 AND id = $3
`

type GetGAPoolTemplateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetGAPoolTemplate(ctx context.Context, arg GetGAPoolTemplateParams) (GaPoolTemplate, error) {
	row := q.db.QueryRow(ctx, getGAPoolTemplate, arg.OrganizationID, arg.SpaceID, arg.ID)
	var i GaPoolTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.PhysicalCapacity,
		&i.SellableCapacity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGate = `-- name: GetGate :one
SELECT id, organization_id, venue_id, space_id, code, display_name, status, version, created_at, updated_at
FROM gates
WHERE organization_id = $1 AND venue_id = $2 AND id = $3
`

type GetGateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	VenueID        uuid.UUID `json:"venue_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetGate(ctx context.Context, arg GetGateParams) (Gate, error) {
	row := q.db.QueryRow(ctx, getGate, arg.OrganizationID, arg.VenueID, arg.ID)
	var i Gate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.SpaceID,
		&i.Code,
		&i.DisplayName,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeatMapVersion = `-- name: GetSeatMapVersion :one
SELECT id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, published_at, created_at, updated_at
FROM seat_map_versions
WHERE organization_id = $1 AND space_id = $2 AND id = $3
`

type GetSeatMapVersionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetSeatMapVersion(ctx context.Context, arg GetSeatMapVersionParams) (SeatMapVersion, error) {
	row := q.db.QueryRow(ctx, getSeatMapVersion, arg.OrganizationID, arg.SpaceID, arg.ID)
	var i SeatMapVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Status,
		&i.Revision,
		&i.Checksum,
		&i.Content,
		&i.SeatCount,
		&i.SellableCount,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeatMapVersionForUpdate = `-- name: GetSeatMapVersionForUpdate :one
SELECT id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, published_at, created_at, updated_at
FROM seat_map_versions
WHERE organization_id = $1 AND space_id = $2 AND id = $3
FOR UPDATE
`

type GetSeatMapVersionForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetSeatMapVersionForUpdate(ctx context.Context, arg GetSeatMapVersionForUpdateParams) (SeatMapVersion, error) {
	row := q.db.QueryRow(ctx, getSeatMapVersionForUpdate, arg.OrganizationID, arg.SpaceID, arg.ID)
	var i SeatMapVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Status,
		&i.Revision,
		&i.Checksum,
		&i.Content,
		&i.SeatCount,
		&i.SellableCount,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpace = `-- name: GetSpace :one
SELECT id, organization_id, venue_id, slug, display_name, status, inventory_mode, physical_capacity, version, created_at, updated_at
FROM spaces
WHERE organization_id = $1 AND venue_id = $2 AND id = $3
`

type GetSpaceParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	VenueID        uuid.UUID `json:"venue_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetSpace(ctx context.Context, arg GetSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, getSpace, arg.OrganizationID, arg.VenueID, arg.ID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.InventoryMode,
		&i.PhysicalCapacity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenue = `-- name: GetVenue :one
SELECT id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at
FROM venues
WHERE organization_id = $1 AND id = $2
`

type GetVenueParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetVenue(ctx context.Context, arg GetVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenue, arg.OrganizationID, arg.ID)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.Timezone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenueForUpdate = `-- name: GetVenueForUpdate :one
SELECT id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at
FROM venues
WHERE organization_id = $1 AND id = $2
FOR UPDATE
`

type GetVenueForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetVenueForUpdate(ctx context.Context, arg GetVenueForUpdateParams) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueForUpdate, arg.OrganizationID, arg.ID)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.Timezone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGAPoolTemplate = `-- name: InsertGAPoolTemplate :one
INSERT INTO ga_pool_templates (id, organization_id, space_id, slug, display_name, status, physical_capacity, sellable_capacity, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
RETURNING id, organization_id, space_id, slug, display_name, status, physical_capacity, sellable_capacity, version, created_at, updated_at
`

type InsertGAPoolTemplateParams struct {
	ID               uuid.UUID `json:"id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	SpaceID          uuid.UUID `json:"space_id"`
	Slug             string    `json:"slug"`
	DisplayName      string    `json:"display_name"`
	Status           string    `json:"status"`
	PhysicalCapacity int64     `json:"physical_capacity"`
	SellableCapacity int64     `json:"sellable_capacity"`
	Version          int64     `json:"version"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) InsertGAPoolTemplate(ctx context.Context, arg InsertGAPoolTemplateParams) (GaPoolTemplate, error) {
	row := q.db.QueryRow(ctx, insertGAPoolTemplate,
		arg.ID,
		arg.OrganizationID,
		arg.SpaceID,
		arg.Slug,
		arg.DisplayName,
		arg.Status,
		arg.PhysicalCapacity,
		arg.SellableCapacity,
		arg.Version,
		arg.CreatedAt,
	)
	var i GaPoolTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.PhysicalCapacity,
		&i.SellableCapacity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGate = `-- name: InsertGate :one
INSERT INTO gates (id, organization_id, venue_id, space_id, code, display_name, status, version, created_at, updated_at)
VALUES ($1, $2, $3, NULLIF($4, '00000000-0000-0000-0000-000000000000')::uuid, $5, $6, $7, $8, $9, $9)
RETURNING id, organization_id, venue_id, space_id, code, display_name, status, version, created_at, updated_at
`

type InsertGateParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	VenueID        uuid.UUID   `json:"venue_id"`
	Column4        interface{} `json:"column_4"`
	Code           string      `json:"code"`
	DisplayName    string      `json:"display_name"`
	Status         string      `json:"status"`
	Version        int64       `json:"version"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) InsertGate(ctx context.Context, arg InsertGateParams) (Gate, error) {
	row := q.db.QueryRow(ctx, insertGate,
		arg.ID,
		arg.OrganizationID,
		arg.VenueID,
		arg.Column4,
		arg.Code,
		arg.DisplayName,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
	)
	var i Gate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.SpaceID,
		&i.Code,
		&i.DisplayName,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSeatMapVersion = `-- name: InsertSeatMapVersion :one
INSERT INTO seat_map_versions (id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12)
RETURNING id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, published_at, created_at, updated_at
`

type InsertSeatMapVersionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
	Revision       int64     `json:"revision"`
	Checksum       []byte    `json:"checksum"`
	Content        []byte    `json:"content"`
	SeatCount      int32     `json:"seat_count"`
	SellableCount  int32     `json:"sellable_count"`
	Version        int64     `json:"version"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertSeatMapVersion(ctx context.Context, arg InsertSeatMapVersionParams) (SeatMapVersion, error) {
	row := q.db.QueryRow(ctx, insertSeatMapVersion,
		arg.ID,
		arg.OrganizationID,
		arg.SpaceID,
		arg.Name,
		arg.Status,
		arg.Revision,
		arg.Checksum,
		arg.Content,
		arg.SeatCount,
		arg.SellableCount,
		arg.Version,
		arg.CreatedAt,
	)
	var i SeatMapVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Status,
		&i.Revision,
		&i.Checksum,
		&i.Content,
		&i.SeatCount,
		&i.SellableCount,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSpace = `-- name: InsertSpace :one
INSERT INTO spaces (id, organization_id, venue_id, slug, display_name, status, inventory_mode, physical_capacity, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
RETURNING id, organization_id, venue_id, slug, display_name, status, inventory_mode, physical_capacity, version, created_at, updated_at
`

type InsertSpaceParams struct {
	ID               uuid.UUID `json:"id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	VenueID          uuid.UUID `json:"venue_id"`
	Slug             string    `json:"slug"`
	DisplayName      string    `json:"display_name"`
	Status           string    `json:"status"`
	InventoryMode    string    `json:"inventory_mode"`
	PhysicalCapacity int64     `json:"physical_capacity"`
	Version          int64     `json:"version"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) InsertSpace(ctx context.Context, arg InsertSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, insertSpace,
		arg.ID,
		arg.OrganizationID,
		arg.VenueID,
		arg.Slug,
		arg.DisplayName,
		arg.Status,
		arg.InventoryMode,
		arg.PhysicalCapacity,
		arg.Version,
		arg.CreatedAt,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VenueID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.InventoryMode,
		&i.PhysicalCapacity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVenue = `-- name: InsertVenue :one
INSERT INTO venues (id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at
`

type InsertVenueParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
	DisplayName    string    `json:"display_name"`
	Status         string    `json:"status"`
	Timezone       string    `json:"timezone"`
	Version        int64     `json:"version"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertVenue(ctx context.Context, arg InsertVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, insertVenue,
		arg.ID,
		arg.OrganizationID,
		arg.Slug,
		arg.DisplayName,
		arg.Status,
		arg.Timezone,
		arg.Version,
		arg.CreatedAt,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.Timezone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGAPoolTemplates = `-- name: ListGAPoolTemplates :many
SELECT id, organization_id, space_id, slug, display_name, status, physical_capacity, sellable_capacity, version, created_at, updated_at
FROM ga_pool_templates
WHERE organization_id = $1 AND space_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListGAPoolTemplatesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListGAPoolTemplates(ctx context.Context, arg ListGAPoolTemplatesParams) ([]GaPoolTemplate, error) {
	rows, err := q.db.Query(ctx, listGAPoolTemplates, arg.OrganizationID, arg.SpaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GaPoolTemplate{}
	for rows.Next() {
		var i GaPoolTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SpaceID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.PhysicalCapacity,
			&i.SellableCapacity,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGAPoolTemplatesAfter = `-- name: ListGAPoolTemplatesAfter :many
SELECT id, organization_id, space_id, slug, display_name, status, physical_capacity, sellable_capacity, version, created_at, updated_at
FROM ga_pool_templates
WHERE organization_id = $1 AND space_id = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListGAPoolTemplatesAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	SpaceID         uuid.UUID `json:"space_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListGAPoolTemplatesAfter(ctx context.Context, arg ListGAPoolTemplatesAfterParams) ([]GaPoolTemplate, error) {
	rows, err := q.db.Query(ctx, listGAPoolTemplatesAfter,
		arg.OrganizationID,
		arg.SpaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GaPoolTemplate{}
	for rows.Next() {
		var i GaPoolTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SpaceID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.PhysicalCapacity,
			&i.SellableCapacity,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGates = `-- name: ListGates :many
SELECT id, organization_id, venue_id, space_id, code, display_name, status, version, created_at, updated_at
FROM gates
WHERE organization_id = $1 AND venue_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListGatesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	VenueID        uuid.UUID `json:"venue_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListGates(ctx context.Context, arg ListGatesParams) ([]Gate, error) {
	rows, err := q.db.Query(ctx, listGates, arg.OrganizationID, arg.VenueID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gate{}
	for rows.Next() {
		var i Gate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VenueID,
			&i.SpaceID,
			&i.Code,
			&i.DisplayName,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatesAfter = `-- name: ListGatesAfter :many
SELECT id, organization_id, venue_id, space_id, code, display_name, status, version, created_at, updated_at
FROM gates
WHERE organization_id = $1 AND venue_id = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListGatesAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	VenueID         uuid.UUID `json:"venue_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListGatesAfter(ctx context.Context, arg ListGatesAfterParams) ([]Gate, error) {
	rows, err := q.db.Query(ctx, listGatesAfter,
		arg.OrganizationID,
		arg.VenueID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gate{}
	for rows.Next() {
		var i Gate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VenueID,
			&i.SpaceID,
			&i.Code,
			&i.DisplayName,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatMapVersions = `-- name: ListSeatMapVersions :many
SELECT id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, published_at, created_at, updated_at
FROM seat_map_versions
WHERE organization_id = $1 AND space_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListSeatMapVersionsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListSeatMapVersions(ctx context.Context, arg ListSeatMapVersionsParams) ([]SeatMapVersion, error) {
	rows, err := q.db.Query(ctx, listSeatMapVersions, arg.OrganizationID, arg.SpaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeatMapVersion{}
	for rows.Next() {
		var i SeatMapVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SpaceID,
			&i.Name,
			&i.Status,
			&i.Revision,
			&i.Checksum,
			&i.Content,
			&i.SeatCount,
			&i.SellableCount,
			&i.Version,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatMapVersionsAfter = `-- name: ListSeatMapVersionsAfter :many
SELECT id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, published_at, created_at, updated_at
FROM seat_map_versions
WHERE organization_id = $1 AND space_id = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSeatMapVersionsAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	SpaceID         uuid.UUID `json:"space_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListSeatMapVersionsAfter(ctx context.Context, arg ListSeatMapVersionsAfterParams) ([]SeatMapVersion, error) {
	rows, err := q.db.Query(ctx, listSeatMapVersionsAfter,
		arg.OrganizationID,
		arg.SpaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeatMapVersion{}
	for rows.Next() {
		var i SeatMapVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SpaceID,
			&i.Name,
			&i.Status,
			&i.Revision,
			&i.Checksum,
			&i.Content,
			&i.SeatCount,
			&i.SellableCount,
			&i.Version,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, organization_id, venue_id, slug, display_name, status, inventory_mode, physical_capacity, version, created_at, updated_at
FROM spaces
WHERE organization_id = $1 AND venue_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListSpacesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	VenueID        uuid.UUID `json:"venue_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListSpaces(ctx context.Context, arg ListSpacesParams) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpaces, arg.OrganizationID, arg.VenueID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VenueID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.InventoryMode,
			&i.PhysicalCapacity,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesAfter = `-- name: ListSpacesAfter :many
SELECT id, organization_id, venue_id, slug, display_name, status, inventory_mode, physical_capacity, version, created_at, updated_at
FROM spaces
WHERE organization_id = $1 AND venue_id = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSpacesAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	VenueID         uuid.UUID `json:"venue_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListSpacesAfter(ctx context.Context, arg ListSpacesAfterParams) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesAfter,
		arg.OrganizationID,
		arg.VenueID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VenueID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.InventoryMode,
			&i.PhysicalCapacity,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenues = `-- name: ListVenues :many
SELECT id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at
FROM venues
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListVenuesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListVenues(ctx context.Context, arg ListVenuesParams) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.Timezone,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuesAfter = `-- name: ListVenuesAfter :many
SELECT id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at
FROM venues
WHERE organization_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListVenuesAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListVenuesAfter(ctx context.Context, arg ListVenuesAfterParams) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenuesAfter,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.Timezone,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSpace = `-- name: LockSpace :one
SELECT id, status, inventory_mode
FROM spaces
WHERE organization_id = $1 AND id = $2
FOR UPDATE
`

type LockSpaceParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockSpaceRow struct {
	ID            uuid.UUID `json:"id"`
	Status        string    `json:"status"`
	InventoryMode string    `json:"inventory_mode"`
}

func (q *Queries) LockSpace(ctx context.Context, arg LockSpaceParams) (LockSpaceRow, error) {
	row := q.db.QueryRow(ctx, lockSpace, arg.OrganizationID, arg.ID)
	var i LockSpaceRow
	err := row.Scan(&i.ID, &i.Status, &i.InventoryMode)
	return i, err
}

const lockVenue = `-- name: LockVenue :one
SELECT id, status
FROM venues
WHERE organization_id = $1 AND id = $2
FOR UPDATE
`

type LockVenueParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockVenueRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) LockVenue(ctx context.Context, arg LockVenueParams) (LockVenueRow, error) {
	row := q.db.QueryRow(ctx, lockVenue, arg.OrganizationID, arg.ID)
	var i LockVenueRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const nextSeatMapRevision = `-- name: NextSeatMapRevision :one
SELECT COALESCE(MAX(revision), 0)::bigint + 1 AS next_revision
FROM seat_map_versions
WHERE organization_id = $1 AND space_id = $2
`

type NextSeatMapRevisionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
}

func (q *Queries) NextSeatMapRevision(ctx context.Context, arg NextSeatMapRevisionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextSeatMapRevision, arg.OrganizationID, arg.SpaceID)
	var next_revision int32
	err := row.Scan(&next_revision)
	return next_revision, err
}

const publishSeatMapVersion = `-- name: PublishSeatMapVersion :one
UPDATE seat_map_versions
SET status = 'published', revision = $4, published_at = $5, version = version + 1, updated_at = $5
WHERE organization_id = $1 AND space_id = $2 AND id = $3 AND status = 'draft' AND version = $6
RETURNING id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, published_at, created_at, updated_at
`

type PublishSeatMapVersionParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	SpaceID        uuid.UUID          `json:"space_id"`
	ID             uuid.UUID          `json:"id"`
	Revision       int64              `json:"revision"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	Version        int64              `json:"version"`
}

func (q *Queries) PublishSeatMapVersion(ctx context.Context, arg PublishSeatMapVersionParams) (SeatMapVersion, error) {
	row := q.db.QueryRow(ctx, publishSeatMapVersion,
		arg.OrganizationID,
		arg.SpaceID,
		arg.ID,
		arg.Revision,
		arg.PublishedAt,
		arg.Version,
	)
	var i SeatMapVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Status,
		&i.Revision,
		&i.Checksum,
		&i.Content,
		&i.SeatCount,
		&i.SellableCount,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreVenue = `-- name: RestoreVenue :one
UPDATE venues
SET status = 'draft', version = version + 1, updated_at = $4
WHERE organization_id = $1 AND id = $2 AND status = 'archived' AND version = $3
RETURNING id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at
`

type RestoreVenueParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	Version        int64     `json:"version"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) RestoreVenue(ctx context.Context, arg RestoreVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, restoreVenue,
		arg.OrganizationID,
		arg.ID,
		arg.Version,
		arg.UpdatedAt,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.Timezone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retirePublishedSeatMaps = `-- name: RetirePublishedSeatMaps :exec
UPDATE seat_map_versions
SET status = 'retired', updated_at = $3
WHERE organization_id = $1 AND space_id = $2 AND status = 'published'
`

type RetirePublishedSeatMapsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) RetirePublishedSeatMaps(ctx context.Context, arg RetirePublishedSeatMapsParams) error {
	_, err := q.db.Exec(ctx, retirePublishedSeatMaps, arg.OrganizationID, arg.SpaceID, arg.UpdatedAt)
	return err
}

const updateSeatMapDraft = `-- name: UpdateSeatMapDraft :one
UPDATE seat_map_versions
SET name = $4, checksum = $5, content = $6, seat_count = $7, sellable_count = $8, version = version + 1, updated_at = $9
WHERE organization_id = $1 AND space_id = $2 AND id = $3 AND status = 'draft' AND version = $10
RETURNING id, organization_id, space_id, name, status, revision, checksum, content, seat_count, sellable_count, version, published_at, created_at, updated_at
`

type UpdateSeatMapDraftParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Checksum       []byte    `json:"checksum"`
	Content        []byte    `json:"content"`
	SeatCount      int32     `json:"seat_count"`
	SellableCount  int32     `json:"sellable_count"`
	UpdatedAt      time.Time `json:"updated_at"`
	Version        int64     `json:"version"`
}

func (q *Queries) UpdateSeatMapDraft(ctx context.Context, arg UpdateSeatMapDraftParams) (SeatMapVersion, error) {
	row := q.db.QueryRow(ctx, updateSeatMapDraft,
		arg.OrganizationID,
		arg.SpaceID,
		arg.ID,
		arg.Name,
		arg.Checksum,
		arg.Content,
		arg.SeatCount,
		arg.SellableCount,
		arg.UpdatedAt,
		arg.Version,
	)
	var i SeatMapVersion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Status,
		&i.Revision,
		&i.Checksum,
		&i.Content,
		&i.SeatCount,
		&i.SellableCount,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET slug = $3, display_name = $4, timezone = $5, version = version + 1, updated_at = $6
WHERE organization_id = $1 AND id = $2 AND status <> 'archived' AND version = $7
RETURNING id, organization_id, slug, display_name, status, timezone, version, created_at, updated_at
`

type UpdateVenueParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	DisplayName    string    `json:"display_name"`
	Timezone       string    `json:"timezone"`
	UpdatedAt      time.Time `json:"updated_at"`
	Version        int64     `json:"version"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.OrganizationID,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Timezone,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.Timezone,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
