// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEntry struct {
	ID                 uuid.UUID   `json:"id"`
	OrganizationID     uuid.UUID   `json:"organization_id"`
	ActorType          string      `json:"actor_type"`
	ActorID            pgtype.Text `json:"actor_id"`
	EffectiveActorType pgtype.Text `json:"effective_actor_type"`
	EffectiveActorID   pgtype.Text `json:"effective_actor_id"`
	Action             string      `json:"action"`
	SubjectType        string      `json:"subject_type"`
	SubjectID          string      `json:"subject_id"`
	Result             string      `json:"result"`
	Reason             pgtype.Text `json:"reason"`
	RequestID          pgtype.Text `json:"request_id"`
	TraceID            pgtype.Text `json:"trace_id"`
	SourceIp           *netip.Addr `json:"source_ip"`
	DeviceID           pgtype.UUID `json:"device_id"`
	BeforeData         []byte      `json:"before_data"`
	AfterData          []byte      `json:"after_data"`
	OccurredAt         time.Time   `json:"occurred_at"`
}

type IdempotencyRecord struct {
	ID                 uuid.UUID          `json:"id"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	PrincipalType      string             `json:"principal_type"`
	PrincipalID        string             `json:"principal_id"`
	Operation          string             `json:"operation"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	State              string             `json:"state"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	ResponseStatus     pgtype.Int2        `json:"response_status"`
	ResponseBody       []byte             `json:"response_body"`
	ResourceType       pgtype.Text        `json:"resource_type"`
	ResourceID         pgtype.Text        `json:"resource_id"`
	ExpiresAt          time.Time          `json:"expires_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type InboxMessage struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	Source           string             `json:"source"`
	MessageID        string             `json:"message_id"`
	PayloadReference pgtype.Text        `json:"payload_reference"`
	PayloadSha256    []byte             `json:"payload_sha256"`
	State            string             `json:"state"`
	AttemptCount     int32              `json:"attempt_count"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	ReceivedAt       time.Time          `json:"received_at"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type Job struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	JobType          string             `json:"job_type"`
	SchemaVersion    int32              `json:"schema_version"`
	Priority         int16              `json:"priority"`
	DedupeKey        string             `json:"dedupe_key"`
	Payload          []byte             `json:"payload"`
	State            string             `json:"state"`
	RunAt            time.Time          `json:"run_at"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
	LeaseOwner       pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	LastErrorClass   pgtype.Text        `json:"last_error_class"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	CorrelationID    pgtype.Text        `json:"correlation_id"`
	RequestID        pgtype.Text        `json:"request_id"`
	TraceID          pgtype.Text        `json:"trace_id"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

type Organization struct {
	ID              uuid.UUID `json:"id"`
	Slug            string    `json:"slug"`
	DisplayName     string    `json:"display_name"`
	Status          string    `json:"status"`
	DefaultLocale   string    `json:"default_locale"`
	DefaultTimezone string    `json:"default_timezone"`
	DefaultCurrency string    `json:"default_currency"`
	SettingsVersion int64     `json:"settings_version"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type OutboxEvent struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	AggregateType    string             `json:"aggregate_type"`
	AggregateID      uuid.UUID          `json:"aggregate_id"`
	AggregateVersion int64              `json:"aggregate_version"`
	EventType        string             `json:"event_type"`
	SchemaVersion    int32              `json:"schema_version"`
	Payload          []byte             `json:"payload"`
	CorrelationID    pgtype.Text        `json:"correlation_id"`
	CausationID      pgtype.UUID        `json:"causation_id"`
	State            string             `json:"state"`
	AvailableAt      time.Time          `json:"available_at"`
	AttemptCount     int32              `json:"attempt_count"`
	LeaseOwner       pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DeadLetteredAt   pgtype.Timestamptz `json:"dead_lettered_at"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	OccurredAt       time.Time          `json:"occurred_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
