// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJobs = `-- name: ClaimJobs :many
WITH candidates AS (
    SELECT id
    FROM jobs
    WHERE (
        (state IN ('queued', 'retry_wait') AND run_at <= now())
        OR (state = 'leased' AND lease_expires_at <= now())
    )
      AND attempt_count < max_attempts
    ORDER BY priority DESC, run_at, created_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
UPDATE jobs AS job
SET state = 'leased',
    attempt_count = job.attempt_count + 1,
    lease_owner = $1,
    lease_expires_at = now() + make_interval(secs => $2),
    last_error_class = CASE WHEN job.state = 'leased' THEN 'unknown' ELSE job.last_error_class END,
    last_error_message = CASE WHEN job.state = 'leased' THEN 'Previous worker lease expired.' ELSE job.last_error_message END,
    started_at = COALESCE(job.started_at, now()),
    updated_at = now()
FROM candidates
WHERE job.id = candidates.id
RETURNING job.id, job.organization_id, job.job_type, job.schema_version, job.priority, job.dedupe_key, job.payload, job.state, job.run_at, job.attempt_count, job.max_attempts, job.lease_owner, job.lease_expires_at, job.last_error_class, job.last_error_message, job.correlation_id, job.request_id, job.trace_id, job.created_at, job.updated_at, job.started_at, job.finished_at
`

type ClaimJobsParams struct {
	LeaseOwner   pgtype.Text `json:"lease_owner"`
	LeaseSeconds float64     `json:"lease_seconds"`
	BatchSize    int32       `json:"batch_size"`
}

func (q *Queries) ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimJobs, arg.LeaseOwner, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.JobType,
			&i.SchemaVersion,
			&i.Priority,
			&i.DedupeKey,
			&i.Payload,
			&i.State,
			&i.RunAt,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.LastErrorClass,
			&i.LastErrorMessage,
			&i.CorrelationID,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeIdempotencyRecord = `-- name: CompleteIdempotencyRecord :execrows
UPDATE idempotency_records
SET state = $3,
    locked_until = NULL,
    response_status = $4,
    response_body = $5,
    resource_type = $6,
    resource_id = $7,
    updated_at = $8
WHERE id = $1
  AND organization_id = $2
  AND state = 'processing'
`

type CompleteIdempotencyRecordParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	State          string      `json:"state"`
	ResponseStatus pgtype.Int2 `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
	ResourceType   pgtype.Text `json:"resource_type"`
	ResourceID     pgtype.Text `json:"resource_id"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyRecord,
		arg.ID,
		arg.OrganizationID,
		arg.State,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResourceType,
		arg.ResourceID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterExhaustedLeases = `-- name: DeadLetterExhaustedLeases :execrows
UPDATE jobs
SET state = 'dead_letter',
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_class = 'unknown',
    last_error_message = 'Worker lease expired after the final attempt.',
    finished_at = now(),
    updated_at = now()
WHERE state = 'leased'
  AND lease_expires_at <= now()
  AND attempt_count >= max_attempts
`

func (q *Queries) DeadLetterExhaustedLeases(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterExhaustedLeases)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterJob = `-- name: DeadLetterJob :execrows
UPDATE jobs
SET state = 'dead_letter',
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_class = $1,
    last_error_message = $2,
    finished_at = now(),
    updated_at = now()
WHERE id = $3
  AND state = 'leased'
  AND lease_owner = $4
`

type DeadLetterJobParams struct {
	ErrorClass   pgtype.Text `json:"error_class"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
}

func (q *Queries) DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterJob,
		arg.ErrorClass,
		arg.ErrorMessage,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :execrows
INSERT INTO jobs (
    id, organization_id, job_type, schema_version, priority, dedupe_key,
    payload, state, run_at, max_attempts, correlation_id, request_id,
    trace_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, 'queued', $8, $9, $10, $11,
    $12, $13, $13
)
ON CONFLICT (organization_id, job_type, dedupe_key)
DO NOTHING
`

type EnqueueJobParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	JobType        string      `json:"job_type"`
	SchemaVersion  int32       `json:"schema_version"`
	Priority       int16       `json:"priority"`
	DedupeKey      string      `json:"dedupe_key"`
	Payload        []byte      `json:"payload"`
	RunAt          time.Time   `json:"run_at"`
	MaxAttempts    int32       `json:"max_attempts"`
	CorrelationID  pgtype.Text `json:"correlation_id"`
	RequestID      pgtype.Text `json:"request_id"`
	TraceID        pgtype.Text `json:"trace_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJob,
		arg.ID,
		arg.OrganizationID,
		arg.JobType,
		arg.SchemaVersion,
		arg.Priority,
		arg.DedupeKey,
		arg.Payload,
		arg.RunAt,
		arg.MaxAttempts,
		arg.CorrelationID,
		arg.RequestID,
		arg.TraceID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendJobLease = `-- name: ExtendJobLease :execrows
UPDATE jobs
SET lease_expires_at = now() + make_interval(secs => $1),
    updated_at = now()
WHERE id = $2
  AND state = 'leased'
  AND lease_owner = $3
  AND lease_expires_at > now()
`

type ExtendJobLeaseParams struct {
	LeaseSeconds float64     `json:"lease_seconds"`
	ID           uuid.UUID   `json:"id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
}

func (q *Queries) ExtendJobLease(ctx context.Context, arg ExtendJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendJobLease, arg.LeaseSeconds, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyRecordForUpdate = `-- name: GetIdempotencyRecordForUpdate :one
SELECT id, organization_id, principal_type, principal_id, operation,
       idempotency_key, request_fingerprint, state, locked_until,
       response_status, response_body, resource_type, resource_id,
       expires_at, created_at, updated_at
FROM idempotency_records
WHERE organization_id = $1
  AND principal_type = $2
  AND principal_id = $3
  AND operation = $4
  AND idempotency_key = $5
FOR UPDATE
`

type GetIdempotencyRecordForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	PrincipalType  string    `json:"principal_type"`
	PrincipalID    string    `json:"principal_id"`
	Operation      string    `json:"operation"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyRecordForUpdate(ctx context.Context, arg GetIdempotencyRecordForUpdateParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecordForUpdate,
		arg.OrganizationID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.State,
		&i.LockedUntil,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobQueueStats = `-- name: GetJobQueueStats :many
SELECT job_type,
       count(*)::bigint AS depth,
       COALESCE(EXTRACT(EPOCH FROM now() - min(run_at)), 0)::double precision AS oldest_age_seconds
FROM jobs
WHERE state IN ('queued', 'retry_wait')
  AND run_at <= now()
  AND job_type = ANY($1::text[])
GROUP BY job_type
ORDER BY job_type
`

type GetJobQueueStatsRow struct {
	JobType          string  `json:"job_type"`
	Depth            int64   `json:"depth"`
	OldestAgeSeconds float64 `json:"oldest_age_seconds"`
}

func (q *Queries) GetJobQueueStats(ctx context.Context, jobTypes []string) ([]GetJobQueueStatsRow, error) {
	rows, err := q.db.Query(ctx, getJobQueueStats, jobTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobQueueStatsRow{}
	for rows.Next() {
		var i GetJobQueueStatsRow
		if err := rows.Scan(&i.JobType, &i.Depth, &i.OldestAgeSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_entries (
    id, organization_id, actor_type, actor_id, effective_actor_type,
    effective_actor_id, action, subject_type, subject_id, result, reason,
    request_id, trace_id, source_ip, device_id, before_data, after_data,
    occurred_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17,
    $18
)
`

type InsertAuditEntryParams struct {
	ID                 uuid.UUID   `json:"id"`
	OrganizationID     uuid.UUID   `json:"organization_id"`
	ActorType          string      `json:"actor_type"`
	ActorID            pgtype.Text `json:"actor_id"`
	EffectiveActorType pgtype.Text `json:"effective_actor_type"`
	EffectiveActorID   pgtype.Text `json:"effective_actor_id"`
	Action             string      `json:"action"`
	SubjectType        string      `json:"subject_type"`
	SubjectID          string      `json:"subject_id"`
	Result             string      `json:"result"`
	Reason             pgtype.Text `json:"reason"`
	RequestID          pgtype.Text `json:"request_id"`
	TraceID            pgtype.Text `json:"trace_id"`
	SourceIp           *netip.Addr `json:"source_ip"`
	DeviceID           pgtype.UUID `json:"device_id"`
	BeforeData         []byte      `json:"before_data"`
	AfterData          []byte      `json:"after_data"`
	OccurredAt         time.Time   `json:"occurred_at"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.ID,
		arg.OrganizationID,
		arg.ActorType,
		arg.ActorID,
		arg.EffectiveActorType,
		arg.EffectiveActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Result,
		arg.Reason,
		arg.RequestID,
		arg.TraceID,
		arg.SourceIp,
		arg.DeviceID,
		arg.BeforeData,
		arg.AfterData,
		arg.OccurredAt,
	)
	return err
}

const insertIdempotencyRecord = `-- name: InsertIdempotencyRecord :execrows
INSERT INTO idempotency_records (
    id, organization_id, principal_type, principal_id, operation,
    idempotency_key, request_fingerprint, state, locked_until, expires_at,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, 'processing', $8, $9,
    $10, $10
)
ON CONFLICT (organization_id, principal_type, principal_id, operation, idempotency_key)
DO NOTHING
`

type InsertIdempotencyRecordParams struct {
	ID                 uuid.UUID          `json:"id"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	PrincipalType      string             `json:"principal_type"`
	PrincipalID        string             `json:"principal_id"`
	Operation          string             `json:"operation"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt          time.Time          `json:"expires_at"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIdempotencyRecord,
		arg.ID,
		arg.OrganizationID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.LockedUntil,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    id, organization_id, aggregate_type, aggregate_id, aggregate_version,
    event_type, schema_version, payload, correlation_id, causation_id,
    state, available_at, occurred_at, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    'pending', $11, $12, $12
)
`

type InsertOutboxEventParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	AggregateType    string      `json:"aggregate_type"`
	AggregateID      uuid.UUID   `json:"aggregate_id"`
	AggregateVersion int64       `json:"aggregate_version"`
	EventType        string      `json:"event_type"`
	SchemaVersion    int32       `json:"schema_version"`
	Payload          []byte      `json:"payload"`
	CorrelationID    pgtype.Text `json:"correlation_id"`
	CausationID      pgtype.UUID `json:"causation_id"`
	AvailableAt      time.Time   `json:"available_at"`
	OccurredAt       time.Time   `json:"occurred_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.OrganizationID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.SchemaVersion,
		arg.Payload,
		arg.CorrelationID,
		arg.CausationID,
		arg.AvailableAt,
		arg.OccurredAt,
	)
	return err
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET state = 'retry_wait',
    run_at = now() + make_interval(secs => $1::double precision / 1000.0),
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_class = $2,
    last_error_message = $3,
    updated_at = now()
WHERE id = $4
  AND state = 'leased'
  AND lease_owner = $5
  AND attempt_count < max_attempts
`

type RetryJobParams struct {
	DelayMilliseconds float64     `json:"delay_milliseconds"`
	ErrorClass        pgtype.Text `json:"error_class"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	ID                uuid.UUID   `json:"id"`
	LeaseOwner        pgtype.Text `json:"lease_owner"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.DelayMilliseconds,
		arg.ErrorClass,
		arg.ErrorMessage,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const succeedJob = `-- name: SucceedJob :execrows
UPDATE jobs
SET state = 'succeeded',
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_class = NULL,
    last_error_message = NULL,
    finished_at = now(),
    updated_at = now()
WHERE id = $1
  AND state = 'leased'
  AND lease_owner = $2
`

type SucceedJobParams struct {
	ID         uuid.UUID   `json:"id"`
	LeaseOwner pgtype.Text `json:"lease_owner"`
}

func (q *Queries) SucceedJob(ctx context.Context, arg SucceedJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, succeedJob, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
