// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueJobSchedule = `-- name: ClaimDueJobSchedule :one
WITH due AS (
    SELECT schedule_key, next_run_at AS due_at
    FROM job_schedules
    WHERE enabled = true AND next_run_at <= $1
    ORDER BY next_run_at ASC, schedule_key ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE job_schedules AS schedule
SET next_run_at = GREATEST(
        schedule.next_run_at + make_interval(secs => schedule.interval_seconds),
        $1 + make_interval(secs => schedule.interval_seconds)
    ),
    updated_at = $1
FROM due
WHERE schedule.schedule_key = due.schedule_key
RETURNING schedule.schedule_key, schedule.organization_id, schedule.job_type, schedule.schema_version, schedule.priority, schedule.payload, schedule.interval_seconds, schedule.next_run_at, schedule.max_attempts, schedule.enabled, schedule.created_at, schedule.updated_at, due.due_at
`

type ClaimDueJobScheduleRow struct {
	ScheduleKey     string      `json:"schedule_key"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	JobType         string      `json:"job_type"`
	SchemaVersion   int32       `json:"schema_version"`
	Priority        int16       `json:"priority"`
	Payload         []byte      `json:"payload"`
	IntervalSeconds int32       `json:"interval_seconds"`
	NextRunAt       time.Time   `json:"next_run_at"`
	MaxAttempts     int32       `json:"max_attempts"`
	Enabled         bool        `json:"enabled"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	DueAt           time.Time   `json:"due_at"`
}

func (q *Queries) ClaimDueJobSchedule(ctx context.Context, now time.Time) (ClaimDueJobScheduleRow, error) {
	row := q.db.QueryRow(ctx, claimDueJobSchedule, now)
	var i ClaimDueJobScheduleRow
	err := row.Scan(
		&i.ScheduleKey,
		&i.OrganizationID,
		&i.JobType,
		&i.SchemaVersion,
		&i.Priority,
		&i.Payload,
		&i.IntervalSeconds,
		&i.NextRunAt,
		&i.MaxAttempts,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueAt,
	)
	return i, err
}

const claimInboxMessages = `-- name: ClaimInboxMessages :many
WITH candidates AS (
    SELECT source.id
    FROM inbox_messages AS source
    WHERE (
        (source.state IN ('received', 'failed') AND source.available_at <= $2)
        OR (source.state = 'processing' AND source.lease_expires_at <= $2)
    )
      AND source.attempt_count < $4
    ORDER BY source.available_at ASC, source.received_at ASC, source.id ASC
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
UPDATE inbox_messages AS message
SET state = 'processing',
    attempt_count = message.attempt_count + 1,
    lease_owner = $1,
    lease_expires_at = $2 + make_interval(secs => $3),
    processed_at = NULL,
    updated_at = $2,
    last_error_code = CASE WHEN message.state = 'processing' THEN 'lease_expired' ELSE message.last_error_code END,
    last_error_message = CASE WHEN message.state = 'processing' THEN 'Previous inbox lease expired.' ELSE message.last_error_message END
FROM candidates
WHERE message.id = candidates.id
RETURNING message.id, message.organization_id, message.source, message.message_id, message.payload_reference, message.payload_sha256, message.state, message.attempt_count, message.last_error_code, message.last_error_message, message.received_at, message.processed_at, message.updated_at, message.available_at, message.lease_owner, message.lease_expires_at
`

type ClaimInboxMessagesParams struct {
	LeaseOwner   pgtype.Text `json:"lease_owner"`
	Now          time.Time   `json:"now"`
	LeaseSeconds float64     `json:"lease_seconds"`
	MaxAttempts  int32       `json:"max_attempts"`
	BatchSize    int32       `json:"batch_size"`
}

func (q *Queries) ClaimInboxMessages(ctx context.Context, arg ClaimInboxMessagesParams) ([]InboxMessage, error) {
	rows, err := q.db.Query(ctx, claimInboxMessages,
		arg.LeaseOwner,
		arg.Now,
		arg.LeaseSeconds,
		arg.MaxAttempts,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxMessage{}
	for rows.Next() {
		var i InboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Source,
			&i.MessageID,
			&i.PayloadReference,
			&i.PayloadSha256,
			&i.State,
			&i.AttemptCount,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
			&i.AvailableAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimJobs = `-- name: ClaimJobs :many
WITH candidates AS (
    SELECT id
    FROM jobs
    WHERE (
        (state IN ('queued', 'retry_wait') AND run_at <= now())
        OR (state = 'leased' AND lease_expires_at <= now())
    )
      AND attempt_count < max_attempts
    ORDER BY priority DESC, run_at, created_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
UPDATE jobs AS job
SET state = 'leased',
    attempt_count = job.attempt_count + 1,
    lease_owner = $1,
    lease_expires_at = now() + make_interval(secs => $2),
    last_error_class = CASE WHEN job.state = 'leased' THEN 'unknown' ELSE job.last_error_class END,
    last_error_message = CASE WHEN job.state = 'leased' THEN 'Previous worker lease expired.' ELSE job.last_error_message END,
    started_at = COALESCE(job.started_at, now()),
    updated_at = now()
FROM candidates
WHERE job.id = candidates.id
RETURNING job.id, job.organization_id, job.job_type, job.schema_version, job.priority, job.dedupe_key, job.payload, job.state, job.run_at, job.attempt_count, job.max_attempts, job.lease_owner, job.lease_expires_at, job.last_error_class, job.last_error_message, job.correlation_id, job.request_id, job.trace_id, job.created_at, job.updated_at, job.started_at, job.finished_at
`

type ClaimJobsParams struct {
	LeaseOwner   pgtype.Text `json:"lease_owner"`
	LeaseSeconds float64     `json:"lease_seconds"`
	BatchSize    int32       `json:"batch_size"`
}

func (q *Queries) ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimJobs, arg.LeaseOwner, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.JobType,
			&i.SchemaVersion,
			&i.Priority,
			&i.DedupeKey,
			&i.Payload,
			&i.State,
			&i.RunAt,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.LastErrorClass,
			&i.LastErrorMessage,
			&i.CorrelationID,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidates AS (
    SELECT source.id
    FROM outbox_events AS source
    WHERE (
        (source.state = 'pending' AND source.available_at <= $2)
        OR (source.state = 'leased' AND source.lease_expires_at <= $2)
    )
      AND source.attempt_count < $4
    ORDER BY source.available_at ASC, source.occurred_at ASC, source.id ASC
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events AS event
SET state = 'leased',
    attempt_count = event.attempt_count + 1,
    lease_owner = $1,
    lease_expires_at = $2 + make_interval(secs => $3),
    published_at = NULL,
    dead_lettered_at = NULL,
    last_error_code = CASE WHEN event.state = 'leased' THEN 'lease_expired' ELSE event.last_error_code END,
    last_error_message = CASE WHEN event.state = 'leased' THEN 'Previous relay lease expired.' ELSE event.last_error_message END
FROM candidates
WHERE event.id = candidates.id
RETURNING event.id, event.organization_id, event.aggregate_type, event.aggregate_id, event.aggregate_version, event.event_type, event.schema_version, event.payload, event.correlation_id, event.causation_id, event.state, event.available_at, event.attempt_count, event.lease_owner, event.lease_expires_at, event.published_at, event.dead_lettered_at, event.last_error_code, event.last_error_message, event.occurred_at, event.created_at
`

type ClaimOutboxEventsParams struct {
	LeaseOwner   pgtype.Text `json:"lease_owner"`
	Now          interface{} `json:"now"`
	LeaseSeconds float64     `json:"lease_seconds"`
	MaxAttempts  int32       `json:"max_attempts"`
	BatchSize    int32       `json:"batch_size"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents,
		arg.LeaseOwner,
		arg.Now,
		arg.LeaseSeconds,
		arg.MaxAttempts,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.AggregateType,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.CorrelationID,
			&i.CausationID,
			&i.State,
			&i.AvailableAt,
			&i.AttemptCount,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.PublishedAt,
			&i.DeadLetteredAt,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeIdempotencyRecord = `-- name: CompleteIdempotencyRecord :execrows
UPDATE idempotency_records
SET state = $3,
    locked_until = NULL,
    response_status = $4,
    response_body = $5,
    resource_type = $6,
    resource_id = $7,
    updated_at = $8
WHERE id = $1
  AND organization_id = $2
  AND state = 'processing'
`

type CompleteIdempotencyRecordParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	State          string      `json:"state"`
	ResponseStatus pgtype.Int2 `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
	ResourceType   pgtype.Text `json:"resource_type"`
	ResourceID     pgtype.Text `json:"resource_id"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyRecord,
		arg.ID,
		arg.OrganizationID,
		arg.State,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResourceType,
		arg.ResourceID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterExhaustedInboxLeases = `-- name: DeadLetterExhaustedInboxLeases :execrows
UPDATE inbox_messages
SET state = 'dead_letter',
    lease_owner = NULL,
    lease_expires_at = NULL,
    processed_at = NULL,
    last_error_code = 'lease_expired',
    last_error_message = 'Inbox lease expired after the final attempt.',
    updated_at = $1
WHERE state = 'processing'
  AND lease_expires_at <= $1
  AND attempt_count >= $2
`

type DeadLetterExhaustedInboxLeasesParams struct {
	Now         time.Time `json:"now"`
	MaxAttempts int32     `json:"max_attempts"`
}

func (q *Queries) DeadLetterExhaustedInboxLeases(ctx context.Context, arg DeadLetterExhaustedInboxLeasesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterExhaustedInboxLeases, arg.Now, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterExhaustedLeases = `-- name: DeadLetterExhaustedLeases :execrows
UPDATE jobs
SET state = 'dead_letter',
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_class = 'unknown',
    last_error_message = 'Worker lease expired after the final attempt.',
    finished_at = now(),
    updated_at = now()
WHERE state = 'leased'
  AND lease_expires_at <= now()
  AND attempt_count >= max_attempts
`

func (q *Queries) DeadLetterExhaustedLeases(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterExhaustedLeases)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterExhaustedOutboxLeases = `-- name: DeadLetterExhaustedOutboxLeases :execrows
UPDATE outbox_events
SET state = 'dead_letter',
    lease_owner = NULL,
    lease_expires_at = NULL,
    dead_lettered_at = $1,
    last_error_code = 'lease_expired',
    last_error_message = 'Outbox relay lease expired after the final attempt.'
WHERE state = 'leased'
  AND lease_expires_at <= $1
  AND attempt_count >= $2
`

type DeadLetterExhaustedOutboxLeasesParams struct {
	Now         pgtype.Timestamptz `json:"now"`
	MaxAttempts int32              `json:"max_attempts"`
}

func (q *Queries) DeadLetterExhaustedOutboxLeases(ctx context.Context, arg DeadLetterExhaustedOutboxLeasesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterExhaustedOutboxLeases, arg.Now, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterInboxMessage = `-- name: DeadLetterInboxMessage :execrows
UPDATE inbox_messages
SET state = 'dead_letter',
    lease_owner = NULL,
    lease_expires_at = NULL,
    processed_at = NULL,
    last_error_code = $1,
    last_error_message = $2,
    updated_at = $3
WHERE id = $4
  AND state = 'processing'
  AND lease_owner = $5
`

type DeadLetterInboxMessageParams struct {
	ErrorCode      pgtype.Text `json:"error_code"`
	ErrorMessage   pgtype.Text `json:"error_message"`
	DeadLetteredAt time.Time   `json:"dead_lettered_at"`
	ID             uuid.UUID   `json:"id"`
	LeaseOwner     pgtype.Text `json:"lease_owner"`
}

func (q *Queries) DeadLetterInboxMessage(ctx context.Context, arg DeadLetterInboxMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterInboxMessage,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.DeadLetteredAt,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterJob = `-- name: DeadLetterJob :execrows
UPDATE jobs
SET state = 'dead_letter',
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_class = $1,
    last_error_message = $2,
    finished_at = now(),
    updated_at = now()
WHERE id = $3
  AND state = 'leased'
  AND lease_owner = $4
`

type DeadLetterJobParams struct {
	ErrorClass   pgtype.Text `json:"error_class"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
}

func (q *Queries) DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterJob,
		arg.ErrorClass,
		arg.ErrorMessage,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterOutboxEvent = `-- name: DeadLetterOutboxEvent :execrows
UPDATE outbox_events
SET state = 'dead_letter',
    lease_owner = NULL,
    lease_expires_at = NULL,
    dead_lettered_at = $1,
    last_error_code = $2,
    last_error_message = $3
WHERE id = $4
  AND state = 'leased'
  AND lease_owner = $5
`

type DeadLetterOutboxEventParams struct {
	DeadLetteredAt pgtype.Timestamptz `json:"dead_lettered_at"`
	ErrorCode      pgtype.Text        `json:"error_code"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	ID             uuid.UUID          `json:"id"`
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) DeadLetterOutboxEvent(ctx context.Context, arg DeadLetterOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterOutboxEvent,
		arg.DeadLetteredAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyRecords = `-- name: DeleteExpiredIdempotencyRecords :execrows
WITH expired AS (
    SELECT source.id
    FROM idempotency_records AS source
    WHERE source.expires_at <= $1
      AND (
          source.state <> 'processing'
          OR source.locked_until IS NULL
          OR source.locked_until <= $1
      )
    ORDER BY source.expires_at ASC, source.id ASC
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM idempotency_records AS records
USING expired
WHERE records.id = expired.id
`

type DeleteExpiredIdempotencyRecordsParams struct {
	Now        time.Time `json:"now"`
	BatchLimit int32     `json:"batch_limit"`
}

func (q *Queries) DeleteExpiredIdempotencyRecords(ctx context.Context, arg DeleteExpiredIdempotencyRecordsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyRecords, arg.Now, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRealtimeEvents = `-- name: DeleteExpiredRealtimeEvents :execrows
WITH expired AS (
    SELECT organization_id, id
    FROM realtime_events
    WHERE retention_expires_at <= now()
    ORDER BY retention_expires_at ASC, id ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
DELETE FROM realtime_events AS events
USING expired
WHERE events.organization_id = expired.organization_id
  AND events.id = expired.id
`

func (q *Queries) DeleteExpiredRealtimeEvents(ctx context.Context, batchLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRealtimeEvents, batchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :execrows
INSERT INTO jobs (
    id, organization_id, job_type, schema_version, priority, dedupe_key,
    payload, state, run_at, max_attempts, correlation_id, request_id,
    trace_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, 'queued', $8, $9, $10, $11,
    $12, $13, $13
)
ON CONFLICT (organization_id, job_type, dedupe_key)
DO NOTHING
`

type EnqueueJobParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	JobType        string      `json:"job_type"`
	SchemaVersion  int32       `json:"schema_version"`
	Priority       int16       `json:"priority"`
	DedupeKey      string      `json:"dedupe_key"`
	Payload        []byte      `json:"payload"`
	RunAt          time.Time   `json:"run_at"`
	MaxAttempts    int32       `json:"max_attempts"`
	CorrelationID  pgtype.Text `json:"correlation_id"`
	RequestID      pgtype.Text `json:"request_id"`
	TraceID        pgtype.Text `json:"trace_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJob,
		arg.ID,
		arg.OrganizationID,
		arg.JobType,
		arg.SchemaVersion,
		arg.Priority,
		arg.DedupeKey,
		arg.Payload,
		arg.RunAt,
		arg.MaxAttempts,
		arg.CorrelationID,
		arg.RequestID,
		arg.TraceID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureJobSchedule = `-- name: EnsureJobSchedule :exec
INSERT INTO job_schedules (
    schedule_key, organization_id, job_type, schema_version, priority, payload,
    interval_seconds, next_run_at, max_attempts, enabled, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, true, $10, $10)
ON CONFLICT (schedule_key)
DO UPDATE SET
    organization_id = EXCLUDED.organization_id,
    job_type = EXCLUDED.job_type,
    schema_version = EXCLUDED.schema_version,
    priority = EXCLUDED.priority,
    payload = EXCLUDED.payload,
    interval_seconds = EXCLUDED.interval_seconds,
    max_attempts = EXCLUDED.max_attempts,
    enabled = true,
    updated_at = EXCLUDED.updated_at
`

type EnsureJobScheduleParams struct {
	ScheduleKey     string      `json:"schedule_key"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	JobType         string      `json:"job_type"`
	SchemaVersion   int32       `json:"schema_version"`
	Priority        int16       `json:"priority"`
	Payload         []byte      `json:"payload"`
	IntervalSeconds int32       `json:"interval_seconds"`
	NextRunAt       time.Time   `json:"next_run_at"`
	MaxAttempts     int32       `json:"max_attempts"`
	CreatedAt       time.Time   `json:"created_at"`
}

func (q *Queries) EnsureJobSchedule(ctx context.Context, arg EnsureJobScheduleParams) error {
	_, err := q.db.Exec(ctx, ensureJobSchedule,
		arg.ScheduleKey,
		arg.OrganizationID,
		arg.JobType,
		arg.SchemaVersion,
		arg.Priority,
		arg.Payload,
		arg.IntervalSeconds,
		arg.NextRunAt,
		arg.MaxAttempts,
		arg.CreatedAt,
	)
	return err
}

const extendJobLease = `-- name: ExtendJobLease :execrows
UPDATE jobs
SET lease_expires_at = now() + make_interval(secs => $1),
    updated_at = now()
WHERE id = $2
  AND state = 'leased'
  AND lease_owner = $3
  AND lease_expires_at > now()
`

type ExtendJobLeaseParams struct {
	LeaseSeconds float64     `json:"lease_seconds"`
	ID           uuid.UUID   `json:"id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
}

func (q *Queries) ExtendJobLease(ctx context.Context, arg ExtendJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendJobLease, arg.LeaseSeconds, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyRecordForUpdate = `-- name: GetIdempotencyRecordForUpdate :one
SELECT id, organization_id, principal_type, principal_id, operation,
       idempotency_key, request_fingerprint, state, locked_until,
       response_status, response_body, resource_type, resource_id,
       expires_at, created_at, updated_at
FROM idempotency_records
WHERE organization_id = $1
  AND principal_type = $2
  AND principal_id = $3
  AND operation = $4
  AND idempotency_key = $5
FOR UPDATE
`

type GetIdempotencyRecordForUpdateParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PrincipalType  string      `json:"principal_type"`
	PrincipalID    string      `json:"principal_id"`
	Operation      string      `json:"operation"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyRecordForUpdate(ctx context.Context, arg GetIdempotencyRecordForUpdateParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecordForUpdate,
		arg.OrganizationID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.State,
		&i.LockedUntil,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboxMessageByKey = `-- name: GetInboxMessageByKey :one
SELECT id, organization_id, source, message_id, payload_reference,
       payload_sha256, state, attempt_count, available_at, lease_owner,
       lease_expires_at, last_error_code, last_error_message, received_at,
       processed_at, updated_at
FROM inbox_messages
WHERE source = $1
  AND message_id = $2
`

type GetInboxMessageByKeyParams struct {
	Source    string `json:"source"`
	MessageID string `json:"message_id"`
}

type GetInboxMessageByKeyRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	Source           string             `json:"source"`
	MessageID        string             `json:"message_id"`
	PayloadReference pgtype.Text        `json:"payload_reference"`
	PayloadSha256    []byte             `json:"payload_sha256"`
	State            string             `json:"state"`
	AttemptCount     int32              `json:"attempt_count"`
	AvailableAt      time.Time          `json:"available_at"`
	LeaseOwner       pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	ReceivedAt       time.Time          `json:"received_at"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

func (q *Queries) GetInboxMessageByKey(ctx context.Context, arg GetInboxMessageByKeyParams) (GetInboxMessageByKeyRow, error) {
	row := q.db.QueryRow(ctx, getInboxMessageByKey, arg.Source, arg.MessageID)
	var i GetInboxMessageByKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Source,
		&i.MessageID,
		&i.PayloadReference,
		&i.PayloadSha256,
		&i.State,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobQueueStats = `-- name: GetJobQueueStats :many
SELECT job_type,
       count(*)::bigint AS depth,
       COALESCE(EXTRACT(EPOCH FROM now() - min(run_at)), 0)::double precision AS oldest_age_seconds
FROM jobs
WHERE state IN ('queued', 'retry_wait')
  AND run_at <= now()
  AND job_type = ANY($1::text[])
GROUP BY job_type
ORDER BY job_type
`

type GetJobQueueStatsRow struct {
	JobType          string  `json:"job_type"`
	Depth            int64   `json:"depth"`
	OldestAgeSeconds float64 `json:"oldest_age_seconds"`
}

func (q *Queries) GetJobQueueStats(ctx context.Context, jobTypes []string) ([]GetJobQueueStatsRow, error) {
	rows, err := q.db.Query(ctx, getJobQueueStats, jobTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobQueueStatsRow{}
	for rows.Next() {
		var i GetJobQueueStatsRow
		if err := rows.Scan(&i.JobType, &i.Depth, &i.OldestAgeSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_entries (
    id, organization_id, actor_type, actor_id, effective_actor_type,
    effective_actor_id, action, subject_type, subject_id, result, reason,
    request_id, trace_id, source_ip, device_id, before_data, after_data,
    occurred_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17,
    $18
)
`

type InsertAuditEntryParams struct {
	ID                 uuid.UUID   `json:"id"`
	OrganizationID     uuid.UUID   `json:"organization_id"`
	ActorType          string      `json:"actor_type"`
	ActorID            pgtype.Text `json:"actor_id"`
	EffectiveActorType pgtype.Text `json:"effective_actor_type"`
	EffectiveActorID   pgtype.Text `json:"effective_actor_id"`
	Action             string      `json:"action"`
	SubjectType        string      `json:"subject_type"`
	SubjectID          string      `json:"subject_id"`
	Result             string      `json:"result"`
	Reason             pgtype.Text `json:"reason"`
	RequestID          pgtype.Text `json:"request_id"`
	TraceID            pgtype.Text `json:"trace_id"`
	SourceIp           *netip.Addr `json:"source_ip"`
	DeviceID           pgtype.UUID `json:"device_id"`
	BeforeData         []byte      `json:"before_data"`
	AfterData          []byte      `json:"after_data"`
	OccurredAt         time.Time   `json:"occurred_at"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.ID,
		arg.OrganizationID,
		arg.ActorType,
		arg.ActorID,
		arg.EffectiveActorType,
		arg.EffectiveActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Result,
		arg.Reason,
		arg.RequestID,
		arg.TraceID,
		arg.SourceIp,
		arg.DeviceID,
		arg.BeforeData,
		arg.AfterData,
		arg.OccurredAt,
	)
	return err
}

const insertIdempotencyRecord = `-- name: InsertIdempotencyRecord :execrows
INSERT INTO idempotency_records (
    id, organization_id, principal_type, principal_id, operation,
    idempotency_key, request_fingerprint, state, locked_until, expires_at,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, 'processing', $8, $9,
    $10, $10
)
ON CONFLICT (organization_id, principal_type, principal_id, operation, idempotency_key)
DO NOTHING
`

type InsertIdempotencyRecordParams struct {
	ID                 uuid.UUID          `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	PrincipalType      string             `json:"principal_type"`
	PrincipalID        string             `json:"principal_id"`
	Operation          string             `json:"operation"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt          time.Time          `json:"expires_at"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIdempotencyRecord,
		arg.ID,
		arg.OrganizationID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.LockedUntil,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertInboxMessage = `-- name: InsertInboxMessage :execrows
INSERT INTO inbox_messages (
    id, organization_id, source, message_id, payload_reference, payload_sha256,
    state, available_at, received_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    'received', $7, $8, $9
)
ON CONFLICT (source, message_id)
DO NOTHING
`

type InsertInboxMessageParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   pgtype.UUID `json:"organization_id"`
	Source           string      `json:"source"`
	MessageID        string      `json:"message_id"`
	PayloadReference pgtype.Text `json:"payload_reference"`
	PayloadSha256    []byte      `json:"payload_sha256"`
	AvailableAt      time.Time   `json:"available_at"`
	ReceivedAt       time.Time   `json:"received_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInboxMessage,
		arg.ID,
		arg.OrganizationID,
		arg.Source,
		arg.MessageID,
		arg.PayloadReference,
		arg.PayloadSha256,
		arg.AvailableAt,
		arg.ReceivedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    id, organization_id, aggregate_type, aggregate_id, aggregate_version,
    event_type, schema_version, payload, correlation_id, causation_id,
    state, available_at, occurred_at, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    'pending', $11, $12, $12
)
`

type InsertOutboxEventParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	AggregateType    string      `json:"aggregate_type"`
	AggregateID      uuid.UUID   `json:"aggregate_id"`
	AggregateVersion int64       `json:"aggregate_version"`
	EventType        string      `json:"event_type"`
	SchemaVersion    int32       `json:"schema_version"`
	Payload          []byte      `json:"payload"`
	CorrelationID    pgtype.Text `json:"correlation_id"`
	CausationID      pgtype.UUID `json:"causation_id"`
	AvailableAt      time.Time   `json:"available_at"`
	OccurredAt       time.Time   `json:"occurred_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.OrganizationID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.SchemaVersion,
		arg.Payload,
		arg.CorrelationID,
		arg.CausationID,
		arg.AvailableAt,
		arg.OccurredAt,
	)
	return err
}

const insertRealtimeEvent = `-- name: InsertRealtimeEvent :exec
INSERT INTO realtime_events (
    id, organization_id, session_id, topic, sequence, event_type,
    schema_version, payload, occurred_at, retention_expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertRealtimeEventParams struct {
	ID                 uuid.UUID `json:"id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	SessionID          uuid.UUID `json:"session_id"`
	Topic              string    `json:"topic"`
	Sequence           int64     `json:"sequence"`
	EventType          string    `json:"event_type"`
	SchemaVersion      int32     `json:"schema_version"`
	Payload            []byte    `json:"payload"`
	OccurredAt         time.Time `json:"occurred_at"`
	RetentionExpiresAt time.Time `json:"retention_expires_at"`
}

func (q *Queries) InsertRealtimeEvent(ctx context.Context, arg InsertRealtimeEventParams) error {
	_, err := q.db.Exec(ctx, insertRealtimeEvent,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.Topic,
		arg.Sequence,
		arg.EventType,
		arg.SchemaVersion,
		arg.Payload,
		arg.OccurredAt,
		arg.RetentionExpiresAt,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, organization_id, actor_type, actor_id, effective_actor_type,
       effective_actor_id, action, subject_type, subject_id, result, reason,
       request_id, trace_id, source_ip, device_id, before_data, after_data,
       occurred_at
FROM audit_entries
WHERE organization_id = $1
  AND ($2::text IS NULL OR actor_type = $2::text)
  AND ($3::text IS NULL OR actor_id = $3::text)
  AND ($4::text IS NULL OR action = $4::text)
  AND ($5::text IS NULL OR subject_type = $5::text)
  AND ($6::text IS NULL OR subject_id = $6::text)
  AND ($7::text IS NULL OR result = $7::text)
  AND ($8::text IS NULL OR request_id = $8::text)
  AND ($9::timestamptz IS NULL OR occurred_at >= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR occurred_at < $10::timestamptz)
  AND (
      $11::timestamptz IS NULL
      OR (occurred_at, id) < ($11::timestamptz, $12::uuid)
  )
ORDER BY occurred_at DESC, id DESC
LIMIT $13
`

type ListAuditEntriesParams struct {
	OrganizationID   uuid.UUID          `json:"organization_id"`
	ActorType        pgtype.Text        `json:"actor_type"`
	ActorID          pgtype.Text        `json:"actor_id"`
	Action           pgtype.Text        `json:"action"`
	SubjectType      pgtype.Text        `json:"subject_type"`
	SubjectID        pgtype.Text        `json:"subject_id"`
	Result           pgtype.Text        `json:"result"`
	RequestID        pgtype.Text        `json:"request_id"`
	OccurredFrom     pgtype.Timestamptz `json:"occurred_from"`
	OccurredUntil    pgtype.Timestamptz `json:"occurred_until"`
	CursorOccurredAt pgtype.Timestamptz `json:"cursor_occurred_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	PageLimit        int32              `json:"page_limit"`
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntries,
		arg.OrganizationID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Result,
		arg.RequestID,
		arg.OccurredFrom,
		arg.OccurredUntil,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorType,
			&i.ActorID,
			&i.EffectiveActorType,
			&i.EffectiveActorID,
			&i.Action,
			&i.SubjectType,
			&i.SubjectID,
			&i.Result,
			&i.Reason,
			&i.RequestID,
			&i.TraceID,
			&i.SourceIp,
			&i.DeviceID,
			&i.BeforeData,
			&i.AfterData,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxMessageProcessed = `-- name: MarkInboxMessageProcessed :execrows
UPDATE inbox_messages
SET state = 'processed',
    lease_owner = NULL,
    lease_expires_at = NULL,
    processed_at = $1,
    last_error_code = NULL,
    last_error_message = NULL,
    updated_at = $1
WHERE id = $2
  AND state = 'processing'
  AND lease_owner = $3
`

type MarkInboxMessageProcessedParams struct {
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	ID          uuid.UUID          `json:"id"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) MarkInboxMessageProcessed(ctx context.Context, arg MarkInboxMessageProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInboxMessageProcessed, arg.ProcessedAt, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE outbox_events
SET state = 'published',
    lease_owner = NULL,
    lease_expires_at = NULL,
    published_at = $1,
    last_error_code = NULL,
    last_error_message = NULL
WHERE id = $2
  AND state = 'leased'
  AND lease_owner = $3
`

type MarkOutboxPublishedParams struct {
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ID          uuid.UUID          `json:"id"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublished, arg.PublishedAt, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryInboxMessage = `-- name: RetryInboxMessage :execrows
UPDATE inbox_messages
SET state = 'failed',
    available_at = $1,
    lease_owner = NULL,
    lease_expires_at = NULL,
    processed_at = NULL,
    last_error_code = $2,
    last_error_message = $3,
    updated_at = $1
WHERE id = $4
  AND state = 'processing'
  AND lease_owner = $5
`

type RetryInboxMessageParams struct {
	AvailableAt  time.Time   `json:"available_at"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
}

func (q *Queries) RetryInboxMessage(ctx context.Context, arg RetryInboxMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryInboxMessage,
		arg.AvailableAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET state = 'retry_wait',
    run_at = now() + make_interval(secs => $1::double precision / 1000.0),
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_class = $2,
    last_error_message = $3,
    updated_at = now()
WHERE id = $4
  AND state = 'leased'
  AND lease_owner = $5
  AND attempt_count < max_attempts
`

type RetryJobParams struct {
	DelayMilliseconds float64     `json:"delay_milliseconds"`
	ErrorClass        pgtype.Text `json:"error_class"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	ID                uuid.UUID   `json:"id"`
	LeaseOwner        pgtype.Text `json:"lease_owner"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.DelayMilliseconds,
		arg.ErrorClass,
		arg.ErrorMessage,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryOutboxEvent = `-- name: RetryOutboxEvent :execrows
UPDATE outbox_events
SET state = 'pending',
    available_at = $1,
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_code = $2,
    last_error_message = $3
WHERE id = $4
  AND state = 'leased'
  AND lease_owner = $5
`

type RetryOutboxEventParams struct {
	AvailableAt  time.Time   `json:"available_at"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
}

func (q *Queries) RetryOutboxEvent(ctx context.Context, arg RetryOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryOutboxEvent,
		arg.AvailableAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const succeedJob = `-- name: SucceedJob :execrows
UPDATE jobs
SET state = 'succeeded',
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_class = NULL,
    last_error_message = NULL,
    finished_at = now(),
    updated_at = now()
WHERE id = $1
  AND state = 'leased'
  AND lease_owner = $2
`

type SucceedJobParams struct {
	ID         uuid.UUID   `json:"id"`
	LeaseOwner pgtype.Text `json:"lease_owner"`
}

func (q *Queries) SucceedJob(ctx context.Context, arg SucceedJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, succeedJob, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
