// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]Job, error)
	CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (int64, error)
	DeadLetterExhaustedLeases(ctx context.Context) (int64, error)
	DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error)
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error)
	ExtendJobLease(ctx context.Context, arg ExtendJobLeaseParams) (int64, error)
	GetIdempotencyRecordForUpdate(ctx context.Context, arg GetIdempotencyRecordForUpdateParams) (IdempotencyRecord, error)
	GetJobQueueStats(ctx context.Context, jobTypes []string) ([]GetJobQueueStatsRow, error)
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) (int64, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	RetryJob(ctx context.Context, arg RetryJobParams) (int64, error)
	SucceedJob(ctx context.Context, arg SucceedJobParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
