// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publication.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicationEvent = `-- name: GetPublicationEvent :one
SELECT id, status, current_revision
FROM events
WHERE organization_id = $1 AND id = $2
`

type GetPublicationEventParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetPublicationEventRow struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	CurrentRevision int64     `json:"current_revision"`
}

func (q *Queries) GetPublicationEvent(ctx context.Context, arg GetPublicationEventParams) (GetPublicationEventRow, error) {
	row := q.db.QueryRow(ctx, getPublicationEvent, arg.OrganizationID, arg.ID)
	var i GetPublicationEventRow
	err := row.Scan(&i.ID, &i.Status, &i.CurrentRevision)
	return i, err
}

const listPublicationSessions = `-- name: ListPublicationSessions :many
SELECT s.id, s.status, s.inventory_mode, s.seat_map_version_id,
       v.status AS venue_status, sp.status AS space_status,
       COALESCE(sm.status, '') AS seat_map_status,
       COALESCE(pt.price_tier_count, 0)::bigint AS price_tier_count,
       COALESCE(sm.sellable_count, 0)::bigint AS seat_sellable_capacity,
       COALESCE(ga.pool_count, 0)::bigint AS ga_pool_count,
       COALESCE(ga.sellable_capacity, 0)::bigint AS ga_sellable_capacity,
       COALESCE(alloc.hard_quantity, 0)::bigint AS hard_allocation_quantity
FROM sessions s
JOIN venues v ON v.organization_id = s.organization_id AND v.id = s.venue_id
JOIN spaces sp ON sp.organization_id = s.organization_id AND sp.id = s.space_id
LEFT JOIN seat_map_versions sm ON sm.organization_id = s.organization_id AND sm.space_id = s.space_id AND sm.id = s.seat_map_version_id
LEFT JOIN (
    SELECT organization_id, session_id, count(*) AS price_tier_count
    FROM price_tiers
    GROUP BY organization_id, session_id
) pt ON pt.organization_id = s.organization_id AND pt.session_id = s.id
LEFT JOIN (
    SELECT organization_id, session_id, count(*)::bigint AS pool_count, sum(sellable_capacity)::bigint AS sellable_capacity
    FROM session_ga_pools
    GROUP BY organization_id, session_id
) ga ON ga.organization_id = s.organization_id AND ga.session_id = s.id
LEFT JOIN (
    SELECT organization_id, session_id, sum(quantity)::bigint AS hard_quantity
    FROM session_channel_allocations
    WHERE allocation_mode = 'hard_reserved'
    GROUP BY organization_id, session_id
) alloc ON alloc.organization_id = s.organization_id AND alloc.session_id = s.id
WHERE s.organization_id = $1 AND s.event_id = $2
ORDER BY s.starts_at ASC, s.id ASC
`

type ListPublicationSessionsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
}

type ListPublicationSessionsRow struct {
	ID                     uuid.UUID   `json:"id"`
	Status                 string      `json:"status"`
	InventoryMode          string      `json:"inventory_mode"`
	SeatMapVersionID       pgtype.UUID `json:"seat_map_version_id"`
	VenueStatus            string      `json:"venue_status"`
	SpaceStatus            string      `json:"space_status"`
	SeatMapStatus          string      `json:"seat_map_status"`
	PriceTierCount         int64       `json:"price_tier_count"`
	SeatSellableCapacity   int64       `json:"seat_sellable_capacity"`
	GaPoolCount            int64       `json:"ga_pool_count"`
	GaSellableCapacity     int64       `json:"ga_sellable_capacity"`
	HardAllocationQuantity int64       `json:"hard_allocation_quantity"`
}

func (q *Queries) ListPublicationSessions(ctx context.Context, arg ListPublicationSessionsParams) ([]ListPublicationSessionsRow, error) {
	rows, err := q.db.Query(ctx, listPublicationSessions, arg.OrganizationID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicationSessionsRow{}
	for rows.Next() {
		var i ListPublicationSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.InventoryMode,
			&i.SeatMapVersionID,
			&i.VenueStatus,
			&i.SpaceStatus,
			&i.SeatMapStatus,
			&i.PriceTierCount,
			&i.SeatSellableCapacity,
			&i.GaPoolCount,
			&i.GaSellableCapacity,
			&i.HardAllocationQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
