// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetPublicationEvent(ctx context.Context, arg GetPublicationEventParams) (GetPublicationEventRow, error)
	ListPublicationSessions(ctx context.Context, arg ListPublicationSessionsParams) ([]ListPublicationSessionsRow, error)
}

var _ Querier = (*Queries)(nil)
