//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// APIError defines model for APIError.
type APIError struct {
	Code      string            `json:"code"`
	Details   *[]ErrorDetail    `json:"details,omitempty"`
	Message   string            `json:"message"`
	RequestId RequestIdentifier `json:"request_id"`
}

// CreateUser defines model for CreateUser.
type CreateUser struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    string  `json:"code"`
	Field   *string `json:"field,omitempty"`
	Message string  `json:"message"`
}

// ErrorResponse Example: {"error":{"code":"validation_failed","details":[{"code":"invalid","field":"currency","message":"Use a supported currency."}],"message":"The request is invalid.","request_id":"req_01JEXAMPLE"}}
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// RequestIdentifier defines model for RequestIdentifier.
type RequestIdentifier = string

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// UserList defines model for UserList.
type UserList struct {
	Items  []User `json:"items"`
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
}

// Problem Example: {"error":{"code":"validation_failed","details":[{"code":"invalid","field":"currency","message":"Use a supported currency."}],"message":"The request is invalid.","request_id":"req_01JEXAMPLE"}}
type Problem = ErrorResponse

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUser

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthz Check process liveness
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// Readyz Check dependency readiness
	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)
	// ListUsers List users
	// (GET /v1/users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// CreateUser Create a user
	// (POST /v1/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// GetUser Fetch a user
	// (GET /v1/users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.Readyz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/users", wrapper.CreateUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/users/{id}", wrapper.GetUser)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFhtb9s2EP4rBNdPm19kxxlWfcuabPOQoUG2DMUCz2DEk81WIhWS8uIa+u/DUa+26TbOvPZLK4tHPnfP",
	"PXc8ZUMjlWZKgrSGhhu6BMZBu8dbeMzB2Okl/uBgIi0yK5SkIX2bsccciC4tSKS0hoThIhEcpBWxAD2g",
	"PYoWQgOnodU59KiJlpAyPPCVhpiG9Jthiz8sV82wRm6OokVR4GEmU9KA8+5Gq4cEUnyMlLQgLT6yLEtE",
	"5DwZvjfo6+aZmFdaK31bIZR42zFfEGPZQwLkT5A5vP2dXNxMCeAuUjuGEXcIfNevAulPLw/BV+bDluzC",
	"YVdu4baLm6lzzsXHuUB/WHKjVQbaCjA0jFlioEezzitkhQP+n7Kna5ALu6Th95MezZi1oDGgv+9Z/+MM",
	"/wn6r+ezb1/RHrXrDGhIjdVCLqjjwDKRuAOFhdQ8i8ZLtwm3p+xpWm47D5rTmdZs7VbBGLbY9fI8CDyO",
	"VFqbC/4S9XSVeF9S08JvHT5rsNXDe4gsYr/RwCzcGTg2B5AiD+GGxkqnzNKwetPrxjs+n3jilSzdJWaE",
	"xKRCNr/3tu3EWYO5s3yBdbP1NdQVC0j4bpTjHzyWz5fKp3N9kIWm9D/HAzyxNEucHdRlWbJBVywR3DWf",
	"ecxEApx2Cui+MRPSGdImfhrlWoOM1h1HQ3pngDBi8ixT2gIntdGAFrOu3R/LthMLQ6rTB9uyDvHHPBj9",
	"evXu4reb6yvH045Y62g+VVxNM9rTmnvro3e/Hj0J35Z1V0YX/b9KEQ3m/dl3Xhm9oDIjV9J8zuxWeXJm",
	"oW9FCj6Yw9W8Zyr4ll2eC+4zq4t8byHP+JHu7aTD4W3Vf68b8xaCL2lI6bUw9khamzviWZeFy1uxfy8k",
	"IhW2w4uQFhalqYpjA961XQKcA/VZzcb9WHGjkLHan3KmUljBEoLzhWaRJbHSxC7bCeCBRR9A8gHBEswN",
	"aAKSZ0pIawjT4GytZtJU9BELaZYwC8QkIgLCJCf/iCQhsFLJCu21yhdLt4+rKE9BYuEL7Df4XE5YWjGe",
	"sgwL3AqbAA1pZyShPboCbcoIRoNgEDjaMpAsEzSkZ4NgcEZdiS1dgnAESezyIz4vSmoxow5rymlIf6nW",
	"dwawcTDZpwyJyLSKwBjsRSwRq5NORXmaMr2mIX2zhOhDA4UwEoxxKhhqYHx9OJ7bcvm54RjQK0xWxCTR",
	"EIFYuaTGsYhOFVmPngdnh3Y0Xg7rkdfHBIcMJMfrgWD4omVjNRrmpvLQyweW+Z2zQFVoloJ15vcbKpCE",
	"xxz0uu4iYVNQ7VjNIWZ5Ymk4DnptrxLSno3LSUekedqOL9WvnqeC/YhV6XohvYg1RuDBmO3lPTjZN0TT",
	"NL2fDxlbAFGxaxTmdNKZBMGhHR7poNSCl0oNYyvdx4MyZTxq6szKzQDyo+Lrk5HcASiKYvcTs9hL7+ik",
	"6fWlFt+T6nLdyeu1KpG2Qdq5QIu+hhhwrvPf6V9QGJPg9XH2o7Mj7c+Psx+Pv5SwS00R5sS93TaHG8GL",
	"g73zZ7CV1H2dE+/Yto25kezwH0Q+Myz+743Lp+zOpwVwR87X61uTYHKU/X+Qw09go2WrBlwDvapTm+uE",
	"hnRIi1nx7wA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
