// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now()::timestamptz
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrderForOwner = `-- name: GetOrderForOwner :one
SELECT id, organization_id, cart_id, session_id, hold_id, order_number,
       owner_token_hash, owner_user_id, currency, state, subtotal_minor,
       discount_minor, fees_minor, taxes_minor, total_minor, quote_snapshot,
       quote_snapshot_raw, quote_sha256, version, created_at, updated_at, confirmed_at
FROM orders
WHERE organization_id = $1
  AND id = $2
  AND owner_token_hash = $3
`

type GetOrderForOwnerParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
}

type GetOrderForOwnerRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	CartID           uuid.UUID          `json:"cart_id"`
	SessionID        uuid.UUID          `json:"session_id"`
	HoldID           uuid.UUID          `json:"hold_id"`
	OrderNumber      string             `json:"order_number"`
	OwnerTokenHash   []byte             `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Currency         string             `json:"currency"`
	State            string             `json:"state"`
	SubtotalMinor    int64              `json:"subtotal_minor"`
	DiscountMinor    int64              `json:"discount_minor"`
	FeesMinor        int64              `json:"fees_minor"`
	TaxesMinor       int64              `json:"taxes_minor"`
	TotalMinor       int64              `json:"total_minor"`
	QuoteSnapshot    []byte             `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte             `json:"quote_snapshot_raw"`
	QuoteSha256      []byte             `json:"quote_sha256"`
	Version          int64              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) GetOrderForOwner(ctx context.Context, arg GetOrderForOwnerParams) (GetOrderForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getOrderForOwner, arg.OrganizationID, arg.ID, arg.OwnerTokenHash)
	var i GetOrderForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CartID,
		&i.SessionID,
		&i.HoldID,
		&i.OrderNumber,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.Currency,
		&i.State,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.FeesMinor,
		&i.TaxesMinor,
		&i.TotalMinor,
		&i.QuoteSnapshot,
		&i.QuoteSnapshotRaw,
		&i.QuoteSha256,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (
    id, organization_id, cart_id, session_id, hold_id, order_number,
    owner_token_hash, owner_user_id, currency, state, subtotal_minor,
    discount_minor, fees_minor, taxes_minor, total_minor, quote_snapshot,
    quote_snapshot_raw, quote_sha256, version, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $20)
RETURNING id, organization_id, cart_id, session_id, hold_id, order_number,
          owner_token_hash, owner_user_id, currency, state, subtotal_minor,
          discount_minor, fees_minor, taxes_minor, total_minor, quote_snapshot,
          quote_snapshot_raw, quote_sha256, version, created_at, updated_at, confirmed_at
`

type InsertOrderParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	CartID           uuid.UUID   `json:"cart_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	HoldID           uuid.UUID   `json:"hold_id"`
	OrderNumber      string      `json:"order_number"`
	OwnerTokenHash   []byte      `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	SubtotalMinor    int64       `json:"subtotal_minor"`
	DiscountMinor    int64       `json:"discount_minor"`
	FeesMinor        int64       `json:"fees_minor"`
	TaxesMinor       int64       `json:"taxes_minor"`
	TotalMinor       int64       `json:"total_minor"`
	QuoteSnapshot    []byte      `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte      `json:"quote_snapshot_raw"`
	QuoteSha256      []byte      `json:"quote_sha256"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
}

type InsertOrderRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	CartID           uuid.UUID          `json:"cart_id"`
	SessionID        uuid.UUID          `json:"session_id"`
	HoldID           uuid.UUID          `json:"hold_id"`
	OrderNumber      string             `json:"order_number"`
	OwnerTokenHash   []byte             `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Currency         string             `json:"currency"`
	State            string             `json:"state"`
	SubtotalMinor    int64              `json:"subtotal_minor"`
	DiscountMinor    int64              `json:"discount_minor"`
	FeesMinor        int64              `json:"fees_minor"`
	TaxesMinor       int64              `json:"taxes_minor"`
	TotalMinor       int64              `json:"total_minor"`
	QuoteSnapshot    []byte             `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte             `json:"quote_snapshot_raw"`
	QuoteSha256      []byte             `json:"quote_sha256"`
	Version          int64              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (InsertOrderRow, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.OrganizationID,
		arg.CartID,
		arg.SessionID,
		arg.HoldID,
		arg.OrderNumber,
		arg.OwnerTokenHash,
		arg.OwnerUserID,
		arg.Currency,
		arg.State,
		arg.SubtotalMinor,
		arg.DiscountMinor,
		arg.FeesMinor,
		arg.TaxesMinor,
		arg.TotalMinor,
		arg.QuoteSnapshot,
		arg.QuoteSnapshotRaw,
		arg.QuoteSha256,
		arg.Version,
		arg.CreatedAt,
	)
	var i InsertOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CartID,
		&i.SessionID,
		&i.HoldID,
		&i.OrderNumber,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.Currency,
		&i.State,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.FeesMinor,
		&i.TaxesMinor,
		&i.TotalMinor,
		&i.QuoteSnapshot,
		&i.QuoteSnapshotRaw,
		&i.QuoteSha256,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const insertOrderLine = `-- name: InsertOrderLine :exec
INSERT INTO order_lines (
    id, organization_id, order_id, line_number, price_tier_id, quantity,
    unit_minor, subtotal_minor, snapshot, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertOrderLineParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	OrderID        uuid.UUID `json:"order_id"`
	LineNumber     int32     `json:"line_number"`
	PriceTierID    uuid.UUID `json:"price_tier_id"`
	Quantity       int64     `json:"quantity"`
	UnitMinor      int64     `json:"unit_minor"`
	SubtotalMinor  int64     `json:"subtotal_minor"`
	Snapshot       []byte    `json:"snapshot"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertOrderLine(ctx context.Context, arg InsertOrderLineParams) error {
	_, err := q.db.Exec(ctx, insertOrderLine,
		arg.ID,
		arg.OrganizationID,
		arg.OrderID,
		arg.LineNumber,
		arg.PriceTierID,
		arg.Quantity,
		arg.UnitMinor,
		arg.SubtotalMinor,
		arg.Snapshot,
		arg.CreatedAt,
	)
	return err
}

const listOrderLines = `-- name: ListOrderLines :many
SELECT id, organization_id, order_id, line_number, price_tier_id, quantity,
       unit_minor, subtotal_minor, snapshot, created_at
FROM order_lines
WHERE organization_id = $1
  AND order_id = $2
ORDER BY line_number ASC, id ASC
`

type ListOrderLinesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	OrderID        uuid.UUID `json:"order_id"`
}

func (q *Queries) ListOrderLines(ctx context.Context, arg ListOrderLinesParams) ([]OrderLine, error) {
	rows, err := q.db.Query(ctx, listOrderLines, arg.OrganizationID, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderLine{}
	for rows.Next() {
		var i OrderLine
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrderID,
			&i.LineNumber,
			&i.PriceTierID,
			&i.Quantity,
			&i.UnitMinor,
			&i.SubtotalMinor,
			&i.Snapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCartForCheckout = `-- name: LockCartForCheckout :one
SELECT id, organization_id, session_id, hold_id, owner_token_hash, owner_user_id,
       currency, state, quote_snapshot, quote_snapshot_raw, quote_sha256, version, created_at, updated_at
FROM carts
WHERE organization_id = $1
  AND id = $2
  AND owner_token_hash = $3
FOR UPDATE
`

type LockCartForCheckoutParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
}

type LockCartForCheckoutRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	HoldID           uuid.UUID   `json:"hold_id"`
	OwnerTokenHash   []byte      `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	QuoteSnapshot    []byte      `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte      `json:"quote_snapshot_raw"`
	QuoteSha256      []byte      `json:"quote_sha256"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) LockCartForCheckout(ctx context.Context, arg LockCartForCheckoutParams) (LockCartForCheckoutRow, error) {
	row := q.db.QueryRow(ctx, lockCartForCheckout, arg.OrganizationID, arg.ID, arg.OwnerTokenHash)
	var i LockCartForCheckoutRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.HoldID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.Currency,
		&i.State,
		&i.QuoteSnapshot,
		&i.QuoteSnapshotRaw,
		&i.QuoteSha256,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockHoldForCheckout = `-- name: LockHoldForCheckout :one
SELECT id, organization_id, session_id, owner_token_hash, currency, state, expires_at
FROM holds
WHERE organization_id = $1
  AND id = $2
  AND owner_token_hash = $3
FOR UPDATE
`

type LockHoldForCheckoutParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
}

type LockHoldForCheckoutRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
	Currency       string    `json:"currency"`
	State          string    `json:"state"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) LockHoldForCheckout(ctx context.Context, arg LockHoldForCheckoutParams) (LockHoldForCheckoutRow, error) {
	row := q.db.QueryRow(ctx, lockHoldForCheckout, arg.OrganizationID, arg.ID, arg.OwnerTokenHash)
	var i LockHoldForCheckoutRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.OwnerTokenHash,
		&i.Currency,
		&i.State,
		&i.ExpiresAt,
	)
	return i, err
}

const markCartCheckedOut = `-- name: MarkCartCheckedOut :one
UPDATE carts
SET state = 'checked_out', version = version + 1, updated_at = $3
WHERE organization_id = $1
  AND id = $2
  AND owner_token_hash = $4
  AND state = 'active'
  AND version = $5
RETURNING id, organization_id, session_id, hold_id, owner_token_hash, owner_user_id,
          currency, state, quote_snapshot, quote_snapshot_raw, quote_sha256, version, created_at, updated_at
`

type MarkCartCheckedOutParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	UpdatedAt      time.Time `json:"updated_at"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
	Version        int64     `json:"version"`
}

type MarkCartCheckedOutRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	HoldID           uuid.UUID   `json:"hold_id"`
	OwnerTokenHash   []byte      `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	QuoteSnapshot    []byte      `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte      `json:"quote_snapshot_raw"`
	QuoteSha256      []byte      `json:"quote_sha256"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) MarkCartCheckedOut(ctx context.Context, arg MarkCartCheckedOutParams) (MarkCartCheckedOutRow, error) {
	row := q.db.QueryRow(ctx, markCartCheckedOut,
		arg.OrganizationID,
		arg.ID,
		arg.UpdatedAt,
		arg.OwnerTokenHash,
		arg.Version,
	)
	var i MarkCartCheckedOutRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.HoldID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.Currency,
		&i.State,
		&i.QuoteSnapshot,
		&i.QuoteSnapshotRaw,
		&i.QuoteSha256,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
