// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, organization_id, prefix, name, secret_hash, scopes,
       created_by_type, created_by_id, expires_at, revoked_at,
       last_used_at, version, created_at, updated_at
FROM api_keys
WHERE organization_id = $1
  AND id = $2
`

type GetAPIKeyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.OrganizationID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Prefix,
		&i.Name,
		&i.SecretHash,
		&i.Scopes,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyForUpdate = `-- name: GetAPIKeyForUpdate :one
SELECT id, organization_id, prefix, name, secret_hash, scopes,
       created_by_type, created_by_id, expires_at, revoked_at,
       last_used_at, version, created_at, updated_at
FROM api_keys
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type GetAPIKeyForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetAPIKeyForUpdate(ctx context.Context, arg GetAPIKeyForUpdateParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyForUpdate, arg.OrganizationID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Prefix,
		&i.Name,
		&i.SecretHash,
		&i.Scopes,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (
    id, organization_id, prefix, name, secret_hash, scopes,
    created_by_type, created_by_id, expires_at, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12
)
RETURNING id, organization_id, prefix, name, secret_hash, scopes,
          created_by_type, created_by_id, expires_at, revoked_at,
          last_used_at, version, created_at, updated_at
`

type InsertAPIKeyParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Prefix         string             `json:"prefix"`
	Name           string             `json:"name"`
	SecretHash     []byte             `json:"secret_hash"`
	Scopes         []string           `json:"scopes"`
	CreatedByType  string             `json:"created_by_type"`
	CreatedByID    string             `json:"created_by_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.ID,
		arg.OrganizationID,
		arg.Prefix,
		arg.Name,
		arg.SecretHash,
		arg.Scopes,
		arg.CreatedByType,
		arg.CreatedByID,
		arg.ExpiresAt,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Prefix,
		&i.Name,
		&i.SecretHash,
		&i.Scopes,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, organization_id, prefix, name, scopes,
       created_by_type, created_by_id, expires_at, revoked_at,
       last_used_at, version, created_at, updated_at
FROM api_keys
WHERE organization_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAPIKeysParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	LimitCount     int32              `json:"limit_count"`
}

type ListAPIKeysRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Prefix         string             `json:"prefix"`
	Name           string             `json:"name"`
	Scopes         []string           `json:"scopes"`
	CreatedByType  string             `json:"created_by_type"`
	CreatedByID    string             `json:"created_by_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	Version        int64              `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys,
		arg.OrganizationID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Prefix,
			&i.Name,
			&i.Scopes,
			&i.CreatedByType,
			&i.CreatedByID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganizationForAPIKey = `-- name: LockOrganizationForAPIKey :one
SELECT id, status
FROM organizations
WHERE id = $1
FOR UPDATE
`

type LockOrganizationForAPIKeyRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) LockOrganizationForAPIKey(ctx context.Context, id uuid.UUID) (LockOrganizationForAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, lockOrganizationForAPIKey, id)
	var i LockOrganizationForAPIKeyRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const lookupAPIKeyByPrefix = `-- name: LookupAPIKeyByPrefix :one
SELECT id, organization_id, prefix, name, secret_hash, scopes,
       created_by_type, created_by_id, expires_at, revoked_at,
       last_used_at, version, created_at, updated_at
FROM api_keys
WHERE prefix = $1
`

func (q *Queries) LookupAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, lookupAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Prefix,
		&i.Name,
		&i.SecretHash,
		&i.Scopes,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = $1,
    version = version + 1,
    updated_at = $2
WHERE organization_id = $3
  AND id = $4
  AND version = $5
  AND revoked_at IS NULL
RETURNING id, organization_id, prefix, name, secret_hash, scopes,
          created_by_type, created_by_id, expires_at, revoked_at,
          last_used_at, version, created_at, updated_at
`

type RevokeAPIKeyParams struct {
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	ID              uuid.UUID          `json:"id"`
	ExpectedVersion int64              `json:"expected_version"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey,
		arg.RevokedAt,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Prefix,
		&i.Name,
		&i.SecretHash,
		&i.Scopes,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :execrows
UPDATE api_keys
SET last_used_at = $1,
    updated_at = $2
WHERE id = $3
  AND revoked_at IS NULL
`

type TouchAPIKeyParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAPIKey, arg.LastUsedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
