// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	GetAPIKeyForUpdate(ctx context.Context, arg GetAPIKeyForUpdateParams) (ApiKey, error)
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error)
	LockOrganizationForAPIKey(ctx context.Context, id uuid.UUID) (LockOrganizationForAPIKeyRow, error)
	LookupAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
