// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completePlatformIdempotencyRecord = `-- name: CompletePlatformIdempotencyRecord :execrows
UPDATE idempotency_records
SET state = 'completed', locked_until = NULL, response_status = 201,
    resource_type = 'organization', resource_id = $2, updated_at = $3
WHERE id = $1 AND organization_id IS NULL AND state = 'processing'
`

type CompletePlatformIdempotencyRecordParams struct {
	ID         uuid.UUID   `json:"id"`
	ResourceID pgtype.Text `json:"resource_id"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

func (q *Queries) CompletePlatformIdempotencyRecord(ctx context.Context, arg CompletePlatformIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, completePlatformIdempotencyRecord, arg.ID, arg.ResourceID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, slug, display_name, status, default_locale, default_timezone,
       default_currency, settings_version, created_at, updated_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.DefaultLocale,
		&i.DefaultTimezone,
		&i.DefaultCurrency,
		&i.SettingsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformIdempotencyRecordForUpdate = `-- name: GetPlatformIdempotencyRecordForUpdate :one
SELECT id, organization_id, principal_type, principal_id, operation,
       idempotency_key, request_fingerprint, state, locked_until,
       response_status, response_body, resource_type, resource_id,
       expires_at, created_at, updated_at
FROM idempotency_records
WHERE organization_id IS NULL
  AND principal_type = 'platform'
  AND principal_id = $1
  AND operation = 'organization.create'
  AND idempotency_key = $2
FOR UPDATE
`

type GetPlatformIdempotencyRecordForUpdateParams struct {
	PrincipalID    string `json:"principal_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetPlatformIdempotencyRecordForUpdate(ctx context.Context, arg GetPlatformIdempotencyRecordForUpdateParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getPlatformIdempotencyRecordForUpdate, arg.PrincipalID, arg.IdempotencyKey)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.State,
		&i.LockedUntil,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrganization = `-- name: InsertOrganization :one
INSERT INTO organizations (
    id, slug, display_name, status, default_locale, default_timezone,
    default_currency, settings_version, created_at, updated_at
) VALUES (
    $1, $2, $3, 'active', $4, $5,
    $6, 1, $7, $7
)
RETURNING id, slug, display_name, status, default_locale, default_timezone,
          default_currency, settings_version, created_at, updated_at
`

type InsertOrganizationParams struct {
	ID              uuid.UUID `json:"id"`
	Slug            string    `json:"slug"`
	DisplayName     string    `json:"display_name"`
	DefaultLocale   string    `json:"default_locale"`
	DefaultTimezone string    `json:"default_timezone"`
	DefaultCurrency string    `json:"default_currency"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, insertOrganization,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.DefaultLocale,
		arg.DefaultTimezone,
		arg.DefaultCurrency,
		arg.CreatedAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.DefaultLocale,
		&i.DefaultTimezone,
		&i.DefaultCurrency,
		&i.SettingsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlatformIdempotencyRecord = `-- name: InsertPlatformIdempotencyRecord :execrows
INSERT INTO idempotency_records (
    id, organization_id, principal_type, principal_id, operation,
    idempotency_key, request_fingerprint, state, locked_until, expires_at,
    created_at, updated_at
) VALUES (
    $1, NULL, 'platform', $2, 'organization.create',
    $3, $4, 'processing', $5, $6,
    $7, $7
)
ON CONFLICT (organization_id, principal_type, principal_id, operation, idempotency_key)
DO NOTHING
`

type InsertPlatformIdempotencyRecordParams struct {
	ID                 uuid.UUID          `json:"id"`
	PrincipalID        string             `json:"principal_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt          time.Time          `json:"expires_at"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) InsertPlatformIdempotencyRecord(ctx context.Context, arg InsertPlatformIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPlatformIdempotencyRecord,
		arg.ID,
		arg.PrincipalID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.LockedUntil,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
