// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompletePlatformIdempotencyRecord(ctx context.Context, arg CompletePlatformIdempotencyRecordParams) (int64, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetPlatformIdempotencyRecordForUpdate(ctx context.Context, arg GetPlatformIdempotencyRecordForUpdateParams) (IdempotencyRecord, error)
	InsertOrganization(ctx context.Context, arg InsertOrganizationParams) (Organization, error)
	InsertPlatformIdempotencyRecord(ctx context.Context, arg InsertPlatformIdempotencyRecordParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
