// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSalesChannel = `-- name: InsertSalesChannel :one
INSERT INTO sales_channels (id, organization_id, channel_key, display_name, channel_type, configuration, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING id, organization_id, channel_key, display_name, channel_type, configuration, status, version, created_at, updated_at
`

type InsertSalesChannelParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	ChannelKey     string    `json:"channel_key"`
	DisplayName    string    `json:"display_name"`
	ChannelType    string    `json:"channel_type"`
	Configuration  []byte    `json:"configuration"`
	Status         string    `json:"status"`
	Version        int64     `json:"version"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertSalesChannel(ctx context.Context, arg InsertSalesChannelParams) (SalesChannel, error) {
	row := q.db.QueryRow(ctx, insertSalesChannel,
		arg.ID,
		arg.OrganizationID,
		arg.ChannelKey,
		arg.DisplayName,
		arg.ChannelType,
		arg.Configuration,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
	)
	var i SalesChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ChannelKey,
		&i.DisplayName,
		&i.ChannelType,
		&i.Configuration,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSessionChannelAllocation = `-- name: InsertSessionChannelAllocation :one
INSERT INTO session_channel_allocations (id, organization_id, session_id, channel_id, scope_key, allocation_mode, quantity, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING id, organization_id, session_id, channel_id, scope_key, allocation_mode, quantity, version, created_at, updated_at
`

type InsertSessionChannelAllocationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	ChannelID      uuid.UUID `json:"channel_id"`
	ScopeKey       string    `json:"scope_key"`
	AllocationMode string    `json:"allocation_mode"`
	Quantity       int64     `json:"quantity"`
	Version        int64     `json:"version"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertSessionChannelAllocation(ctx context.Context, arg InsertSessionChannelAllocationParams) (SessionChannelAllocation, error) {
	row := q.db.QueryRow(ctx, insertSessionChannelAllocation,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.ChannelID,
		arg.ScopeKey,
		arg.AllocationMode,
		arg.Quantity,
		arg.Version,
		arg.CreatedAt,
	)
	var i SessionChannelAllocation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.ChannelID,
		&i.ScopeKey,
		&i.AllocationMode,
		&i.Quantity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSalesChannels = `-- name: ListSalesChannels :many
SELECT id, organization_id, channel_key, display_name, channel_type, configuration, status, version, created_at, updated_at
FROM sales_channels
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListSalesChannelsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListSalesChannels(ctx context.Context, arg ListSalesChannelsParams) ([]SalesChannel, error) {
	rows, err := q.db.Query(ctx, listSalesChannels, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesChannel{}
	for rows.Next() {
		var i SalesChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ChannelKey,
			&i.DisplayName,
			&i.ChannelType,
			&i.Configuration,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesChannelsAfter = `-- name: ListSalesChannelsAfter :many
SELECT id, organization_id, channel_key, display_name, channel_type, configuration, status, version, created_at, updated_at
FROM sales_channels
WHERE organization_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListSalesChannelsAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListSalesChannelsAfter(ctx context.Context, arg ListSalesChannelsAfterParams) ([]SalesChannel, error) {
	rows, err := q.db.Query(ctx, listSalesChannelsAfter,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesChannel{}
	for rows.Next() {
		var i SalesChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ChannelKey,
			&i.DisplayName,
			&i.ChannelType,
			&i.Configuration,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionChannelAllocations = `-- name: ListSessionChannelAllocations :many
SELECT id, organization_id, session_id, channel_id, scope_key, allocation_mode, quantity, version, created_at, updated_at
FROM session_channel_allocations
WHERE organization_id = $1 AND session_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListSessionChannelAllocationsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListSessionChannelAllocations(ctx context.Context, arg ListSessionChannelAllocationsParams) ([]SessionChannelAllocation, error) {
	rows, err := q.db.Query(ctx, listSessionChannelAllocations, arg.OrganizationID, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionChannelAllocation{}
	for rows.Next() {
		var i SessionChannelAllocation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.ChannelID,
			&i.ScopeKey,
			&i.AllocationMode,
			&i.Quantity,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionChannelAllocationsAfter = `-- name: ListSessionChannelAllocationsAfter :many
SELECT id, organization_id, session_id, channel_id, scope_key, allocation_mode, quantity, version, created_at, updated_at
FROM session_channel_allocations
WHERE organization_id = $1 AND session_id = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSessionChannelAllocationsAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	SessionID       uuid.UUID `json:"session_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListSessionChannelAllocationsAfter(ctx context.Context, arg ListSessionChannelAllocationsAfterParams) ([]SessionChannelAllocation, error) {
	rows, err := q.db.Query(ctx, listSessionChannelAllocationsAfter,
		arg.OrganizationID,
		arg.SessionID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionChannelAllocation{}
	for rows.Next() {
		var i SessionChannelAllocation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.ChannelID,
			&i.ScopeKey,
			&i.AllocationMode,
			&i.Quantity,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionForAllocation = `-- name: LockSessionForAllocation :one
SELECT s.id, s.space_id, sp.physical_capacity
FROM sessions s
JOIN spaces sp ON sp.organization_id = s.organization_id AND sp.id = s.space_id
WHERE s.organization_id = $1 AND s.event_id = $2 AND s.id = $3
FOR UPDATE OF s
`

type LockSessionForAllocationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
	ID             uuid.UUID `json:"id"`
}

type LockSessionForAllocationRow struct {
	ID               uuid.UUID `json:"id"`
	SpaceID          uuid.UUID `json:"space_id"`
	PhysicalCapacity int64     `json:"physical_capacity"`
}

func (q *Queries) LockSessionForAllocation(ctx context.Context, arg LockSessionForAllocationParams) (LockSessionForAllocationRow, error) {
	row := q.db.QueryRow(ctx, lockSessionForAllocation, arg.OrganizationID, arg.EventID, arg.ID)
	var i LockSessionForAllocationRow
	err := row.Scan(&i.ID, &i.SpaceID, &i.PhysicalCapacity)
	return i, err
}

const sumHardSessionAllocations = `-- name: SumHardSessionAllocations :one
SELECT COALESCE(SUM(quantity), 0)::bigint
FROM session_channel_allocations
WHERE organization_id = $1 AND session_id = $2 AND allocation_mode = 'hard_reserved'
`

type SumHardSessionAllocationsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

func (q *Queries) SumHardSessionAllocations(ctx context.Context, arg SumHardSessionAllocationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumHardSessionAllocations, arg.OrganizationID, arg.SessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
