// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	InsertSalesChannel(ctx context.Context, arg InsertSalesChannelParams) (SalesChannel, error)
	InsertSessionChannelAllocation(ctx context.Context, arg InsertSessionChannelAllocationParams) (SessionChannelAllocation, error)
	ListSalesChannels(ctx context.Context, arg ListSalesChannelsParams) ([]SalesChannel, error)
	ListSalesChannelsAfter(ctx context.Context, arg ListSalesChannelsAfterParams) ([]SalesChannel, error)
	ListSessionChannelAllocations(ctx context.Context, arg ListSessionChannelAllocationsParams) ([]SessionChannelAllocation, error)
	ListSessionChannelAllocationsAfter(ctx context.Context, arg ListSessionChannelAllocationsAfterParams) ([]SessionChannelAllocation, error)
	LockSessionForAllocation(ctx context.Context, arg LockSessionForAllocationParams) (LockSessionForAllocationRow, error)
	SumHardSessionAllocations(ctx context.Context, arg SumHardSessionAllocationsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
