// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations
SET status = 'accepted', membership_id = $2, accepted_at = $3, version = version + 1, updated_at = $3
WHERE id = $1 AND status = 'invited' AND version = $4
RETURNING id, organization_id, normalized_email, role, status, expires_at,
          created_by_type, created_by_id, membership_id, accepted_at, revoked_at,
          version, created_at, updated_at
`

type AcceptInvitationParams struct {
	ID           uuid.UUID          `json:"id"`
	MembershipID pgtype.UUID        `json:"membership_id"`
	AcceptedAt   pgtype.Timestamptz `json:"accepted_at"`
	Version      int64              `json:"version"`
}

type AcceptInvitationRow struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	NormalizedEmail string             `json:"normalized_email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ExpiresAt       time.Time          `json:"expires_at"`
	CreatedByType   string             `json:"created_by_type"`
	CreatedByID     pgtype.Text        `json:"created_by_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Version         int64              `json:"version"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (AcceptInvitationRow, error) {
	row := q.db.QueryRow(ctx, acceptInvitation,
		arg.ID,
		arg.MembershipID,
		arg.AcceptedAt,
		arg.Version,
	)
	var i AcceptInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NormalizedEmail,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.MembershipID,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireInvitation = `-- name: ExpireInvitation :one
UPDATE invitations
SET status = 'expired', version = version + 1, updated_at = $2
WHERE id = $1 AND status = 'invited' AND version = $3
RETURNING id, organization_id, normalized_email, role, status, expires_at,
          created_by_type, created_by_id, membership_id, accepted_at, revoked_at,
          version, created_at, updated_at
`

type ExpireInvitationParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
	Version   int64     `json:"version"`
}

type ExpireInvitationRow struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	NormalizedEmail string             `json:"normalized_email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ExpiresAt       time.Time          `json:"expires_at"`
	CreatedByType   string             `json:"created_by_type"`
	CreatedByID     pgtype.Text        `json:"created_by_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Version         int64              `json:"version"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) ExpireInvitation(ctx context.Context, arg ExpireInvitationParams) (ExpireInvitationRow, error) {
	row := q.db.QueryRow(ctx, expireInvitation, arg.ID, arg.UpdatedAt, arg.Version)
	var i ExpireInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NormalizedEmail,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.MembershipID,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationForUpdate = `-- name: GetInvitationForUpdate :one
SELECT id, organization_id, normalized_email, role, status, expires_at,
       created_by_type, created_by_id, membership_id, accepted_at, revoked_at,
       version, created_at, updated_at
FROM invitations
WHERE organization_id = $1 AND id = $2
FOR UPDATE
`

type GetInvitationForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetInvitationForUpdateRow struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	NormalizedEmail string             `json:"normalized_email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ExpiresAt       time.Time          `json:"expires_at"`
	CreatedByType   string             `json:"created_by_type"`
	CreatedByID     pgtype.Text        `json:"created_by_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Version         int64              `json:"version"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) GetInvitationForUpdate(ctx context.Context, arg GetInvitationForUpdateParams) (GetInvitationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInvitationForUpdate, arg.OrganizationID, arg.ID)
	var i GetInvitationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NormalizedEmail,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.MembershipID,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationForUpdateByToken = `-- name: GetInvitationForUpdateByToken :one
SELECT id, organization_id, normalized_email, role, status, expires_at,
       created_by_type, created_by_id, membership_id, accepted_at, revoked_at,
       version, created_at, updated_at
FROM invitations
WHERE token_hash = $1
FOR UPDATE
`

type GetInvitationForUpdateByTokenRow struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	NormalizedEmail string             `json:"normalized_email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ExpiresAt       time.Time          `json:"expires_at"`
	CreatedByType   string             `json:"created_by_type"`
	CreatedByID     pgtype.Text        `json:"created_by_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Version         int64              `json:"version"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) GetInvitationForUpdateByToken(ctx context.Context, tokenHash []byte) (GetInvitationForUpdateByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInvitationForUpdateByToken, tokenHash)
	var i GetInvitationForUpdateByTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NormalizedEmail,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.MembershipID,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipForInvitation = `-- name: GetMembershipForInvitation :one
SELECT id, status
FROM memberships
WHERE organization_id = $1 AND user_id = $2
FOR UPDATE
`

type GetMembershipForInvitationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

type GetMembershipForInvitationRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) GetMembershipForInvitation(ctx context.Context, arg GetMembershipForInvitationParams) (GetMembershipForInvitationRow, error) {
	row := q.db.QueryRow(ctx, getMembershipForInvitation, arg.OrganizationID, arg.UserID)
	var i GetMembershipForInvitationRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getUserForInvitation = `-- name: GetUserForInvitation :one
SELECT id, email
FROM users
WHERE id = $1
FOR UPDATE
`

type GetUserForInvitationRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) GetUserForInvitation(ctx context.Context, id uuid.UUID) (GetUserForInvitationRow, error) {
	row := q.db.QueryRow(ctx, getUserForInvitation, id)
	var i GetUserForInvitationRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const insertInvitation = `-- name: InsertInvitation :one
INSERT INTO invitations (
    id, organization_id, normalized_email, role, token_hash, status, expires_at,
    created_by_type, created_by_id, version, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, 'invited', $6, $7, NULLIF($8::text, ''), $9, $10, $10)
RETURNING id, organization_id, normalized_email, role, status, expires_at,
          created_by_type, created_by_id, membership_id, accepted_at, revoked_at,
          version, created_at, updated_at
`

type InsertInvitationParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	NormalizedEmail string    `json:"normalized_email"`
	Role            string    `json:"role"`
	TokenHash       []byte    `json:"token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
	CreatedByType   string    `json:"created_by_type"`
	Column8         string    `json:"column_8"`
	Version         int64     `json:"version"`
	CreatedAt       time.Time `json:"created_at"`
}

type InsertInvitationRow struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	NormalizedEmail string             `json:"normalized_email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ExpiresAt       time.Time          `json:"expires_at"`
	CreatedByType   string             `json:"created_by_type"`
	CreatedByID     pgtype.Text        `json:"created_by_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Version         int64              `json:"version"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) (InsertInvitationRow, error) {
	row := q.db.QueryRow(ctx, insertInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.NormalizedEmail,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedByType,
		arg.Column8,
		arg.Version,
		arg.CreatedAt,
	)
	var i InsertInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NormalizedEmail,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.MembershipID,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMembershipFromInvitation = `-- name: InsertMembershipFromInvitation :one
INSERT INTO memberships (
    id, organization_id, user_id, role, status, venue_scope, version, created_at, updated_at
)
VALUES ($1, $2, $3, $4, 'active', '{}', 1, $5, $5)
RETURNING id, organization_id, user_id, role, status, venue_scope, version,
          created_at, updated_at, revoked_at
`

type InsertMembershipFromInvitationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertMembershipFromInvitation(ctx context.Context, arg InsertMembershipFromInvitationParams) (Membership, error) {
	row := q.db.QueryRow(ctx, insertMembershipFromInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.VenueScope,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listDueInvitations = `-- name: ListDueInvitations :many
SELECT id, organization_id, version
FROM invitations
WHERE status = 'invited' AND expires_at <= $1
ORDER BY expires_at ASC, id ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListDueInvitationsParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	Limit     int32     `json:"limit"`
}

type ListDueInvitationsRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Version        int64     `json:"version"`
}

func (q *Queries) ListDueInvitations(ctx context.Context, arg ListDueInvitationsParams) ([]ListDueInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listDueInvitations, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueInvitationsRow{}
	for rows.Next() {
		var i ListDueInvitationsRow
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganizationForInvitation = `-- name: LockOrganizationForInvitation :one
SELECT id, status
FROM organizations
WHERE id = $1
FOR UPDATE
`

type LockOrganizationForInvitationRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) LockOrganizationForInvitation(ctx context.Context, id uuid.UUID) (LockOrganizationForInvitationRow, error) {
	row := q.db.QueryRow(ctx, lockOrganizationForInvitation, id)
	var i LockOrganizationForInvitationRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE invitations
SET status = 'revoked', revoked_at = $4, version = version + 1, updated_at = $4
WHERE organization_id = $1 AND id = $2 AND status = 'invited' AND version = $3
RETURNING id, organization_id, normalized_email, role, status, expires_at,
          created_by_type, created_by_id, membership_id, accepted_at, revoked_at,
          version, created_at, updated_at
`

type RevokeInvitationParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ID             uuid.UUID          `json:"id"`
	Version        int64              `json:"version"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type RevokeInvitationRow struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	NormalizedEmail string             `json:"normalized_email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	ExpiresAt       time.Time          `json:"expires_at"`
	CreatedByType   string             `json:"created_by_type"`
	CreatedByID     pgtype.Text        `json:"created_by_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Version         int64              `json:"version"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (RevokeInvitationRow, error) {
	row := q.db.QueryRow(ctx, revokeInvitation,
		arg.OrganizationID,
		arg.ID,
		arg.Version,
		arg.RevokedAt,
	)
	var i RevokeInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.NormalizedEmail,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.MembershipID,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
