// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (AcceptInvitationRow, error)
	ExpireInvitation(ctx context.Context, arg ExpireInvitationParams) (ExpireInvitationRow, error)
	GetInvitationForUpdate(ctx context.Context, arg GetInvitationForUpdateParams) (GetInvitationForUpdateRow, error)
	GetInvitationForUpdateByToken(ctx context.Context, tokenHash []byte) (GetInvitationForUpdateByTokenRow, error)
	GetMembershipForInvitation(ctx context.Context, arg GetMembershipForInvitationParams) (GetMembershipForInvitationRow, error)
	GetUserForInvitation(ctx context.Context, id uuid.UUID) (GetUserForInvitationRow, error)
	InsertInvitation(ctx context.Context, arg InsertInvitationParams) (InsertInvitationRow, error)
	InsertMembershipFromInvitation(ctx context.Context, arg InsertMembershipFromInvitationParams) (Membership, error)
	ListDueInvitations(ctx context.Context, arg ListDueInvitationsParams) ([]ListDueInvitationsRow, error)
	LockOrganizationForInvitation(ctx context.Context, id uuid.UUID) (LockOrganizationForInvitationRow, error)
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (RevokeInvitationRow, error)
}

var _ Querier = (*Queries)(nil)
