// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetPublishedEventRevision(ctx context.Context, arg GetPublishedEventRevisionParams) (uuid.UUID, error)
	GetPublishedSeatMapForSession(ctx context.Context, arg GetPublishedSeatMapForSessionParams) (GetPublishedSeatMapForSessionRow, error)
	GetPublishedSeatMapVersion(ctx context.Context, arg GetPublishedSeatMapVersionParams) (uuid.UUID, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error)
	InsertSessionGAPool(ctx context.Context, arg InsertSessionGAPoolParams) error
	InsertSessionSeat(ctx context.Context, arg InsertSessionSeatParams) error
	ListActiveGAPoolTemplatesForSession(ctx context.Context, arg ListActiveGAPoolTemplatesForSessionParams) ([]ListActiveGAPoolTemplatesForSessionRow, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	ListSessionsAfter(ctx context.Context, arg ListSessionsAfterParams) ([]Session, error)
	LockSpaceForSession(ctx context.Context, arg LockSpaceForSessionParams) (LockSpaceForSessionRow, error)
	SessionOverlap(ctx context.Context, arg SessionOverlapParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
