// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPublishedEventRevision = `-- name: GetPublishedEventRevision :one
SELECT id
FROM event_revisions
WHERE organization_id = $1 AND event_id = $2 AND revision = $3 AND status = 'published'
`

type GetPublishedEventRevisionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
	Revision       int64     `json:"revision"`
}

func (q *Queries) GetPublishedEventRevision(ctx context.Context, arg GetPublishedEventRevisionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPublishedEventRevision, arg.OrganizationID, arg.EventID, arg.Revision)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPublishedSeatMapForSession = `-- name: GetPublishedSeatMapForSession :one
SELECT id, content
FROM seat_map_versions
WHERE organization_id = $1 AND space_id = $2 AND id = $3 AND status = 'published'
`

type GetPublishedSeatMapForSessionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	ID             uuid.UUID `json:"id"`
}

type GetPublishedSeatMapForSessionRow struct {
	ID      uuid.UUID `json:"id"`
	Content []byte    `json:"content"`
}

func (q *Queries) GetPublishedSeatMapForSession(ctx context.Context, arg GetPublishedSeatMapForSessionParams) (GetPublishedSeatMapForSessionRow, error) {
	row := q.db.QueryRow(ctx, getPublishedSeatMapForSession, arg.OrganizationID, arg.SpaceID, arg.ID)
	var i GetPublishedSeatMapForSessionRow
	err := row.Scan(&i.ID, &i.Content)
	return i, err
}

const getPublishedSeatMapVersion = `-- name: GetPublishedSeatMapVersion :one
SELECT id
FROM seat_map_versions
WHERE organization_id = $1 AND space_id = $2 AND id = $3 AND status = 'published'
`

type GetPublishedSeatMapVersionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetPublishedSeatMapVersion(ctx context.Context, arg GetPublishedSeatMapVersionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPublishedSeatMapVersion, arg.OrganizationID, arg.SpaceID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSession = `-- name: GetSession :one
SELECT id, organization_id, event_id, event_revision, venue_id, space_id, seat_map_version_id, inventory_mode, doors_at, starts_at, ends_at, sales_start_at, sales_end_at, timezone, status, version, created_at, updated_at, inventory_revision
FROM sessions
WHERE organization_id = $1 AND event_id = $2 AND id = $3
`

type GetSessionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.OrganizationID, arg.EventID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.EventRevision,
		&i.VenueID,
		&i.SpaceID,
		&i.SeatMapVersionID,
		&i.InventoryMode,
		&i.DoorsAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Timezone,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InventoryRevision,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (id, organization_id, event_id, event_revision, venue_id, space_id, seat_map_version_id, inventory_mode, doors_at, starts_at, ends_at, sales_start_at, sales_end_at, timezone, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $17)
RETURNING id, organization_id, event_id, event_revision, venue_id, space_id, seat_map_version_id, inventory_mode, doors_at, starts_at, ends_at, sales_start_at, sales_end_at, timezone, status, version, created_at, updated_at, inventory_revision
`

type InsertSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	EventID          uuid.UUID          `json:"event_id"`
	EventRevision    int64              `json:"event_revision"`
	VenueID          uuid.UUID          `json:"venue_id"`
	SpaceID          uuid.UUID          `json:"space_id"`
	SeatMapVersionID pgtype.UUID        `json:"seat_map_version_id"`
	InventoryMode    string             `json:"inventory_mode"`
	DoorsAt          pgtype.Timestamptz `json:"doors_at"`
	StartsAt         time.Time          `json:"starts_at"`
	EndsAt           time.Time          `json:"ends_at"`
	SalesStartAt     pgtype.Timestamptz `json:"sales_start_at"`
	SalesEndAt       pgtype.Timestamptz `json:"sales_end_at"`
	Timezone         string             `json:"timezone"`
	Status           string             `json:"status"`
	Version          int64              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.OrganizationID,
		arg.EventID,
		arg.EventRevision,
		arg.VenueID,
		arg.SpaceID,
		arg.SeatMapVersionID,
		arg.InventoryMode,
		arg.DoorsAt,
		arg.StartsAt,
		arg.EndsAt,
		arg.SalesStartAt,
		arg.SalesEndAt,
		arg.Timezone,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventID,
		&i.EventRevision,
		&i.VenueID,
		&i.SpaceID,
		&i.SeatMapVersionID,
		&i.InventoryMode,
		&i.DoorsAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Timezone,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InventoryRevision,
	)
	return i, err
}

const insertSessionGAPool = `-- name: InsertSessionGAPool :exec
INSERT INTO session_ga_pools (
    id, organization_id, session_id, source_pool_id, slug, display_name,
    physical_capacity, sellable_capacity, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
`

type InsertSessionGAPoolParams struct {
	ID               uuid.UUID `json:"id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	SessionID        uuid.UUID `json:"session_id"`
	SourcePoolID     uuid.UUID `json:"source_pool_id"`
	Slug             string    `json:"slug"`
	DisplayName      string    `json:"display_name"`
	PhysicalCapacity int64     `json:"physical_capacity"`
	SellableCapacity int64     `json:"sellable_capacity"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) InsertSessionGAPool(ctx context.Context, arg InsertSessionGAPoolParams) error {
	_, err := q.db.Exec(ctx, insertSessionGAPool,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.SourcePoolID,
		arg.Slug,
		arg.DisplayName,
		arg.PhysicalCapacity,
		arg.SellableCapacity,
		arg.CreatedAt,
	)
	return err
}

const insertSessionSeat = `-- name: InsertSessionSeat :exec
INSERT INTO session_seats (
    id, organization_id, session_id, seat_map_version_id, section_key, row_key,
    seat_key, label, category, sellable, wheelchair, companion_to, state,
    version, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 'available', 1, $13, $13)
`

type InsertSessionSeatParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	SeatMapVersionID uuid.UUID   `json:"seat_map_version_id"`
	SectionKey       string      `json:"section_key"`
	RowKey           string      `json:"row_key"`
	SeatKey          string      `json:"seat_key"`
	Label            string      `json:"label"`
	Category         string      `json:"category"`
	Sellable         bool        `json:"sellable"`
	Wheelchair       bool        `json:"wheelchair"`
	CompanionTo      pgtype.Text `json:"companion_to"`
	CreatedAt        time.Time   `json:"created_at"`
}

func (q *Queries) InsertSessionSeat(ctx context.Context, arg InsertSessionSeatParams) error {
	_, err := q.db.Exec(ctx, insertSessionSeat,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.SeatMapVersionID,
		arg.SectionKey,
		arg.RowKey,
		arg.SeatKey,
		arg.Label,
		arg.Category,
		arg.Sellable,
		arg.Wheelchair,
		arg.CompanionTo,
		arg.CreatedAt,
	)
	return err
}

const listActiveGAPoolTemplatesForSession = `-- name: ListActiveGAPoolTemplatesForSession :many
SELECT id, slug, display_name, physical_capacity, sellable_capacity
FROM ga_pool_templates
WHERE organization_id = $1 AND space_id = $2 AND status = 'active'
ORDER BY id ASC
FOR SHARE
`

type ListActiveGAPoolTemplatesForSessionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SpaceID        uuid.UUID `json:"space_id"`
}

type ListActiveGAPoolTemplatesForSessionRow struct {
	ID               uuid.UUID `json:"id"`
	Slug             string    `json:"slug"`
	DisplayName      string    `json:"display_name"`
	PhysicalCapacity int64     `json:"physical_capacity"`
	SellableCapacity int64     `json:"sellable_capacity"`
}

func (q *Queries) ListActiveGAPoolTemplatesForSession(ctx context.Context, arg ListActiveGAPoolTemplatesForSessionParams) ([]ListActiveGAPoolTemplatesForSessionRow, error) {
	rows, err := q.db.Query(ctx, listActiveGAPoolTemplatesForSession, arg.OrganizationID, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveGAPoolTemplatesForSessionRow{}
	for rows.Next() {
		var i ListActiveGAPoolTemplatesForSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.PhysicalCapacity,
			&i.SellableCapacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, organization_id, event_id, event_revision, venue_id, space_id, seat_map_version_id, inventory_mode, doors_at, starts_at, ends_at, sales_start_at, sales_end_at, timezone, status, version, created_at, updated_at, inventory_revision
FROM sessions
WHERE organization_id = $1 AND event_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListSessionsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.OrganizationID, arg.EventID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.EventRevision,
			&i.VenueID,
			&i.SpaceID,
			&i.SeatMapVersionID,
			&i.InventoryMode,
			&i.DoorsAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.SalesStartAt,
			&i.SalesEndAt,
			&i.Timezone,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InventoryRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsAfter = `-- name: ListSessionsAfter :many
SELECT id, organization_id, event_id, event_revision, venue_id, space_id, seat_map_version_id, inventory_mode, doors_at, starts_at, ends_at, sales_start_at, sales_end_at, timezone, status, version, created_at, updated_at, inventory_revision
FROM sessions
WHERE organization_id = $1 AND event_id = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSessionsAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	EventID         uuid.UUID `json:"event_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListSessionsAfter(ctx context.Context, arg ListSessionsAfterParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsAfter,
		arg.OrganizationID,
		arg.EventID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventID,
			&i.EventRevision,
			&i.VenueID,
			&i.SpaceID,
			&i.SeatMapVersionID,
			&i.InventoryMode,
			&i.DoorsAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.SalesStartAt,
			&i.SalesEndAt,
			&i.Timezone,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InventoryRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSpaceForSession = `-- name: LockSpaceForSession :one
SELECT id, venue_id, status, inventory_mode
FROM spaces
WHERE organization_id = $1 AND venue_id = $2 AND id = $3
FOR UPDATE
`

type LockSpaceForSessionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	VenueID        uuid.UUID `json:"venue_id"`
	ID             uuid.UUID `json:"id"`
}

type LockSpaceForSessionRow struct {
	ID            uuid.UUID `json:"id"`
	VenueID       uuid.UUID `json:"venue_id"`
	Status        string    `json:"status"`
	InventoryMode string    `json:"inventory_mode"`
}

func (q *Queries) LockSpaceForSession(ctx context.Context, arg LockSpaceForSessionParams) (LockSpaceForSessionRow, error) {
	row := q.db.QueryRow(ctx, lockSpaceForSession, arg.OrganizationID, arg.VenueID, arg.ID)
	var i LockSpaceForSessionRow
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Status,
		&i.InventoryMode,
	)
	return i, err
}

const sessionOverlap = `-- name: SessionOverlap :one
SELECT EXISTS (
    SELECT 1
    FROM sessions
    WHERE organization_id = $1
      AND venue_id = $2
      AND space_id = $3
      AND status NOT IN ('cancelled', 'completed')
      AND starts_at < $4::timestamptz
      AND ends_at > $5::timestamptz
) AS overlaps
`

type SessionOverlapParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	VenueID        uuid.UUID `json:"venue_id"`
	SpaceID        uuid.UUID `json:"space_id"`
	NewEndsAt      time.Time `json:"new_ends_at"`
	NewStartsAt    time.Time `json:"new_starts_at"`
}

func (q *Queries) SessionOverlap(ctx context.Context, arg SessionOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionOverlap,
		arg.OrganizationID,
		arg.VenueID,
		arg.SpaceID,
		arg.NewEndsAt,
		arg.NewStartsAt,
	)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}
