// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: key.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTicketByEntitlement = `-- name: GetTicketByEntitlement :one
SELECT id, organization_id, entitlement_id, order_line_id, session_id,
       public_reference, state, version, signing_key_id, not_before, expires_at,
       entry_opens_at, entry_closes_at, issued_at, admitted_at, void_at,
       refunded_at, expired_at, created_at, updated_at
FROM tickets
WHERE organization_id = $1
  AND entitlement_id = $2
`

type GetTicketByEntitlementParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EntitlementID  uuid.UUID `json:"entitlement_id"`
}

func (q *Queries) GetTicketByEntitlement(ctx context.Context, arg GetTicketByEntitlementParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByEntitlement, arg.OrganizationID, arg.EntitlementID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntitlementID,
		&i.OrderLineID,
		&i.SessionID,
		&i.PublicReference,
		&i.State,
		&i.Version,
		&i.SigningKeyID,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.EntryOpensAt,
		&i.EntryClosesAt,
		&i.IssuedAt,
		&i.AdmittedAt,
		&i.VoidAt,
		&i.RefundedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :one
INSERT INTO tickets (
    id, organization_id, entitlement_id, order_line_id, session_id,
    public_reference, state, version, signing_key_id, not_before, expires_at,
    entry_opens_at, entry_closes_at, issued_at, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16
)
RETURNING id, organization_id, entitlement_id, order_line_id, session_id,
          public_reference, state, version, signing_key_id, not_before,
          expires_at, entry_opens_at, entry_closes_at, issued_at, admitted_at,
          void_at, refunded_at, expired_at, created_at, updated_at
`

type InsertTicketParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	EntitlementID   uuid.UUID `json:"entitlement_id"`
	OrderLineID     uuid.UUID `json:"order_line_id"`
	SessionID       uuid.UUID `json:"session_id"`
	PublicReference string    `json:"public_reference"`
	State           string    `json:"state"`
	Version         int64     `json:"version"`
	SigningKeyID    string    `json:"signing_key_id"`
	NotBefore       time.Time `json:"not_before"`
	ExpiresAt       time.Time `json:"expires_at"`
	EntryOpensAt    time.Time `json:"entry_opens_at"`
	EntryClosesAt   time.Time `json:"entry_closes_at"`
	IssuedAt        time.Time `json:"issued_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, insertTicket,
		arg.ID,
		arg.OrganizationID,
		arg.EntitlementID,
		arg.OrderLineID,
		arg.SessionID,
		arg.PublicReference,
		arg.State,
		arg.Version,
		arg.SigningKeyID,
		arg.NotBefore,
		arg.ExpiresAt,
		arg.EntryOpensAt,
		arg.EntryClosesAt,
		arg.IssuedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntitlementID,
		&i.OrderLineID,
		&i.SessionID,
		&i.PublicReference,
		&i.State,
		&i.Version,
		&i.SigningKeyID,
		&i.NotBefore,
		&i.ExpiresAt,
		&i.EntryOpensAt,
		&i.EntryClosesAt,
		&i.IssuedAt,
		&i.AdmittedAt,
		&i.VoidAt,
		&i.RefundedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockEntitlementForIssue = `-- name: LockEntitlementForIssue :one
SELECT id, organization_id, order_line_id, session_id, unit_number, state
FROM entitlements
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockEntitlementForIssueParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EntitlementID  uuid.UUID `json:"entitlement_id"`
}

type LockEntitlementForIssueRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	OrderLineID    uuid.UUID `json:"order_line_id"`
	SessionID      uuid.UUID `json:"session_id"`
	UnitNumber     int32     `json:"unit_number"`
	State          string    `json:"state"`
}

func (q *Queries) LockEntitlementForIssue(ctx context.Context, arg LockEntitlementForIssueParams) (LockEntitlementForIssueRow, error) {
	row := q.db.QueryRow(ctx, lockEntitlementForIssue, arg.OrganizationID, arg.EntitlementID)
	var i LockEntitlementForIssueRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderLineID,
		&i.SessionID,
		&i.UnitNumber,
		&i.State,
	)
	return i, err
}

const markEntitlementIssued = `-- name: MarkEntitlementIssued :one
UPDATE entitlements
SET state = 'issued', updated_at = $1
WHERE organization_id = $2
  AND id = $3
  AND state = 'pending'
RETURNING id, organization_id, order_line_id, session_id, unit_number, state
`

type MarkEntitlementIssuedParams struct {
	UpdatedAt      time.Time `json:"updated_at"`
	OrganizationID uuid.UUID `json:"organization_id"`
	EntitlementID  uuid.UUID `json:"entitlement_id"`
}

type MarkEntitlementIssuedRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	OrderLineID    uuid.UUID `json:"order_line_id"`
	SessionID      uuid.UUID `json:"session_id"`
	UnitNumber     int32     `json:"unit_number"`
	State          string    `json:"state"`
}

func (q *Queries) MarkEntitlementIssued(ctx context.Context, arg MarkEntitlementIssuedParams) (MarkEntitlementIssuedRow, error) {
	row := q.db.QueryRow(ctx, markEntitlementIssued, arg.UpdatedAt, arg.OrganizationID, arg.EntitlementID)
	var i MarkEntitlementIssuedRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderLineID,
		&i.SessionID,
		&i.UnitNumber,
		&i.State,
	)
	return i, err
}

const resolveTicketKey = `-- name: ResolveTicketKey :one
SELECT public_key, state
FROM ticket_signing_keys
WHERE key_id = $1
`

type ResolveTicketKeyRow struct {
	PublicKey []byte `json:"public_key"`
	State     string `json:"state"`
}

func (q *Queries) ResolveTicketKey(ctx context.Context, keyID string) (ResolveTicketKeyRow, error) {
	row := q.db.QueryRow(ctx, resolveTicketKey, keyID)
	var i ResolveTicketKeyRow
	err := row.Scan(&i.PublicKey, &i.State)
	return i, err
}
