// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetTicketByEntitlement(ctx context.Context, arg GetTicketByEntitlementParams) (Ticket, error)
	InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error)
	LockEntitlementForIssue(ctx context.Context, arg LockEntitlementForIssueParams) (LockEntitlementForIssueRow, error)
	MarkEntitlementIssued(ctx context.Context, arg MarkEntitlementIssuedParams) (MarkEntitlementIssuedRow, error)
	ResolveTicketKey(ctx context.Context, keyID string) (ResolveTicketKeyRow, error)
}

var _ Querier = (*Queries)(nil)
