// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cloneEventDraft = `-- name: CloneEventDraft :one
INSERT INTO event_revisions (id, organization_id, event_id, revision, status, title, short_description, long_description, checksum, version, created_at, updated_at)
SELECT $1, source.organization_id, source.event_id, 0, 'draft', source.title, source.short_description, source.long_description, source.checksum, 1, $4, $4
FROM event_revisions AS source
JOIN events AS e ON e.organization_id = source.organization_id AND e.id = source.event_id AND e.current_revision = source.revision
WHERE source.organization_id = $2 AND source.event_id = $3 AND source.status IN ('published', 'retired')
RETURNING id
`

type CloneEventDraftParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) CloneEventDraft(ctx context.Context, arg CloneEventDraftParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, cloneEventDraft,
		arg.ID,
		arg.OrganizationID,
		arg.EventID,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDraftRevisionForUpdate = `-- name: GetDraftRevisionForUpdate :one
SELECT id, version
FROM event_revisions
WHERE organization_id = $1 AND event_id = $2 AND revision = 0 AND status = 'draft'
FOR UPDATE
`

type GetDraftRevisionForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
}

type GetDraftRevisionForUpdateRow struct {
	ID      uuid.UUID `json:"id"`
	Version int64     `json:"version"`
}

func (q *Queries) GetDraftRevisionForUpdate(ctx context.Context, arg GetDraftRevisionForUpdateParams) (GetDraftRevisionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getDraftRevisionForUpdate, arg.OrganizationID, arg.EventID)
	var i GetDraftRevisionForUpdateRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const getEventForUpdate = `-- name: GetEventForUpdate :one
SELECT id, organization_id, slug, status, current_revision, version, created_at, updated_at
FROM events
WHERE organization_id = $1 AND id = $2
FOR UPDATE
`

type GetEventForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetEventForUpdate(ctx context.Context, arg GetEventForUpdateParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForUpdate, arg.OrganizationID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Status,
		&i.CurrentRevision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventProjection = `-- name: GetEventProjection :one
SELECT e.id, e.organization_id, e.slug, e.status, e.current_revision, e.version, e.created_at, e.updated_at,
       COALESCE(r.title, '') AS title,
       COALESCE(r.short_description, '') AS short_description,
       COALESCE(r.long_description, '') AS long_description,
       COALESCE(r.checksum, ''::bytea) AS checksum,
       r.published_at
FROM events AS e
LEFT JOIN event_revisions AS r
  ON r.organization_id = e.organization_id AND r.event_id = e.id AND r.revision = e.current_revision
WHERE e.organization_id = $1 AND e.id = $2
`

type GetEventProjectionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetEventProjectionRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Slug             string             `json:"slug"`
	Status           string             `json:"status"`
	CurrentRevision  int64              `json:"current_revision"`
	Version          int64              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	Title            string             `json:"title"`
	ShortDescription string             `json:"short_description"`
	LongDescription  string             `json:"long_description"`
	Checksum         []byte             `json:"checksum"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetEventProjection(ctx context.Context, arg GetEventProjectionParams) (GetEventProjectionRow, error) {
	row := q.db.QueryRow(ctx, getEventProjection, arg.OrganizationID, arg.ID)
	var i GetEventProjectionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Status,
		&i.CurrentRevision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ShortDescription,
		&i.LongDescription,
		&i.Checksum,
		&i.PublishedAt,
	)
	return i, err
}

const incrementEventVersion = `-- name: IncrementEventVersion :exec
UPDATE events
SET version = version + 1, updated_at = $3
WHERE organization_id = $1 AND id = $2
`

type IncrementEventVersionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) IncrementEventVersion(ctx context.Context, arg IncrementEventVersionParams) error {
	_, err := q.db.Exec(ctx, incrementEventVersion, arg.OrganizationID, arg.ID, arg.UpdatedAt)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (id, organization_id, slug, status, current_revision, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, organization_id, slug, status, current_revision, version, created_at, updated_at
`

type InsertEventParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	Slug            string    `json:"slug"`
	Status          string    `json:"status"`
	CurrentRevision int64     `json:"current_revision"`
	Version         int64     `json:"version"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.OrganizationID,
		arg.Slug,
		arg.Status,
		arg.CurrentRevision,
		arg.Version,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Status,
		&i.CurrentRevision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEventRevision = `-- name: InsertEventRevision :one
INSERT INTO event_revisions (id, organization_id, event_id, revision, status, title, short_description, long_description, checksum, version, created_at, updated_at)
VALUES ($1, $2, $3, 0, 'draft', $4, $5, $6, $7, 1, $8, $8)
RETURNING id
`

type InsertEventRevisionParams struct {
	ID               uuid.UUID `json:"id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	EventID          uuid.UUID `json:"event_id"`
	Title            string    `json:"title"`
	ShortDescription string    `json:"short_description"`
	LongDescription  string    `json:"long_description"`
	Checksum         []byte    `json:"checksum"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) InsertEventRevision(ctx context.Context, arg InsertEventRevisionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertEventRevision,
		arg.ID,
		arg.OrganizationID,
		arg.EventID,
		arg.Title,
		arg.ShortDescription,
		arg.LongDescription,
		arg.Checksum,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.organization_id, e.slug, e.status, e.current_revision, e.version, e.created_at, e.updated_at,
       COALESCE(r.title, '') AS title,
       COALESCE(r.short_description, '') AS short_description,
       COALESCE(r.long_description, '') AS long_description,
       COALESCE(r.checksum, ''::bytea) AS checksum,
       r.published_at
FROM events AS e
LEFT JOIN event_revisions AS r
  ON r.organization_id = e.organization_id AND r.event_id = e.id AND r.revision = e.current_revision
WHERE e.organization_id = $1
ORDER BY e.created_at DESC, e.id DESC
LIMIT $2
`

type ListEventsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
}

type ListEventsRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Slug             string             `json:"slug"`
	Status           string             `json:"status"`
	CurrentRevision  int64              `json:"current_revision"`
	Version          int64              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	Title            string             `json:"title"`
	ShortDescription string             `json:"short_description"`
	LongDescription  string             `json:"long_description"`
	Checksum         []byte             `json:"checksum"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.Status,
			&i.CurrentRevision,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.ShortDescription,
			&i.LongDescription,
			&i.Checksum,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT e.id, e.organization_id, e.slug, e.status, e.current_revision, e.version, e.created_at, e.updated_at,
       COALESCE(r.title, '') AS title,
       COALESCE(r.short_description, '') AS short_description,
       COALESCE(r.long_description, '') AS long_description,
       COALESCE(r.checksum, ''::bytea) AS checksum,
       r.published_at
FROM events AS e
LEFT JOIN event_revisions AS r
  ON r.organization_id = e.organization_id AND r.event_id = e.id AND r.revision = e.current_revision
WHERE e.organization_id = $1
  AND (e.created_at, e.id) < ($2::timestamptz, $3::uuid)
ORDER BY e.created_at DESC, e.id DESC
LIMIT $4
`

type ListEventsAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

type ListEventsAfterRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Slug             string             `json:"slug"`
	Status           string             `json:"status"`
	CurrentRevision  int64              `json:"current_revision"`
	Version          int64              `json:"version"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	Title            string             `json:"title"`
	ShortDescription string             `json:"short_description"`
	LongDescription  string             `json:"long_description"`
	Checksum         []byte             `json:"checksum"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]ListEventsAfterRow, error) {
	rows, err := q.db.Query(ctx, listEventsAfter,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsAfterRow{}
	for rows.Next() {
		var i ListEventsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.Status,
			&i.CurrentRevision,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.ShortDescription,
			&i.LongDescription,
			&i.Checksum,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEventRevision = `-- name: NextEventRevision :one
SELECT COALESCE(MAX(revision), 0)::bigint + 1 AS next_revision
FROM event_revisions
WHERE organization_id = $1 AND event_id = $2
`

type NextEventRevisionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
}

func (q *Queries) NextEventRevision(ctx context.Context, arg NextEventRevisionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextEventRevision, arg.OrganizationID, arg.EventID)
	var next_revision int32
	err := row.Scan(&next_revision)
	return next_revision, err
}

const publishEventAggregate = `-- name: PublishEventAggregate :exec
UPDATE events
SET status = 'published', current_revision = $3, version = version + 1, updated_at = $4
WHERE organization_id = $1 AND id = $2 AND version = $5
`

type PublishEventAggregateParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	ID              uuid.UUID `json:"id"`
	CurrentRevision int64     `json:"current_revision"`
	UpdatedAt       time.Time `json:"updated_at"`
	Version         int64     `json:"version"`
}

func (q *Queries) PublishEventAggregate(ctx context.Context, arg PublishEventAggregateParams) error {
	_, err := q.db.Exec(ctx, publishEventAggregate,
		arg.OrganizationID,
		arg.ID,
		arg.CurrentRevision,
		arg.UpdatedAt,
		arg.Version,
	)
	return err
}

const publishEventRevision = `-- name: PublishEventRevision :exec
UPDATE event_revisions
SET status = 'published', revision = $3, published_at = $4, version = version + 1, updated_at = $4
WHERE organization_id = $1 AND event_id = $2 AND revision = 0 AND status = 'draft' AND version = $5
`

type PublishEventRevisionParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	EventID        uuid.UUID          `json:"event_id"`
	Revision       int64              `json:"revision"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	Version        int64              `json:"version"`
}

func (q *Queries) PublishEventRevision(ctx context.Context, arg PublishEventRevisionParams) error {
	_, err := q.db.Exec(ctx, publishEventRevision,
		arg.OrganizationID,
		arg.EventID,
		arg.Revision,
		arg.PublishedAt,
		arg.Version,
	)
	return err
}

const retirePublishedEventRevisions = `-- name: RetirePublishedEventRevisions :exec
UPDATE event_revisions
SET status = 'retired', updated_at = $3
WHERE organization_id = $1 AND event_id = $2 AND status = 'published'
`

type RetirePublishedEventRevisionsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) RetirePublishedEventRevisions(ctx context.Context, arg RetirePublishedEventRevisionsParams) error {
	_, err := q.db.Exec(ctx, retirePublishedEventRevisions, arg.OrganizationID, arg.EventID, arg.UpdatedAt)
	return err
}

const updateEventDraftRevision = `-- name: UpdateEventDraftRevision :exec
UPDATE event_revisions
SET title = $3, short_description = $4, long_description = $5, checksum = $6, version = version + 1, updated_at = $7
WHERE organization_id = $1 AND event_id = $2 AND revision = 0 AND status = 'draft' AND version = $8
`

type UpdateEventDraftRevisionParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	EventID          uuid.UUID `json:"event_id"`
	Title            string    `json:"title"`
	ShortDescription string    `json:"short_description"`
	LongDescription  string    `json:"long_description"`
	Checksum         []byte    `json:"checksum"`
	UpdatedAt        time.Time `json:"updated_at"`
	Version          int64     `json:"version"`
}

func (q *Queries) UpdateEventDraftRevision(ctx context.Context, arg UpdateEventDraftRevisionParams) error {
	_, err := q.db.Exec(ctx, updateEventDraftRevision,
		arg.OrganizationID,
		arg.EventID,
		arg.Title,
		arg.ShortDescription,
		arg.LongDescription,
		arg.Checksum,
		arg.UpdatedAt,
		arg.Version,
	)
	return err
}

const updateEventIdentity = `-- name: UpdateEventIdentity :one
UPDATE events
SET slug = $3, version = version + 1, updated_at = $4
WHERE organization_id = $1 AND id = $2 AND status NOT IN ('cancelled', 'archived') AND version = $5
RETURNING id, organization_id, slug, status, current_revision, version, created_at, updated_at
`

type UpdateEventIdentityParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	UpdatedAt      time.Time `json:"updated_at"`
	Version        int64     `json:"version"`
}

func (q *Queries) UpdateEventIdentity(ctx context.Context, arg UpdateEventIdentityParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventIdentity,
		arg.OrganizationID,
		arg.ID,
		arg.Slug,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Status,
		&i.CurrentRevision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
