// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CloneEventDraft(ctx context.Context, arg CloneEventDraftParams) (uuid.UUID, error)
	GetDraftRevisionForUpdate(ctx context.Context, arg GetDraftRevisionForUpdateParams) (GetDraftRevisionForUpdateRow, error)
	GetEventForUpdate(ctx context.Context, arg GetEventForUpdateParams) (Event, error)
	GetEventProjection(ctx context.Context, arg GetEventProjectionParams) (GetEventProjectionRow, error)
	IncrementEventVersion(ctx context.Context, arg IncrementEventVersionParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertEventRevision(ctx context.Context, arg InsertEventRevisionParams) (uuid.UUID, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]ListEventsAfterRow, error)
	NextEventRevision(ctx context.Context, arg NextEventRevisionParams) (int32, error)
	PublishEventAggregate(ctx context.Context, arg PublishEventAggregateParams) error
	PublishEventRevision(ctx context.Context, arg PublishEventRevisionParams) error
	RetirePublishedEventRevisions(ctx context.Context, arg RetirePublishedEventRevisionsParams) error
	UpdateEventDraftRevision(ctx context.Context, arg UpdateEventDraftRevisionParams) error
	UpdateEventIdentity(ctx context.Context, arg UpdateEventIdentityParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
