// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveOwners = `-- name: CountActiveOwners :one
SELECT count(*)::bigint
FROM memberships
WHERE organization_id = $1 AND status = 'active' AND role = 'owner'
`

func (q *Queries) CountActiveOwners(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOwners, organizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getMembershipForUpdate = `-- name: GetMembershipForUpdate :one
SELECT id, organization_id, user_id, role, status, venue_scope, version,
       created_at, updated_at, revoked_at
FROM memberships
WHERE organization_id = $1 AND id = $2
FOR UPDATE
`

type GetMembershipForUpdateParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetMembershipForUpdate(ctx context.Context, arg GetMembershipForUpdateParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipForUpdate, arg.OrganizationID, arg.ID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.VenueScope,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT id, organization_id, user_id, role, status, venue_scope, version,
       created_at, updated_at, revoked_at
FROM memberships
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListMembershipsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListMemberships(ctx context.Context, arg ListMembershipsParams) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMemberships, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.VenueScope,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsAfter = `-- name: ListMembershipsAfter :many
SELECT id, organization_id, user_id, role, status, venue_scope, version,
       created_at, updated_at, revoked_at
FROM memberships
WHERE organization_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMembershipsAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListMembershipsAfter(ctx context.Context, arg ListMembershipsAfterParams) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsAfter,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.VenueScope,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganization = `-- name: LockOrganization :one
SELECT id
FROM organizations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockOrganization(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockOrganization, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const revokeMembership = `-- name: RevokeMembership :one
UPDATE memberships
SET status = 'revoked', version = version + 1, updated_at = $4, revoked_at = $4
WHERE organization_id = $1 AND id = $2 AND status = 'active' AND version = $3
RETURNING id, organization_id, user_id, role, status, venue_scope, version,
          created_at, updated_at, revoked_at
`

type RevokeMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	Version        int64     `json:"version"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) RevokeMembership(ctx context.Context, arg RevokeMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, revokeMembership,
		arg.OrganizationID,
		arg.ID,
		arg.Version,
		arg.UpdatedAt,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.VenueScope,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships
SET role = $4, version = version + 1, updated_at = $5
WHERE organization_id = $1 AND id = $2 AND status = 'active' AND version = $3
RETURNING id, organization_id, user_id, role, status, venue_scope, version,
          created_at, updated_at, revoked_at
`

type UpdateMembershipRoleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	Version        int64     `json:"version"`
	Role           string    `json:"role"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole,
		arg.OrganizationID,
		arg.ID,
		arg.Version,
		arg.Role,
		arg.UpdatedAt,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.VenueScope,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}
