// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveOwners(ctx context.Context, organizationID uuid.UUID) (int64, error)
	GetMembershipForUpdate(ctx context.Context, arg GetMembershipForUpdateParams) (Membership, error)
	ListMemberships(ctx context.Context, arg ListMembershipsParams) ([]Membership, error)
	ListMembershipsAfter(ctx context.Context, arg ListMembershipsAfterParams) ([]Membership, error)
	LockOrganization(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	RevokeMembership(ctx context.Context, arg RevokeMembershipParams) (Membership, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error)
}

var _ Querier = (*Queries)(nil)
