// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionPriceCurrency = `-- name: GetSessionPriceCurrency :one
SELECT currency
FROM price_tiers
WHERE organization_id = $1 AND session_id = $2
ORDER BY created_at ASC, id ASC
LIMIT 1
`

type GetSessionPriceCurrencyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

func (q *Queries) GetSessionPriceCurrency(ctx context.Context, arg GetSessionPriceCurrencyParams) (string, error) {
	row := q.db.QueryRow(ctx, getSessionPriceCurrency, arg.OrganizationID, arg.SessionID)
	var currency string
	err := row.Scan(&currency)
	return currency, err
}

const insertPriceTier = `-- name: InsertPriceTier :one
INSERT INTO price_tiers (id, organization_id, session_id, slug, display_name, currency, amount_minor, minimum_quantity, maximum_quantity, sales_start_at, sales_end_at, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $14)
RETURNING id, organization_id, session_id, slug, display_name, currency, amount_minor, minimum_quantity, maximum_quantity, sales_start_at, sales_end_at, status, version, created_at, updated_at
`

type InsertPriceTierParams struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	SessionID       uuid.UUID          `json:"session_id"`
	Slug            string             `json:"slug"`
	DisplayName     string             `json:"display_name"`
	Currency        string             `json:"currency"`
	AmountMinor     int64              `json:"amount_minor"`
	MinimumQuantity int32              `json:"minimum_quantity"`
	MaximumQuantity int32              `json:"maximum_quantity"`
	SalesStartAt    pgtype.Timestamptz `json:"sales_start_at"`
	SalesEndAt      pgtype.Timestamptz `json:"sales_end_at"`
	Status          string             `json:"status"`
	Version         int64              `json:"version"`
	CreatedAt       time.Time          `json:"created_at"`
}

func (q *Queries) InsertPriceTier(ctx context.Context, arg InsertPriceTierParams) (PriceTier, error) {
	row := q.db.QueryRow(ctx, insertPriceTier,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.Slug,
		arg.DisplayName,
		arg.Currency,
		arg.AmountMinor,
		arg.MinimumQuantity,
		arg.MaximumQuantity,
		arg.SalesStartAt,
		arg.SalesEndAt,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
	)
	var i PriceTier
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.Slug,
		&i.DisplayName,
		&i.Currency,
		&i.AmountMinor,
		&i.MinimumQuantity,
		&i.MaximumQuantity,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPriceTiers = `-- name: ListPriceTiers :many
SELECT id, organization_id, session_id, slug, display_name, currency, amount_minor, minimum_quantity, maximum_quantity, sales_start_at, sales_end_at, status, version, created_at, updated_at
FROM price_tiers
WHERE organization_id = $1 AND session_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListPriceTiersParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListPriceTiers(ctx context.Context, arg ListPriceTiersParams) ([]PriceTier, error) {
	rows, err := q.db.Query(ctx, listPriceTiers, arg.OrganizationID, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceTier{}
	for rows.Next() {
		var i PriceTier
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.Slug,
			&i.DisplayName,
			&i.Currency,
			&i.AmountMinor,
			&i.MinimumQuantity,
			&i.MaximumQuantity,
			&i.SalesStartAt,
			&i.SalesEndAt,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTiersAfter = `-- name: ListPriceTiersAfter :many
SELECT id, organization_id, session_id, slug, display_name, currency, amount_minor, minimum_quantity, maximum_quantity, sales_start_at, sales_end_at, status, version, created_at, updated_at
FROM price_tiers
WHERE organization_id = $1 AND session_id = $2
  AND (created_at, id) < ($3::timestamptz, $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListPriceTiersAfterParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	SessionID       uuid.UUID `json:"session_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	PageLimit       int32     `json:"page_limit"`
}

func (q *Queries) ListPriceTiersAfter(ctx context.Context, arg ListPriceTiersAfterParams) ([]PriceTier, error) {
	rows, err := q.db.Query(ctx, listPriceTiersAfter,
		arg.OrganizationID,
		arg.SessionID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceTier{}
	for rows.Next() {
		var i PriceTier
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.Slug,
			&i.DisplayName,
			&i.Currency,
			&i.AmountMinor,
			&i.MinimumQuantity,
			&i.MaximumQuantity,
			&i.SalesStartAt,
			&i.SalesEndAt,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionForPricing = `-- name: LockSessionForPricing :one
SELECT id, status
FROM sessions
WHERE organization_id = $1 AND event_id = $2 AND id = $3
FOR UPDATE
`

type LockSessionForPricingParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EventID        uuid.UUID `json:"event_id"`
	ID             uuid.UUID `json:"id"`
}

type LockSessionForPricingRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) LockSessionForPricing(ctx context.Context, arg LockSessionForPricingParams) (LockSessionForPricingRow, error) {
	row := q.db.QueryRow(ctx, lockSessionForPricing, arg.OrganizationID, arg.EventID, arg.ID)
	var i LockSessionForPricingRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}
