// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetSessionPriceCurrency(ctx context.Context, arg GetSessionPriceCurrencyParams) (string, error)
	InsertPriceTier(ctx context.Context, arg InsertPriceTierParams) (PriceTier, error)
	ListPriceTiers(ctx context.Context, arg ListPriceTiersParams) ([]PriceTier, error)
	ListPriceTiersAfter(ctx context.Context, arg ListPriceTiersAfterParams) ([]PriceTier, error)
	LockSessionForPricing(ctx context.Context, arg LockSessionForPricingParams) (LockSessionForPricingRow, error)
}

var _ Querier = (*Queries)(nil)
