// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now()::timestamptz
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const getEntrySummaryMeta = `-- name: GetEntrySummaryMeta :one
SELECT now()::timestamptz AS generated_at,
       COUNT(scan.id)::bigint AS scan_count
FROM sessions AS session
LEFT JOIN scan_attempts AS scan
  ON scan.organization_id = session.organization_id
 AND scan.session_id = session.id
 AND scan.scanned_at >= $1
 AND scan.scanned_at < $2
WHERE session.organization_id = $3
  AND session.id = $4
`

type GetEntrySummaryMetaParams struct {
	FromTime       time.Time `json:"from_time"`
	UntilTime      time.Time `json:"until_time"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

type GetEntrySummaryMetaRow struct {
	GeneratedAt time.Time `json:"generated_at"`
	ScanCount   int64     `json:"scan_count"`
}

func (q *Queries) GetEntrySummaryMeta(ctx context.Context, arg GetEntrySummaryMetaParams) (GetEntrySummaryMetaRow, error) {
	row := q.db.QueryRow(ctx, getEntrySummaryMeta,
		arg.FromTime,
		arg.UntilTime,
		arg.OrganizationID,
		arg.SessionID,
	)
	var i GetEntrySummaryMetaRow
	err := row.Scan(&i.GeneratedAt, &i.ScanCount)
	return i, err
}

const getLatestEntryReceivedAt = `-- name: GetLatestEntryReceivedAt :one
SELECT scan.received_at
FROM scan_attempts AS scan
WHERE scan.organization_id = $1
  AND scan.session_id = $2
  AND scan.scanned_at >= $3
  AND scan.scanned_at < $4
ORDER BY scan.received_at DESC, scan.id DESC
LIMIT 1
`

type GetLatestEntryReceivedAtParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	FromTime       time.Time `json:"from_time"`
	UntilTime      time.Time `json:"until_time"`
}

func (q *Queries) GetLatestEntryReceivedAt(ctx context.Context, arg GetLatestEntryReceivedAtParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLatestEntryReceivedAt,
		arg.OrganizationID,
		arg.SessionID,
		arg.FromTime,
		arg.UntilTime,
	)
	var received_at time.Time
	err := row.Scan(&received_at)
	return received_at, err
}

const getScanAttemptByDeviceKey = `-- name: GetScanAttemptByDeviceKey :one
SELECT id, organization_id, session_id, ticket_id, device_id, device_scan_id,
       ticket_version, result, mode, credential_sha256, gate_id, scanned_at,
       received_at, metadata
FROM scan_attempts
WHERE organization_id = $1
  AND device_id = $2
  AND device_scan_id = $3
`

type GetScanAttemptByDeviceKeyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	DeviceID       uuid.UUID `json:"device_id"`
	DeviceScanID   string    `json:"device_scan_id"`
}

func (q *Queries) GetScanAttemptByDeviceKey(ctx context.Context, arg GetScanAttemptByDeviceKeyParams) (ScanAttempt, error) {
	row := q.db.QueryRow(ctx, getScanAttemptByDeviceKey, arg.OrganizationID, arg.DeviceID, arg.DeviceScanID)
	var i ScanAttempt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.TicketID,
		&i.DeviceID,
		&i.DeviceScanID,
		&i.TicketVersion,
		&i.Result,
		&i.Mode,
		&i.CredentialSha256,
		&i.GateID,
		&i.ScannedAt,
		&i.ReceivedAt,
		&i.Metadata,
	)
	return i, err
}

const insertAdmission = `-- name: InsertAdmission :exec
INSERT INTO admissions (
    id, organization_id, ticket_id, scan_attempt_id, session_id, device_id,
    gate_id, admitted_at, override_actor_id, override_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAdmissionParams struct {
	ID              uuid.UUID   `json:"id"`
	OrganizationID  uuid.UUID   `json:"organization_id"`
	TicketID        uuid.UUID   `json:"ticket_id"`
	ScanAttemptID   uuid.UUID   `json:"scan_attempt_id"`
	SessionID       uuid.UUID   `json:"session_id"`
	DeviceID        uuid.UUID   `json:"device_id"`
	GateID          pgtype.UUID `json:"gate_id"`
	AdmittedAt      time.Time   `json:"admitted_at"`
	OverrideActorID pgtype.Text `json:"override_actor_id"`
	OverrideReason  pgtype.Text `json:"override_reason"`
}

func (q *Queries) InsertAdmission(ctx context.Context, arg InsertAdmissionParams) error {
	_, err := q.db.Exec(ctx, insertAdmission,
		arg.ID,
		arg.OrganizationID,
		arg.TicketID,
		arg.ScanAttemptID,
		arg.SessionID,
		arg.DeviceID,
		arg.GateID,
		arg.AdmittedAt,
		arg.OverrideActorID,
		arg.OverrideReason,
	)
	return err
}

const insertScanAttempt = `-- name: InsertScanAttempt :one
INSERT INTO scan_attempts (
    id, organization_id, session_id, ticket_id, device_id, device_scan_id,
    ticket_version, result, mode, credential_sha256, gate_id, scanned_at,
    received_at, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'online', $9, $10, $11, $11, $12)
RETURNING id, organization_id, session_id, ticket_id, device_id, device_scan_id,
          ticket_version, result, mode, credential_sha256, gate_id, scanned_at,
          received_at, metadata
`

type InsertScanAttemptParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	TicketID         uuid.UUID   `json:"ticket_id"`
	DeviceID         uuid.UUID   `json:"device_id"`
	DeviceScanID     string      `json:"device_scan_id"`
	TicketVersion    int64       `json:"ticket_version"`
	Result           string      `json:"result"`
	CredentialSha256 []byte      `json:"credential_sha256"`
	GateID           pgtype.UUID `json:"gate_id"`
	ScannedAt        time.Time   `json:"scanned_at"`
	Metadata         []byte      `json:"metadata"`
}

func (q *Queries) InsertScanAttempt(ctx context.Context, arg InsertScanAttemptParams) (ScanAttempt, error) {
	row := q.db.QueryRow(ctx, insertScanAttempt,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.TicketID,
		arg.DeviceID,
		arg.DeviceScanID,
		arg.TicketVersion,
		arg.Result,
		arg.CredentialSha256,
		arg.GateID,
		arg.ScannedAt,
		arg.Metadata,
	)
	var i ScanAttempt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.TicketID,
		&i.DeviceID,
		&i.DeviceScanID,
		&i.TicketVersion,
		&i.Result,
		&i.Mode,
		&i.CredentialSha256,
		&i.GateID,
		&i.ScannedAt,
		&i.ReceivedAt,
		&i.Metadata,
	)
	return i, err
}

const isDeviceAuthorizedForScan = `-- name: IsDeviceAuthorizedForScan :one
SELECT EXISTS (
    SELECT 1
    FROM device_assignments AS assignment
    WHERE assignment.organization_id = $1
      AND assignment.device_id = $2
      AND assignment.capability = 'entry.scan'
      AND assignment.state = 'active'
      AND assignment.valid_from <= $3
      AND (assignment.valid_until IS NULL OR assignment.valid_until > $3)
      AND (assignment.session_id IS NULL OR assignment.session_id = $4)
      AND (
          assignment.gate_id IS NULL
          OR ($5::uuid IS NOT NULL AND assignment.gate_id = $5::uuid)
      )
) AS authorized
`

type IsDeviceAuthorizedForScanParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	DeviceID       uuid.UUID   `json:"device_id"`
	AtTime         time.Time   `json:"at_time"`
	SessionID      pgtype.UUID `json:"session_id"`
	GateID         pgtype.UUID `json:"gate_id"`
}

func (q *Queries) IsDeviceAuthorizedForScan(ctx context.Context, arg IsDeviceAuthorizedForScanParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDeviceAuthorizedForScan,
		arg.OrganizationID,
		arg.DeviceID,
		arg.AtTime,
		arg.SessionID,
		arg.GateID,
	)
	var authorized bool
	err := row.Scan(&authorized)
	return authorized, err
}

const listEntrySummaryRows = `-- name: ListEntrySummaryRows :many
SELECT scan.result,
       scan.gate_id,
       date_trunc('minute', scan.scanned_at)::timestamptz AS minute,
       order_line.price_tier_id,
       COUNT(*)::bigint AS scan_count
FROM scan_attempts AS scan
JOIN tickets AS ticket
  ON ticket.organization_id = scan.organization_id
 AND ticket.id = scan.ticket_id
JOIN entitlements AS entitlement
  ON entitlement.organization_id = ticket.organization_id
 AND entitlement.id = ticket.entitlement_id
JOIN order_lines AS order_line
  ON order_line.organization_id = entitlement.organization_id
 AND order_line.id = entitlement.order_line_id
WHERE scan.organization_id = $1
  AND scan.session_id = $2
  AND scan.scanned_at >= $3
  AND scan.scanned_at < $4
GROUP BY scan.result, scan.gate_id, date_trunc('minute', scan.scanned_at), order_line.price_tier_id
ORDER BY minute ASC, scan.result ASC, scan.gate_id ASC NULLS FIRST, order_line.price_tier_id ASC
`

type ListEntrySummaryRowsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	FromTime       time.Time `json:"from_time"`
	UntilTime      time.Time `json:"until_time"`
}

type ListEntrySummaryRowsRow struct {
	Result      string      `json:"result"`
	GateID      pgtype.UUID `json:"gate_id"`
	Minute      time.Time   `json:"minute"`
	PriceTierID uuid.UUID   `json:"price_tier_id"`
	ScanCount   int64       `json:"scan_count"`
}

func (q *Queries) ListEntrySummaryRows(ctx context.Context, arg ListEntrySummaryRowsParams) ([]ListEntrySummaryRowsRow, error) {
	rows, err := q.db.Query(ctx, listEntrySummaryRows,
		arg.OrganizationID,
		arg.SessionID,
		arg.FromTime,
		arg.UntilTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntrySummaryRowsRow{}
	for rows.Next() {
		var i ListEntrySummaryRowsRow
		if err := rows.Scan(
			&i.Result,
			&i.GateID,
			&i.Minute,
			&i.PriceTierID,
			&i.ScanCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeviceForScan = `-- name: LockDeviceForScan :one
SELECT id, organization_id, state
FROM devices
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockDeviceForScanParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockDeviceForScanRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	State          string    `json:"state"`
}

func (q *Queries) LockDeviceForScan(ctx context.Context, arg LockDeviceForScanParams) (LockDeviceForScanRow, error) {
	row := q.db.QueryRow(ctx, lockDeviceForScan, arg.OrganizationID, arg.ID)
	var i LockDeviceForScanRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.State)
	return i, err
}

const lockTicketForScan = `-- name: LockTicketForScan :one
SELECT id, organization_id, session_id, state, version, entry_opens_at,
       entry_closes_at, admitted_at
FROM tickets
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockTicketForScanParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockTicketForScanRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	SessionID      uuid.UUID          `json:"session_id"`
	State          string             `json:"state"`
	Version        int64              `json:"version"`
	EntryOpensAt   time.Time          `json:"entry_opens_at"`
	EntryClosesAt  time.Time          `json:"entry_closes_at"`
	AdmittedAt     pgtype.Timestamptz `json:"admitted_at"`
}

func (q *Queries) LockTicketForScan(ctx context.Context, arg LockTicketForScanParams) (LockTicketForScanRow, error) {
	row := q.db.QueryRow(ctx, lockTicketForScan, arg.OrganizationID, arg.ID)
	var i LockTicketForScanRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.State,
		&i.Version,
		&i.EntryOpensAt,
		&i.EntryClosesAt,
		&i.AdmittedAt,
	)
	return i, err
}

const markTicketAdmitted = `-- name: MarkTicketAdmitted :one
UPDATE tickets
SET state = 'admitted', version = version + 1, admitted_at = $3, updated_at = $3
WHERE organization_id = $1
  AND id = $2
  AND state = 'valid'
  AND version = $4
RETURNING id, organization_id, session_id, state, version, entry_opens_at,
          entry_closes_at, admitted_at
`

type MarkTicketAdmittedParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ID             uuid.UUID          `json:"id"`
	AdmittedAt     pgtype.Timestamptz `json:"admitted_at"`
	Version        int64              `json:"version"`
}

type MarkTicketAdmittedRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	SessionID      uuid.UUID          `json:"session_id"`
	State          string             `json:"state"`
	Version        int64              `json:"version"`
	EntryOpensAt   time.Time          `json:"entry_opens_at"`
	EntryClosesAt  time.Time          `json:"entry_closes_at"`
	AdmittedAt     pgtype.Timestamptz `json:"admitted_at"`
}

func (q *Queries) MarkTicketAdmitted(ctx context.Context, arg MarkTicketAdmittedParams) (MarkTicketAdmittedRow, error) {
	row := q.db.QueryRow(ctx, markTicketAdmitted,
		arg.OrganizationID,
		arg.ID,
		arg.AdmittedAt,
		arg.Version,
	)
	var i MarkTicketAdmittedRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.State,
		&i.Version,
		&i.EntryOpensAt,
		&i.EntryClosesAt,
		&i.AdmittedAt,
	)
	return i, err
}
