// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	GetDatabaseTime(ctx context.Context) (time.Time, error)
	GetEntrySummaryMeta(ctx context.Context, arg GetEntrySummaryMetaParams) (GetEntrySummaryMetaRow, error)
	GetLatestEntryReceivedAt(ctx context.Context, arg GetLatestEntryReceivedAtParams) (time.Time, error)
	GetScanAttemptByDeviceKey(ctx context.Context, arg GetScanAttemptByDeviceKeyParams) (ScanAttempt, error)
	InsertAdmission(ctx context.Context, arg InsertAdmissionParams) error
	InsertScanAttempt(ctx context.Context, arg InsertScanAttemptParams) (ScanAttempt, error)
	IsDeviceAuthorizedForScan(ctx context.Context, arg IsDeviceAuthorizedForScanParams) (bool, error)
	ListEntrySummaryRows(ctx context.Context, arg ListEntrySummaryRowsParams) ([]ListEntrySummaryRowsRow, error)
	LockDeviceForScan(ctx context.Context, arg LockDeviceForScanParams) (LockDeviceForScanRow, error)
	LockTicketForScan(ctx context.Context, arg LockTicketForScanParams) (LockTicketForScanRow, error)
	MarkTicketAdmitted(ctx context.Context, arg MarkTicketAdmittedParams) (MarkTicketAdmittedRow, error)
}

var _ Querier = (*Queries)(nil)
