// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCartForOwner = `-- name: GetCartForOwner :one
SELECT id, organization_id, session_id, hold_id, owner_token_hash, owner_user_id,
       currency, state, quote_snapshot, quote_snapshot_raw, quote_sha256, version, created_at, updated_at
FROM carts
WHERE organization_id = $1
  AND id = $2
  AND owner_token_hash = $3
`

type GetCartForOwnerParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
}

type GetCartForOwnerRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	HoldID           uuid.UUID   `json:"hold_id"`
	OwnerTokenHash   []byte      `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	QuoteSnapshot    []byte      `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte      `json:"quote_snapshot_raw"`
	QuoteSha256      []byte      `json:"quote_sha256"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) GetCartForOwner(ctx context.Context, arg GetCartForOwnerParams) (GetCartForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getCartForOwner, arg.OrganizationID, arg.ID, arg.OwnerTokenHash)
	var i GetCartForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.HoldID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.Currency,
		&i.State,
		&i.QuoteSnapshot,
		&i.QuoteSnapshotRaw,
		&i.QuoteSha256,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now()::timestamptz
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const insertCart = `-- name: InsertCart :one
INSERT INTO carts (
    id, organization_id, session_id, hold_id, owner_token_hash, owner_user_id,
    currency, state, quote_snapshot, quote_snapshot_raw, quote_sha256, version, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $13)
RETURNING id, organization_id, session_id, hold_id, owner_token_hash, owner_user_id,
          currency, state, quote_snapshot, quote_snapshot_raw, quote_sha256, version, created_at, updated_at
`

type InsertCartParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	HoldID           uuid.UUID   `json:"hold_id"`
	OwnerTokenHash   []byte      `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	QuoteSnapshot    []byte      `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte      `json:"quote_snapshot_raw"`
	QuoteSha256      []byte      `json:"quote_sha256"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
}

type InsertCartRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	HoldID           uuid.UUID   `json:"hold_id"`
	OwnerTokenHash   []byte      `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	QuoteSnapshot    []byte      `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte      `json:"quote_snapshot_raw"`
	QuoteSha256      []byte      `json:"quote_sha256"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) InsertCart(ctx context.Context, arg InsertCartParams) (InsertCartRow, error) {
	row := q.db.QueryRow(ctx, insertCart,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.HoldID,
		arg.OwnerTokenHash,
		arg.OwnerUserID,
		arg.Currency,
		arg.State,
		arg.QuoteSnapshot,
		arg.QuoteSnapshotRaw,
		arg.QuoteSha256,
		arg.Version,
		arg.CreatedAt,
	)
	var i InsertCartRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.HoldID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.Currency,
		&i.State,
		&i.QuoteSnapshot,
		&i.QuoteSnapshotRaw,
		&i.QuoteSha256,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockCartForOwner = `-- name: LockCartForOwner :one
SELECT id, organization_id, session_id, hold_id, owner_token_hash, owner_user_id,
       currency, state, quote_snapshot, quote_snapshot_raw, quote_sha256, version, created_at, updated_at
FROM carts
WHERE organization_id = $1
  AND id = $2
  AND owner_token_hash = $3
FOR UPDATE
`

type LockCartForOwnerParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
}

type LockCartForOwnerRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	HoldID           uuid.UUID   `json:"hold_id"`
	OwnerTokenHash   []byte      `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	QuoteSnapshot    []byte      `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte      `json:"quote_snapshot_raw"`
	QuoteSha256      []byte      `json:"quote_sha256"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) LockCartForOwner(ctx context.Context, arg LockCartForOwnerParams) (LockCartForOwnerRow, error) {
	row := q.db.QueryRow(ctx, lockCartForOwner, arg.OrganizationID, arg.ID, arg.OwnerTokenHash)
	var i LockCartForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.HoldID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.Currency,
		&i.State,
		&i.QuoteSnapshot,
		&i.QuoteSnapshotRaw,
		&i.QuoteSha256,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockHoldForCart = `-- name: LockHoldForCart :one
SELECT id, organization_id, session_id, currency, state, expires_at
FROM holds
WHERE organization_id = $1
  AND id = $2
  AND owner_token_hash = $3
FOR UPDATE
`

type LockHoldForCartParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
}

type LockHoldForCartRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	Currency       string    `json:"currency"`
	State          string    `json:"state"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) LockHoldForCart(ctx context.Context, arg LockHoldForCartParams) (LockHoldForCartRow, error) {
	row := q.db.QueryRow(ctx, lockHoldForCart, arg.OrganizationID, arg.ID, arg.OwnerTokenHash)
	var i LockHoldForCartRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.Currency,
		&i.State,
		&i.ExpiresAt,
	)
	return i, err
}

const updateCartQuote = `-- name: UpdateCartQuote :one
UPDATE carts
SET quote_snapshot = $1,
    quote_snapshot_raw = $2,
    quote_sha256 = $3,
    version = version + 1,
    updated_at = $4
 WHERE organization_id = $5
  AND id = $6
  AND owner_token_hash = $7
  AND state = 'active'
  AND version = $8
RETURNING id, organization_id, session_id, hold_id, owner_token_hash, owner_user_id,
          currency, state, quote_snapshot, quote_snapshot_raw, quote_sha256, version, created_at, updated_at
`

type UpdateCartQuoteParams struct {
	QuoteSnapshot    []byte    `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte    `json:"quote_snapshot_raw"`
	QuoteSha256      []byte    `json:"quote_sha256"`
	UpdatedAt        time.Time `json:"updated_at"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	ID               uuid.UUID `json:"id"`
	OwnerTokenHash   []byte    `json:"owner_token_hash"`
	Version          int64     `json:"version"`
}

type UpdateCartQuoteRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	SessionID        uuid.UUID   `json:"session_id"`
	HoldID           uuid.UUID   `json:"hold_id"`
	OwnerTokenHash   []byte      `json:"owner_token_hash"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	QuoteSnapshot    []byte      `json:"quote_snapshot"`
	QuoteSnapshotRaw []byte      `json:"quote_snapshot_raw"`
	QuoteSha256      []byte      `json:"quote_sha256"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateCartQuote(ctx context.Context, arg UpdateCartQuoteParams) (UpdateCartQuoteRow, error) {
	row := q.db.QueryRow(ctx, updateCartQuote,
		arg.QuoteSnapshot,
		arg.QuoteSnapshotRaw,
		arg.QuoteSha256,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
		arg.OwnerTokenHash,
		arg.Version,
	)
	var i UpdateCartQuoteRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.HoldID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.Currency,
		&i.State,
		&i.QuoteSnapshot,
		&i.QuoteSnapshotRaw,
		&i.QuoteSha256,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
