// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	GetCartForOwner(ctx context.Context, arg GetCartForOwnerParams) (GetCartForOwnerRow, error)
	GetDatabaseTime(ctx context.Context) (time.Time, error)
	InsertCart(ctx context.Context, arg InsertCartParams) (InsertCartRow, error)
	LockCartForOwner(ctx context.Context, arg LockCartForOwnerParams) (LockCartForOwnerRow, error)
	LockHoldForCart(ctx context.Context, arg LockHoldForCartParams) (LockHoldForCartRow, error)
	UpdateCartQuote(ctx context.Context, arg UpdateCartQuoteParams) (UpdateCartQuoteRow, error)
}

var _ Querier = (*Queries)(nil)
