// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	FinalizeRefund(ctx context.Context, arg FinalizeRefundParams) (Refund, error)
	GetDatabaseTime(ctx context.Context) (time.Time, error)
	GetRefund(ctx context.Context, arg GetRefundParams) (Refund, error)
	GetRefundByIdempotency(ctx context.Context, arg GetRefundByIdempotencyParams) (Refund, error)
	InsertRefund(ctx context.Context, arg InsertRefundParams) (Refund, error)
	LockOrderForRefund(ctx context.Context, arg LockOrderForRefundParams) (LockOrderForRefundRow, error)
	LockPaymentForRefund(ctx context.Context, arg LockPaymentForRefundParams) (LockPaymentForRefundRow, error)
	LockRefundExecution(ctx context.Context, arg LockRefundExecutionParams) (LockRefundExecutionRow, error)
	MarkRefundProcessing(ctx context.Context, arg MarkRefundProcessingParams) (Refund, error)
	SumAllocatedRefunds(ctx context.Context, arg SumAllocatedRefundsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
