// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refund.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const finalizeRefund = `-- name: FinalizeRefund :one
UPDATE refunds
SET state = $3, provider_refund_id = $4, version = version + 1, updated_at = $5
WHERE organization_id = $1 AND id = $2 AND version = $6 AND state = 'processing'
RETURNING id, organization_id, order_id, payment_attempt_id, amount_minor,
          currency, state, idempotency_key, reason, actor_type, actor_id,
          provider_refund_id, version, created_at, updated_at
`

type FinalizeRefundParams struct {
	OrganizationID   uuid.UUID   `json:"organization_id"`
	ID               uuid.UUID   `json:"id"`
	State            string      `json:"state"`
	ProviderRefundID pgtype.Text `json:"provider_refund_id"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Version          int64       `json:"version"`
}

func (q *Queries) FinalizeRefund(ctx context.Context, arg FinalizeRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, finalizeRefund,
		arg.OrganizationID,
		arg.ID,
		arg.State,
		arg.ProviderRefundID,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.PaymentAttemptID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.Reason,
		&i.ActorType,
		&i.ActorID,
		&i.ProviderRefundID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now()::timestamptz
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const getRefund = `-- name: GetRefund :one
SELECT id, organization_id, order_id, payment_attempt_id, amount_minor,
       currency, state, idempotency_key, reason, actor_type, actor_id,
       provider_refund_id, version, created_at, updated_at
FROM refunds
WHERE organization_id = $1
  AND id = $2
`

type GetRefundParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetRefund(ctx context.Context, arg GetRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefund, arg.OrganizationID, arg.ID)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.PaymentAttemptID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.Reason,
		&i.ActorType,
		&i.ActorID,
		&i.ProviderRefundID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundByIdempotency = `-- name: GetRefundByIdempotency :one
SELECT id, organization_id, order_id, payment_attempt_id, amount_minor,
       currency, state, idempotency_key, reason, actor_type, actor_id,
       provider_refund_id, version, created_at, updated_at
FROM refunds
WHERE organization_id = $1
  AND order_id = $2
  AND idempotency_key = $3
FOR UPDATE
`

type GetRefundByIdempotencyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	OrderID        uuid.UUID `json:"order_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetRefundByIdempotency(ctx context.Context, arg GetRefundByIdempotencyParams) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByIdempotency, arg.OrganizationID, arg.OrderID, arg.IdempotencyKey)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.PaymentAttemptID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.Reason,
		&i.ActorType,
		&i.ActorID,
		&i.ProviderRefundID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRefund = `-- name: InsertRefund :one
INSERT INTO refunds (
    id, organization_id, order_id, payment_attempt_id, amount_minor, currency,
    state, idempotency_key, reason, actor_type, actor_id, version, created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $13)
ON CONFLICT (organization_id, order_id, idempotency_key) DO NOTHING
RETURNING id, organization_id, order_id, payment_attempt_id, amount_minor,
          currency, state, idempotency_key, reason, actor_type, actor_id,
          provider_refund_id, version, created_at, updated_at
`

type InsertRefundParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	OrderID          uuid.UUID   `json:"order_id"`
	PaymentAttemptID uuid.UUID   `json:"payment_attempt_id"`
	AmountMinor      int64       `json:"amount_minor"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	IdempotencyKey   string      `json:"idempotency_key"`
	Reason           string      `json:"reason"`
	ActorType        string      `json:"actor_type"`
	ActorID          pgtype.Text `json:"actor_id"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, insertRefund,
		arg.ID,
		arg.OrganizationID,
		arg.OrderID,
		arg.PaymentAttemptID,
		arg.AmountMinor,
		arg.Currency,
		arg.State,
		arg.IdempotencyKey,
		arg.Reason,
		arg.ActorType,
		arg.ActorID,
		arg.Version,
		arg.CreatedAt,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.PaymentAttemptID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.Reason,
		&i.ActorType,
		&i.ActorID,
		&i.ProviderRefundID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOrderForRefund = `-- name: LockOrderForRefund :one
SELECT id, organization_id, currency, state
FROM orders
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockOrderForRefundParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockOrderForRefundRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Currency       string    `json:"currency"`
	State          string    `json:"state"`
}

func (q *Queries) LockOrderForRefund(ctx context.Context, arg LockOrderForRefundParams) (LockOrderForRefundRow, error) {
	row := q.db.QueryRow(ctx, lockOrderForRefund, arg.OrganizationID, arg.ID)
	var i LockOrderForRefundRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.State,
	)
	return i, err
}

const lockPaymentForRefund = `-- name: LockPaymentForRefund :one
SELECT id, organization_id, order_id, amount_minor, currency, state
FROM payment_attempts
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockPaymentForRefundParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockPaymentForRefundRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	OrderID        uuid.UUID `json:"order_id"`
	AmountMinor    int64     `json:"amount_minor"`
	Currency       string    `json:"currency"`
	State          string    `json:"state"`
}

func (q *Queries) LockPaymentForRefund(ctx context.Context, arg LockPaymentForRefundParams) (LockPaymentForRefundRow, error) {
	row := q.db.QueryRow(ctx, lockPaymentForRefund, arg.OrganizationID, arg.ID)
	var i LockPaymentForRefundRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
	)
	return i, err
}

const lockRefundExecution = `-- name: LockRefundExecution :one
SELECT r.id, r.organization_id, r.order_id, r.payment_attempt_id,
       r.amount_minor, r.currency, r.state, r.idempotency_key, r.reason,
       r.actor_type, r.actor_id, r.provider_refund_id, r.version,
       r.created_at, r.updated_at, p.provider, p.provider_object_id
FROM refunds AS r
JOIN payment_attempts AS p
  ON p.organization_id = r.organization_id AND p.id = r.payment_attempt_id
WHERE r.organization_id = $1 AND r.id = $2
FOR UPDATE OF r, p
`

type LockRefundExecutionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockRefundExecutionRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	OrderID          uuid.UUID   `json:"order_id"`
	PaymentAttemptID uuid.UUID   `json:"payment_attempt_id"`
	AmountMinor      int64       `json:"amount_minor"`
	Currency         string      `json:"currency"`
	State            string      `json:"state"`
	IdempotencyKey   string      `json:"idempotency_key"`
	Reason           string      `json:"reason"`
	ActorType        string      `json:"actor_type"`
	ActorID          pgtype.Text `json:"actor_id"`
	ProviderRefundID pgtype.Text `json:"provider_refund_id"`
	Version          int64       `json:"version"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Provider         string      `json:"provider"`
	ProviderObjectID pgtype.Text `json:"provider_object_id"`
}

func (q *Queries) LockRefundExecution(ctx context.Context, arg LockRefundExecutionParams) (LockRefundExecutionRow, error) {
	row := q.db.QueryRow(ctx, lockRefundExecution, arg.OrganizationID, arg.ID)
	var i LockRefundExecutionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.PaymentAttemptID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.Reason,
		&i.ActorType,
		&i.ActorID,
		&i.ProviderRefundID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderObjectID,
	)
	return i, err
}

const markRefundProcessing = `-- name: MarkRefundProcessing :one
UPDATE refunds
SET state = 'processing', version = version + 1, updated_at = $3
WHERE organization_id = $1 AND id = $2 AND version = $4 AND state = 'requested'
RETURNING id, organization_id, order_id, payment_attempt_id, amount_minor,
          currency, state, idempotency_key, reason, actor_type, actor_id,
          provider_refund_id, version, created_at, updated_at
`

type MarkRefundProcessingParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	UpdatedAt      time.Time `json:"updated_at"`
	Version        int64     `json:"version"`
}

func (q *Queries) MarkRefundProcessing(ctx context.Context, arg MarkRefundProcessingParams) (Refund, error) {
	row := q.db.QueryRow(ctx, markRefundProcessing,
		arg.OrganizationID,
		arg.ID,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.PaymentAttemptID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.Reason,
		&i.ActorType,
		&i.ActorID,
		&i.ProviderRefundID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumAllocatedRefunds = `-- name: SumAllocatedRefunds :one
SELECT COALESCE(SUM(amount_minor), 0)::bigint
FROM refunds
WHERE organization_id = $1
  AND order_id = $2
  AND payment_attempt_id = $3
  AND state IN ('requested', 'processing', 'succeeded')
`

type SumAllocatedRefundsParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrderID          uuid.UUID `json:"order_id"`
	PaymentAttemptID uuid.UUID `json:"payment_attempt_id"`
}

func (q *Queries) SumAllocatedRefunds(ctx context.Context, arg SumAllocatedRefundsParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumAllocatedRefunds, arg.OrganizationID, arg.OrderID, arg.PaymentAttemptID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
