// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHoldItems = `-- name: DeleteHoldItems :execrows
DELETE FROM hold_items
WHERE organization_id = $1
  AND hold_id = $2
`

type DeleteHoldItemsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	HoldID         uuid.UUID `json:"hold_id"`
}

func (q *Queries) DeleteHoldItems(ctx context.Context, arg DeleteHoldItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHoldItems, arg.OrganizationID, arg.HoldID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireHold = `-- name: ExpireHold :one
UPDATE holds
SET state = 'expired', version = version + 1, updated_at = $1
WHERE organization_id = $2 AND id = $3 AND state = 'active'
RETURNING id, organization_id, session_id, version, updated_at
`

type ExpireHoldParams struct {
	UpdatedAt      time.Time `json:"updated_at"`
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type ExpireHoldRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	Version        int64     `json:"version"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ExpireHold(ctx context.Context, arg ExpireHoldParams) (ExpireHoldRow, error) {
	row := q.db.QueryRow(ctx, expireHold, arg.UpdatedAt, arg.OrganizationID, arg.ID)
	var i ExpireHoldRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailabilityEventBounds = `-- name: GetAvailabilityEventBounds :one
SELECT COALESCE(MIN(sequence), 0)::bigint AS first_sequence,
       COALESCE(MAX(sequence), 0)::bigint AS last_sequence
FROM realtime_events
WHERE organization_id = $1
  AND session_id = $2
  AND topic = 'availability'
`

type GetAvailabilityEventBoundsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

type GetAvailabilityEventBoundsRow struct {
	FirstSequence int64 `json:"first_sequence"`
	LastSequence  int64 `json:"last_sequence"`
}

func (q *Queries) GetAvailabilityEventBounds(ctx context.Context, arg GetAvailabilityEventBoundsParams) (GetAvailabilityEventBoundsRow, error) {
	row := q.db.QueryRow(ctx, getAvailabilityEventBounds, arg.OrganizationID, arg.SessionID)
	var i GetAvailabilityEventBoundsRow
	err := row.Scan(&i.FirstSequence, &i.LastSequence)
	return i, err
}

const getAvailabilitySession = `-- name: GetAvailabilitySession :one
SELECT id, organization_id, inventory_mode, status, inventory_revision, now()::timestamptz AS server_time
FROM sessions
WHERE organization_id = $1 AND id = $2
`

type GetAvailabilitySessionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetAvailabilitySessionRow struct {
	ID                uuid.UUID `json:"id"`
	OrganizationID    uuid.UUID `json:"organization_id"`
	InventoryMode     string    `json:"inventory_mode"`
	Status            string    `json:"status"`
	InventoryRevision int64     `json:"inventory_revision"`
	ServerTime        time.Time `json:"server_time"`
}

func (q *Queries) GetAvailabilitySession(ctx context.Context, arg GetAvailabilitySessionParams) (GetAvailabilitySessionRow, error) {
	row := q.db.QueryRow(ctx, getAvailabilitySession, arg.OrganizationID, arg.ID)
	var i GetAvailabilitySessionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InventoryMode,
		&i.Status,
		&i.InventoryRevision,
		&i.ServerTime,
	)
	return i, err
}

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now()::timestamptz
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const holdSessionSeat = `-- name: HoldSessionSeat :execrows
UPDATE session_seats
SET state = 'held', hold_id = $1, hold_expires_at = $2, version = version + 1, updated_at = $3
WHERE organization_id = $4
  AND session_id = $5
  AND id = $6
  AND state = 'available'
  AND sellable = true
`

type HoldSessionSeatParams struct {
	HoldID         pgtype.UUID        `json:"hold_id"`
	HoldExpiresAt  pgtype.Timestamptz `json:"hold_expires_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	SessionID      uuid.UUID          `json:"session_id"`
	SeatID         uuid.UUID          `json:"seat_id"`
}

func (q *Queries) HoldSessionSeat(ctx context.Context, arg HoldSessionSeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, holdSessionSeat,
		arg.HoldID,
		arg.HoldExpiresAt,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.SessionID,
		arg.SeatID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementSessionInventoryRevision = `-- name: IncrementSessionInventoryRevision :one
UPDATE sessions
SET inventory_revision = inventory_revision + 1, updated_at = $1
WHERE organization_id = $2 AND id = $3
RETURNING inventory_revision
`

type IncrementSessionInventoryRevisionParams struct {
	UpdatedAt      time.Time `json:"updated_at"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

func (q *Queries) IncrementSessionInventoryRevision(ctx context.Context, arg IncrementSessionInventoryRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementSessionInventoryRevision, arg.UpdatedAt, arg.OrganizationID, arg.SessionID)
	var inventory_revision int64
	err := row.Scan(&inventory_revision)
	return inventory_revision, err
}

const insertHold = `-- name: InsertHold :one
INSERT INTO holds (id, organization_id, session_id, owner_token_hash, owner_user_id, channel_id, currency, state, expires_at, renewal_count, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12)
RETURNING id, organization_id, session_id, owner_token_hash, owner_user_id, channel_id, currency, state, expires_at, renewal_count, version, created_at, updated_at
`

type InsertHoldParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	SessionID      uuid.UUID   `json:"session_id"`
	OwnerTokenHash []byte      `json:"owner_token_hash"`
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
	ChannelID      pgtype.UUID `json:"channel_id"`
	Currency       string      `json:"currency"`
	State          string      `json:"state"`
	ExpiresAt      time.Time   `json:"expires_at"`
	RenewalCount   int32       `json:"renewal_count"`
	Version        int64       `json:"version"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) InsertHold(ctx context.Context, arg InsertHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, insertHold,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.OwnerTokenHash,
		arg.OwnerUserID,
		arg.ChannelID,
		arg.Currency,
		arg.State,
		arg.ExpiresAt,
		arg.RenewalCount,
		arg.Version,
		arg.CreatedAt,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.ChannelID,
		&i.Currency,
		&i.State,
		&i.ExpiresAt,
		&i.RenewalCount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHoldItem = `-- name: InsertHoldItem :one
INSERT INTO hold_items (id, organization_id, hold_id, session_id, pool_id, seat_id, quantity, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, hold_id, session_id, pool_id, seat_id, quantity, created_at
`

type InsertHoldItemParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	HoldID         uuid.UUID   `json:"hold_id"`
	SessionID      uuid.UUID   `json:"session_id"`
	PoolID         pgtype.UUID `json:"pool_id"`
	SeatID         pgtype.UUID `json:"seat_id"`
	Quantity       int64       `json:"quantity"`
	CreatedAt      time.Time   `json:"created_at"`
}

type InsertHoldItemRow struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	HoldID         uuid.UUID   `json:"hold_id"`
	SessionID      uuid.UUID   `json:"session_id"`
	PoolID         pgtype.UUID `json:"pool_id"`
	SeatID         pgtype.UUID `json:"seat_id"`
	Quantity       int64       `json:"quantity"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) InsertHoldItem(ctx context.Context, arg InsertHoldItemParams) (InsertHoldItemRow, error) {
	row := q.db.QueryRow(ctx, insertHoldItem,
		arg.ID,
		arg.OrganizationID,
		arg.HoldID,
		arg.SessionID,
		arg.PoolID,
		arg.SeatID,
		arg.Quantity,
		arg.CreatedAt,
	)
	var i InsertHoldItemRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.HoldID,
		&i.SessionID,
		&i.PoolID,
		&i.SeatID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listAvailabilityEventsAfter = `-- name: ListAvailabilityEventsAfter :many
SELECT id, session_id, sequence, event_type, schema_version, payload, occurred_at
FROM realtime_events
WHERE organization_id = $1
  AND session_id = $2
  AND topic = 'availability'
  AND sequence > $3
ORDER BY sequence ASC
LIMIT $4
`

type ListAvailabilityEventsAfterParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	AfterSequence  int64     `json:"after_sequence"`
	PageLimit      int32     `json:"page_limit"`
}

type ListAvailabilityEventsAfterRow struct {
	ID            uuid.UUID `json:"id"`
	SessionID     uuid.UUID `json:"session_id"`
	Sequence      int64     `json:"sequence"`
	EventType     string    `json:"event_type"`
	SchemaVersion int32     `json:"schema_version"`
	Payload       []byte    `json:"payload"`
	OccurredAt    time.Time `json:"occurred_at"`
}

func (q *Queries) ListAvailabilityEventsAfter(ctx context.Context, arg ListAvailabilityEventsAfterParams) ([]ListAvailabilityEventsAfterRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityEventsAfter,
		arg.OrganizationID,
		arg.SessionID,
		arg.AfterSequence,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilityEventsAfterRow{}
	for rows.Next() {
		var i ListAvailabilityEventsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Sequence,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldItems = `-- name: ListHoldItems :many
SELECT id, organization_id, hold_id, session_id, pool_id, seat_id, quantity, created_at
FROM hold_items
WHERE organization_id = $1 AND hold_id = $2
ORDER BY id ASC
FOR UPDATE
`

type ListHoldItemsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	HoldID         uuid.UUID `json:"hold_id"`
}

type ListHoldItemsRow struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	HoldID         uuid.UUID   `json:"hold_id"`
	SessionID      uuid.UUID   `json:"session_id"`
	PoolID         pgtype.UUID `json:"pool_id"`
	SeatID         pgtype.UUID `json:"seat_id"`
	Quantity       int64       `json:"quantity"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) ListHoldItems(ctx context.Context, arg ListHoldItemsParams) ([]ListHoldItemsRow, error) {
	rows, err := q.db.Query(ctx, listHoldItems, arg.OrganizationID, arg.HoldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHoldItemsRow{}
	for rows.Next() {
		var i ListHoldItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.HoldID,
			&i.SessionID,
			&i.PoolID,
			&i.SeatID,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionGAPoolAvailability = `-- name: ListSessionGAPoolAvailability :many
SELECT id, slug, sellable_capacity, sold_qty, held_qty, killed_qty, comped_qty, version
FROM session_ga_pools
WHERE organization_id = $1 AND session_id = $2
ORDER BY slug ASC, id ASC
`

type ListSessionGAPoolAvailabilityParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

type ListSessionGAPoolAvailabilityRow struct {
	ID               uuid.UUID `json:"id"`
	Slug             string    `json:"slug"`
	SellableCapacity int64     `json:"sellable_capacity"`
	SoldQty          int64     `json:"sold_qty"`
	HeldQty          int64     `json:"held_qty"`
	KilledQty        int64     `json:"killed_qty"`
	CompedQty        int64     `json:"comped_qty"`
	Version          int64     `json:"version"`
}

func (q *Queries) ListSessionGAPoolAvailability(ctx context.Context, arg ListSessionGAPoolAvailabilityParams) ([]ListSessionGAPoolAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listSessionGAPoolAvailability, arg.OrganizationID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionGAPoolAvailabilityRow{}
	for rows.Next() {
		var i ListSessionGAPoolAvailabilityRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.SellableCapacity,
			&i.SoldQty,
			&i.HeldQty,
			&i.KilledQty,
			&i.CompedQty,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSeatAvailability = `-- name: ListSessionSeatAvailability :many
SELECT id, seat_key, label, category, sellable, wheelchair, state, version
FROM session_seats
WHERE organization_id = $1 AND session_id = $2
ORDER BY seat_key ASC, id ASC
`

type ListSessionSeatAvailabilityParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

type ListSessionSeatAvailabilityRow struct {
	ID         uuid.UUID `json:"id"`
	SeatKey    string    `json:"seat_key"`
	Label      string    `json:"label"`
	Category   string    `json:"category"`
	Sellable   bool      `json:"sellable"`
	Wheelchair bool      `json:"wheelchair"`
	State      string    `json:"state"`
	Version    int64     `json:"version"`
}

func (q *Queries) ListSessionSeatAvailability(ctx context.Context, arg ListSessionSeatAvailabilityParams) ([]ListSessionSeatAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listSessionSeatAvailability, arg.OrganizationID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionSeatAvailabilityRow{}
	for rows.Next() {
		var i ListSessionSeatAvailabilityRow
		if err := rows.Scan(
			&i.ID,
			&i.SeatKey,
			&i.Label,
			&i.Category,
			&i.Sellable,
			&i.Wheelchair,
			&i.State,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueHolds = `-- name: LockDueHolds :many
SELECT id, organization_id, session_id
FROM holds
WHERE state = 'active'
  AND expires_at <= $1
ORDER BY expires_at ASC, id ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type LockDueHoldsParams struct {
	Now        time.Time `json:"now"`
	BatchLimit int32     `json:"batch_limit"`
}

type LockDueHoldsRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

func (q *Queries) LockDueHolds(ctx context.Context, arg LockDueHoldsParams) ([]LockDueHoldsRow, error) {
	rows, err := q.db.Query(ctx, lockDueHolds, arg.Now, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockDueHoldsRow{}
	for rows.Next() {
		var i LockDueHoldsRow
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHoldForOwner = `-- name: LockHoldForOwner :one
SELECT id, organization_id, session_id, owner_token_hash, owner_user_id, channel_id, currency, state, expires_at, renewal_count, version, created_at, updated_at
FROM holds
WHERE organization_id = $1 AND id = $2 AND owner_token_hash = $3
FOR UPDATE
`

type LockHoldForOwnerParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
	OwnerTokenHash []byte    `json:"owner_token_hash"`
}

func (q *Queries) LockHoldForOwner(ctx context.Context, arg LockHoldForOwnerParams) (Hold, error) {
	row := q.db.QueryRow(ctx, lockHoldForOwner, arg.OrganizationID, arg.ID, arg.OwnerTokenHash)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.ChannelID,
		&i.Currency,
		&i.State,
		&i.ExpiresAt,
		&i.RenewalCount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSessionForGAHold = `-- name: LockSessionForGAHold :one
SELECT id, status, inventory_mode, inventory_revision
FROM sessions
WHERE organization_id = $1 AND id = $2
FOR UPDATE
`

type LockSessionForGAHoldParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockSessionForGAHoldRow struct {
	ID                uuid.UUID `json:"id"`
	Status            string    `json:"status"`
	InventoryMode     string    `json:"inventory_mode"`
	InventoryRevision int64     `json:"inventory_revision"`
}

func (q *Queries) LockSessionForGAHold(ctx context.Context, arg LockSessionForGAHoldParams) (LockSessionForGAHoldRow, error) {
	row := q.db.QueryRow(ctx, lockSessionForGAHold, arg.OrganizationID, arg.ID)
	var i LockSessionForGAHoldRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.InventoryMode,
		&i.InventoryRevision,
	)
	return i, err
}

const lockSessionSeatsForHold = `-- name: LockSessionSeatsForHold :many
SELECT id, organization_id, session_id, seat_map_version_id, state, sellable, hold_id, hold_expires_at, version
FROM session_seats
WHERE organization_id = $1
  AND session_id = $2
  AND id = ANY($3::uuid[])
ORDER BY id ASC
FOR UPDATE
`

type LockSessionSeatsForHoldParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SessionID      uuid.UUID   `json:"session_id"`
	SeatIds        []uuid.UUID `json:"seat_ids"`
}

type LockSessionSeatsForHoldRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	SessionID        uuid.UUID          `json:"session_id"`
	SeatMapVersionID uuid.UUID          `json:"seat_map_version_id"`
	State            string             `json:"state"`
	Sellable         bool               `json:"sellable"`
	HoldID           pgtype.UUID        `json:"hold_id"`
	HoldExpiresAt    pgtype.Timestamptz `json:"hold_expires_at"`
	Version          int64              `json:"version"`
}

func (q *Queries) LockSessionSeatsForHold(ctx context.Context, arg LockSessionSeatsForHoldParams) ([]LockSessionSeatsForHoldRow, error) {
	rows, err := q.db.Query(ctx, lockSessionSeatsForHold, arg.OrganizationID, arg.SessionID, arg.SeatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockSessionSeatsForHoldRow{}
	for rows.Next() {
		var i LockSessionSeatsForHoldRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.SeatMapVersionID,
			&i.State,
			&i.Sellable,
			&i.HoldID,
			&i.HoldExpiresAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseGAPool = `-- name: ReleaseGAPool :execrows
UPDATE session_ga_pools
SET held_qty = held_qty - $1, version = version + 1, updated_at = $2
WHERE organization_id = $3
  AND session_id = $4
  AND id = $5
  AND held_qty >= $1
`

type ReleaseGAPoolParams struct {
	Quantity       int64     `json:"quantity"`
	UpdatedAt      time.Time `json:"updated_at"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	PoolID         uuid.UUID `json:"pool_id"`
}

func (q *Queries) ReleaseGAPool(ctx context.Context, arg ReleaseGAPoolParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseGAPool,
		arg.Quantity,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.SessionID,
		arg.PoolID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseSessionSeat = `-- name: ReleaseSessionSeat :execrows
UPDATE session_seats
SET state = 'available', hold_id = NULL, hold_expires_at = NULL, version = version + 1, updated_at = $1
WHERE organization_id = $2
  AND session_id = $3
  AND id = $4
  AND state = 'held'
  AND hold_id = $5
`

type ReleaseSessionSeatParams struct {
	UpdatedAt      time.Time   `json:"updated_at"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	SessionID      uuid.UUID   `json:"session_id"`
	SeatID         uuid.UUID   `json:"seat_id"`
	HoldID         pgtype.UUID `json:"hold_id"`
}

func (q *Queries) ReleaseSessionSeat(ctx context.Context, arg ReleaseSessionSeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseSessionSeat,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.SessionID,
		arg.SeatID,
		arg.HoldID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewHold = `-- name: RenewHold :one
UPDATE holds
SET expires_at = $1, renewal_count = renewal_count + 1, version = version + 1, updated_at = $2
WHERE organization_id = $3
  AND id = $4
  AND state = 'active'
  AND version = $5
  AND renewal_count < 1
  AND expires_at > $6
RETURNING id, organization_id, session_id, owner_token_hash, owner_user_id, channel_id, currency, state, expires_at, renewal_count, version, created_at, updated_at
`

type RenewHoldParams struct {
	NewExpiresAt    time.Time `json:"new_expires_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int64     `json:"expected_version"`
	DatabaseNow     time.Time `json:"database_now"`
}

func (q *Queries) RenewHold(ctx context.Context, arg RenewHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, renewHold,
		arg.NewExpiresAt,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
		arg.ExpectedVersion,
		arg.DatabaseNow,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.ChannelID,
		&i.Currency,
		&i.State,
		&i.ExpiresAt,
		&i.RenewalCount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGAPoolForHold = `-- name: UpdateGAPoolForHold :one
UPDATE session_ga_pools
SET held_qty = held_qty + $1, version = version + 1, updated_at = $2
WHERE organization_id = $3
  AND session_id = $4
  AND id = $5
  AND sellable_capacity - sold_qty - held_qty - killed_qty - comped_qty >= $1
RETURNING id, organization_id, session_id, held_qty, version
`

type UpdateGAPoolForHoldParams struct {
	Quantity       int64     `json:"quantity"`
	UpdatedAt      time.Time `json:"updated_at"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	PoolID         uuid.UUID `json:"pool_id"`
}

type UpdateGAPoolForHoldRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	SessionID      uuid.UUID `json:"session_id"`
	HeldQty        int64     `json:"held_qty"`
	Version        int64     `json:"version"`
}

func (q *Queries) UpdateGAPoolForHold(ctx context.Context, arg UpdateGAPoolForHoldParams) (UpdateGAPoolForHoldRow, error) {
	row := q.db.QueryRow(ctx, updateGAPoolForHold,
		arg.Quantity,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.SessionID,
		arg.PoolID,
	)
	var i UpdateGAPoolForHoldRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.HeldQty,
		&i.Version,
	)
	return i, err
}

const updateHoldForModification = `-- name: UpdateHoldForModification :one
UPDATE holds
SET version = version + 1, updated_at = $1
WHERE organization_id = $2
  AND id = $3
  AND state = 'active'
  AND version = $4
RETURNING id, organization_id, session_id, owner_token_hash, owner_user_id, channel_id, currency, state, expires_at, renewal_count, version, created_at, updated_at
`

type UpdateHoldForModificationParams struct {
	UpdatedAt       time.Time `json:"updated_at"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) UpdateHoldForModification(ctx context.Context, arg UpdateHoldForModificationParams) (Hold, error) {
	row := q.db.QueryRow(ctx, updateHoldForModification,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.ChannelID,
		&i.Currency,
		&i.State,
		&i.ExpiresAt,
		&i.RenewalCount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHoldState = `-- name: UpdateHoldState :one
UPDATE holds
SET state = $1, version = version + 1, updated_at = $2
WHERE organization_id = $3 AND id = $4 AND state = 'active'
RETURNING id, organization_id, session_id, owner_token_hash, owner_user_id, channel_id, currency, state, expires_at, renewal_count, version, created_at, updated_at
`

type UpdateHoldStateParams struct {
	State          string    `json:"state"`
	UpdatedAt      time.Time `json:"updated_at"`
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateHoldState(ctx context.Context, arg UpdateHoldStateParams) (Hold, error) {
	row := q.db.QueryRow(ctx, updateHoldState,
		arg.State,
		arg.UpdatedAt,
		arg.OrganizationID,
		arg.ID,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.OwnerTokenHash,
		&i.OwnerUserID,
		&i.ChannelID,
		&i.Currency,
		&i.State,
		&i.ExpiresAt,
		&i.RenewalCount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
