// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	DeleteHoldItems(ctx context.Context, arg DeleteHoldItemsParams) (int64, error)
	ExpireHold(ctx context.Context, arg ExpireHoldParams) (ExpireHoldRow, error)
	GetAvailabilityEventBounds(ctx context.Context, arg GetAvailabilityEventBoundsParams) (GetAvailabilityEventBoundsRow, error)
	GetAvailabilitySession(ctx context.Context, arg GetAvailabilitySessionParams) (GetAvailabilitySessionRow, error)
	GetDatabaseTime(ctx context.Context) (time.Time, error)
	HoldSessionSeat(ctx context.Context, arg HoldSessionSeatParams) (int64, error)
	IncrementSessionInventoryRevision(ctx context.Context, arg IncrementSessionInventoryRevisionParams) (int64, error)
	InsertHold(ctx context.Context, arg InsertHoldParams) (Hold, error)
	InsertHoldItem(ctx context.Context, arg InsertHoldItemParams) (InsertHoldItemRow, error)
	ListAvailabilityEventsAfter(ctx context.Context, arg ListAvailabilityEventsAfterParams) ([]ListAvailabilityEventsAfterRow, error)
	ListHoldItems(ctx context.Context, arg ListHoldItemsParams) ([]ListHoldItemsRow, error)
	ListSessionGAPoolAvailability(ctx context.Context, arg ListSessionGAPoolAvailabilityParams) ([]ListSessionGAPoolAvailabilityRow, error)
	ListSessionSeatAvailability(ctx context.Context, arg ListSessionSeatAvailabilityParams) ([]ListSessionSeatAvailabilityRow, error)
	LockDueHolds(ctx context.Context, arg LockDueHoldsParams) ([]LockDueHoldsRow, error)
	LockHoldForOwner(ctx context.Context, arg LockHoldForOwnerParams) (Hold, error)
	LockSessionForGAHold(ctx context.Context, arg LockSessionForGAHoldParams) (LockSessionForGAHoldRow, error)
	LockSessionSeatsForHold(ctx context.Context, arg LockSessionSeatsForHoldParams) ([]LockSessionSeatsForHoldRow, error)
	ReleaseGAPool(ctx context.Context, arg ReleaseGAPoolParams) (int64, error)
	ReleaseSessionSeat(ctx context.Context, arg ReleaseSessionSeatParams) (int64, error)
	RenewHold(ctx context.Context, arg RenewHoldParams) (Hold, error)
	UpdateGAPoolForHold(ctx context.Context, arg UpdateGAPoolForHoldParams) (UpdateGAPoolForHoldRow, error)
	UpdateHoldForModification(ctx context.Context, arg UpdateHoldForModificationParams) (Hold, error)
	UpdateHoldState(ctx context.Context, arg UpdateHoldStateParams) (Hold, error)
}

var _ Querier = (*Queries)(nil)
