// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now()::timestamptz
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const getPaymentAttempt = `-- name: GetPaymentAttempt :one
SELECT id, organization_id, order_id, provider, provider_object_id, amount_minor,
       currency, state, idempotency_key, failure_class, failure_code,
       failure_message, client_action_reference, metadata, version, created_at,
       updated_at
FROM payment_attempts
WHERE organization_id = $1
  AND id = $2
`

type GetPaymentAttemptParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetPaymentAttempt(ctx context.Context, arg GetPaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttempt, arg.OrganizationID, arg.ID)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderObjectID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.FailureClass,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ClientActionReference,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentAttempt = `-- name: InsertPaymentAttempt :one
INSERT INTO payment_attempts (
    id, organization_id, order_id, provider, provider_object_id, amount_minor,
    currency, state, idempotency_key, failure_class, failure_code,
    failure_message, client_action_reference, metadata, version, created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $16)
RETURNING id, organization_id, order_id, provider, provider_object_id, amount_minor,
          currency, state, idempotency_key, failure_class, failure_code,
          failure_message, client_action_reference, metadata, version, created_at,
          updated_at
`

type InsertPaymentAttemptParams struct {
	ID                    uuid.UUID   `json:"id"`
	OrganizationID        uuid.UUID   `json:"organization_id"`
	OrderID               uuid.UUID   `json:"order_id"`
	Provider              string      `json:"provider"`
	ProviderObjectID      pgtype.Text `json:"provider_object_id"`
	AmountMinor           int64       `json:"amount_minor"`
	Currency              string      `json:"currency"`
	State                 string      `json:"state"`
	IdempotencyKey        string      `json:"idempotency_key"`
	FailureClass          pgtype.Text `json:"failure_class"`
	FailureCode           pgtype.Text `json:"failure_code"`
	FailureMessage        pgtype.Text `json:"failure_message"`
	ClientActionReference pgtype.Text `json:"client_action_reference"`
	Metadata              []byte      `json:"metadata"`
	Version               int64       `json:"version"`
	CreatedAt             time.Time   `json:"created_at"`
}

func (q *Queries) InsertPaymentAttempt(ctx context.Context, arg InsertPaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, insertPaymentAttempt,
		arg.ID,
		arg.OrganizationID,
		arg.OrderID,
		arg.Provider,
		arg.ProviderObjectID,
		arg.AmountMinor,
		arg.Currency,
		arg.State,
		arg.IdempotencyKey,
		arg.FailureClass,
		arg.FailureCode,
		arg.FailureMessage,
		arg.ClientActionReference,
		arg.Metadata,
		arg.Version,
		arg.CreatedAt,
	)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderObjectID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.FailureClass,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ClientActionReference,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOrderForPayment = `-- name: LockOrderForPayment :one
SELECT id, organization_id, currency, state, total_minor
FROM orders
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockOrderForPaymentParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type LockOrderForPaymentRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Currency       string    `json:"currency"`
	State          string    `json:"state"`
	TotalMinor     int64     `json:"total_minor"`
}

func (q *Queries) LockOrderForPayment(ctx context.Context, arg LockOrderForPaymentParams) (LockOrderForPaymentRow, error) {
	row := q.db.QueryRow(ctx, lockOrderForPayment, arg.OrganizationID, arg.ID)
	var i LockOrderForPaymentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.State,
		&i.TotalMinor,
	)
	return i, err
}

const lockPaymentAttempt = `-- name: LockPaymentAttempt :one
SELECT id, organization_id, order_id, provider, provider_object_id, amount_minor,
       currency, state, idempotency_key, failure_class, failure_code,
       failure_message, client_action_reference, metadata, version, created_at,
       updated_at
FROM payment_attempts
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockPaymentAttemptParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) LockPaymentAttempt(ctx context.Context, arg LockPaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, lockPaymentAttempt, arg.OrganizationID, arg.ID)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderObjectID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.FailureClass,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ClientActionReference,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentAttempt = `-- name: UpdatePaymentAttempt :one
UPDATE payment_attempts
SET provider_object_id = $3,
    state = $4,
    failure_class = $5,
    failure_code = $6,
    failure_message = $7,
    client_action_reference = $8,
    metadata = $9,
    version = version + 1,
    updated_at = $10
WHERE organization_id = $1
  AND id = $2
  AND version = $11
RETURNING id, organization_id, order_id, provider, provider_object_id, amount_minor,
          currency, state, idempotency_key, failure_class, failure_code,
          failure_message, client_action_reference, metadata, version, created_at,
          updated_at
`

type UpdatePaymentAttemptParams struct {
	OrganizationID        uuid.UUID   `json:"organization_id"`
	ID                    uuid.UUID   `json:"id"`
	ProviderObjectID      pgtype.Text `json:"provider_object_id"`
	State                 string      `json:"state"`
	FailureClass          pgtype.Text `json:"failure_class"`
	FailureCode           pgtype.Text `json:"failure_code"`
	FailureMessage        pgtype.Text `json:"failure_message"`
	ClientActionReference pgtype.Text `json:"client_action_reference"`
	Metadata              []byte      `json:"metadata"`
	UpdatedAt             time.Time   `json:"updated_at"`
	Version               int64       `json:"version"`
}

func (q *Queries) UpdatePaymentAttempt(ctx context.Context, arg UpdatePaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, updatePaymentAttempt,
		arg.OrganizationID,
		arg.ID,
		arg.ProviderObjectID,
		arg.State,
		arg.FailureClass,
		arg.FailureCode,
		arg.FailureMessage,
		arg.ClientActionReference,
		arg.Metadata,
		arg.UpdatedAt,
		arg.Version,
	)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderObjectID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
		&i.IdempotencyKey,
		&i.FailureClass,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ClientActionReference,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
