// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	GetDatabaseTime(ctx context.Context) (time.Time, error)
	GetPaymentAttempt(ctx context.Context, arg GetPaymentAttemptParams) (PaymentAttempt, error)
	InsertPaymentAttempt(ctx context.Context, arg InsertPaymentAttemptParams) (PaymentAttempt, error)
	LockOrderForPayment(ctx context.Context, arg LockOrderForPaymentParams) (LockOrderForPaymentRow, error)
	LockPaymentAttempt(ctx context.Context, arg LockPaymentAttemptParams) (PaymentAttempt, error)
	UpdatePaymentAttempt(ctx context.Context, arg UpdatePaymentAttemptParams) (PaymentAttempt, error)
}

var _ Querier = (*Queries)(nil)
